version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  upload_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - codecov/upload
workflows:
  upload-to-codecov:
    jobs:
      - upload_job