version: 2.1
orbs:
  codecov: codecov/codecov@5
jobs:
  upload_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Upload to Codecov
          command: codecov
workflows:
  upload-to-codecov:
    jobs:
      - upload_job