# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

# test_that("Load_Zimsdata works", {
#   file = system.file("coretest.csv", package = 'ISRverse')
# RastDir = dirname(file)
# 
# data <- Load_Zimsdata	 (taxa = "Mammalia", 
#                            ZIMSdir = RastDir, 
#                            extractDate = "2023-12-04", 
#                            type = c('core','weights'),
#                            silent = TRUE) 
# expect_named(data, c("core",  "weights"))
#   expect_true(is.data.frame(core))
#   expect_true(is.data.frame(weights))
#   # expect_named(data$core, c("")) XXXXXXXXXXXXXXXXXXXXXXX
#   # expect_named(data$weights, c("")) XXXXXXXXXXXXXXXXXXXXXXX
#   unlink(ZIMSdirtest, recursive = TRUE)
# 
# })

