# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand

data = tibble(Age = c(rep(c(1:5),2),4),
              MeasurementValue= c(5,10000,3,6,5,4,100,2,5,3,4),
              AnimalAnonID = c(rep(1:2, each = 5),3),
              MeasurementType = "Live weight")

out= Gro_remoutliers(data, taxa = "Reptilia", ageMat = 10,
                     min_Nmeasures = 5, minq = 0.1, IQR = 1.2)

test_that(
  "Gro_outplot",
  {
    expect_error(out$MeasurementValue %>% Gro_outplot(),
                 regexp = "data is not a data frame")
  })

test_that(
  "Gro_outplot",
  { 
    p<- out %>% Gro_outplot()
    expect_named(p$labels,c("title", "x", "y"))
    expect_length(p$layers,5)
  })

