# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand


 test_that("make_summary works", {
file = system.file("Testudo_hermanni.RData", package = 'ISRverse')
AnalysisDir  = dirname(file)
TempDir = paste0(tempdir(check = TRUE),'\\temp')
dir.create(TempDir,showWarnings =FALSE)

SummTab <- make_summary(AnalysisDir, TempDir,
               taxaList = "Reptilia",
               BySex = list(Reptilia = c("Male", "Female")) ,
               Sections = c("sur", 'gro')
)
expect_true(file.exists(paste(TempDir, 'Survival_error.pdf', sep = '\\')))
expect_true(file.exists(paste(TempDir, 'SRGs_Survival.csv', sep = '\\')))
expect_true(file.exists(paste(TempDir, 'Growth_error.pdf', sep = '\\')))
expect_true(file.exists(paste(TempDir, 'SRGs_Growth.csv', sep = '\\')))
expect_true(file.exists(paste(TempDir, 'SRGs_Analyses.csv', sep = '\\')))
expect_named(SummTab , c("Class", "Species", "Sex", "Nraw", "Ndate", "Nglobal", "Nalive", "firstDate", "maxAgeraw",
                         "extractdate", "Nlifespan", "GapThresh", "NThres", "NBasta", "Surv_Ana", "Surv_error", "NWeight_raw", "NWeight", "Gro_Ana", "Gro_error", "Any_Ana", "All_Ana"))

unlink(TempDir, recursive = TRUE)
 })

