# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

test_that("Sur_ana works", {
  data(core)
  out <- Sur_ana(core,  models = "GO", shape = "bathtub",
                  niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
  expect_named(out, c("summary",  "bastaRes", "DICmods"))
  expect_named(out$DICmods, c("models",  "DIC"))
  expect_equal(nrow(out$DICmods),1)
  expect_named(out$summary, c("NGlobal", "NBasta", "Ndead", "maxAge", "maxAlive", "lxMin",    "outLev", "analyzed", "Nerr", "error"))
  expect_false(out$summary$analyzed )
  expect_true(is.numeric(out$summary$NGlobal ))
  expect_true(is.numeric(out$summary$NBasta ))
  expect_true(is.numeric(out$summary$Ndead ))
  expect_true(is.numeric(out$summary$maxAge ))
  expect_true(is.numeric(out$summary$maxAlive))
  expect_true(is.numeric(out$summary$lxMin ))
  expect_true(is.numeric(out$summary$outLev ))
  expect_true(is.numeric(out$summary$Nerr ))
  expect_true(class(out$bastaRes) == "basta")
})
