# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand

data(raw_weights)
data(core)

test_that("Gro_cleanmeasures works", {
  d=Gro_cleanmeasures(raw_weights, core)
  expect_named(
    d,
    c("binSpecies", "BirthDate", "Sex", "anonID", "AnonInstitutionID", "MeasurementType", "MeasurementDate", "age", "Measure", "Unit"))
  expect_true(unique(d$Unit) == "kilogram")
})
