# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

# test_that("make_summary works", {
#   file = system.file("gorilla gorilla.Rdata", package = 'ISRverse')
# AnalysisDir  = dirname(file)
# SaveDir = paste0(tempdir(check = TRUE),'\\temp')
# dir.create(SaveDir)
# 
# SummTab <- make_summary (AnalysisDir, SaveDir,
#                           taxaList = "Mammalia", 
#                           BySex = list(Mammalia = c("Male", "Female")) , 
#                           Sections = c("sur", 'gro')
# )
# expect_true(file.exists(paste(TempDir, 'Survival_error.pdf', sep = '\\')))
# expect_true(file.exists(paste(TempDir, 'SRGs_Survival.csv', sep = '\\')))
# expect_true(file.exists(paste(TempDir, 'Growth_error.pdf', sep = '\\')))
# expect_true(file.exists(paste(TempDir, 'SRGs_Growth.csv', sep = '\\')))
# expect_true(file.exists(paste(TempDir, 'SRGs_Analyses.csv', sep = '\\')))
#   # expect_named(SummTab , c()) XXXXXXXXXXXXXXXXXXXXXXXXXX
# 
# unlink(SaveDir, recursive = TRUE)
# })

