# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

test_that("Sur_out works", {
  data(core)
  data(deathinformation)
  out <- Sur_ana(core,  DeathInformation = deathinformation, models = "GO", shape = "simple",
                 niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
  
  out <- Sur_out(out, shape = "simple", ncpus = 3)
  expect_named(out, c("summary",  "bastaRes", "DICmods", "relex", 'L90', 'L50', 'Sur5', 'Sur1'))
  expect_named(out$summary, c("NGlobal", "NBasta", "Ndead", "maxAge", "maxAlive", "lxMin", "outLev", "analyzed", "Nerr", "error", "Gof_KM_coeff1", "Gof_KM_coeff2", "Gof_KM"))
  expect_named(out$relex, c("Age", "RemLExp", "Lower", "Upper"))
  expect_true(is.numeric(out$relex$Upper))
  expect_true(is.numeric(out$relex$Age))
  expect_true(is.numeric(out$relex$RemLExp))
  expect_true(is.numeric(out$relex$Lower))
  expect_true(out$relex$Lower[1]<out$relex$RemLExp[1])
  expect_true(out$relex$RemLExp[1]<out$relex$Upper[1])
  expect_named(out$Sur5, c("Age", "Lower",  "Upper", "Sur"))
  expect_true(is.numeric(out$Sur5$Lower))
  expect_true(is.numeric(out$Sur5$Sur))
  expect_named(out$L90, c("L", "Lower",  "Upper"))
  expect_true(out$L90$L >5)
})
