# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand

data(weights)
data(core)


test_that("Gro_Main Captive works", {
  output= Gro_Main(data = weights, coresubse = core,
                   Taxa = "Reptilia", Species = "Testudo hermanni" ,
                   BirthType = c("Captive", "Wild"), 
                   AgeMat = 1, MeasureType = "Live weight",
                   type = "weight", 
                   MinNGro = 30, MinNIGro = 30, 
                   models = c("vonBertalanffy", "logistic"), percentiles = c(2.5,97.5)) 
  
  expect_named(output,c("Captive", "Wild"))
  expect_named(output$Captive,c("wSummar", "weightQ"))
  expect_named(output$Captive$wSummar,
               c("NInd_raw", "NWeight_raw", "NWeight_val", "NInd_val", 
                 "error", "Nerr", "AgeMat", "NJuv", 
                 "NJuv_keep", "NAd", "NAd_keep", "NWeight", "NInd", "analyzed"))
  expect_equal(output$Captive$wSummar$NWeight_raw, 2393)
  expect_equal(output$Captive$wSummar$Nerr, 6)
  expect_equal(output$Captive$wSummar$NWeight, 2307)
  expect_true(output$Captive$wSummar$analyzed)
  expect_match(output$Captive$wSummar$error,"Model did not fit")
  expect_equal(output$Wild$wSummar$NJuv, 183)
  expect_equal(output$Wild$wSummar$Nerr, 6)
  expect_equal(output$Wild$wSummar$NAd, 2205)
  expect_true(output$Wild$wSummar$analyzed)
  expect_match(output$Wild$wSummar$error,"Model did not fit")
  expect_named(output$Captive$weightQ, c("percent", "fit", "AIC_tab", "GOF"))
  expect_warning(Gro_Main(data = weights, coresubse = core,
                   Taxa = "Reptilia", Species = "Testudo hermanni" ,
                   BirthType = c("Captive", "Wild"), MeasureType = "b",
                   AgeMat = 1, 
                   type = "weight", 
                   MinNGro = 30, MinNIGro = 30, 
                   models = c("vonBertalanffy", "logistic"), percentiles = c(2.5,97.5)) )
})
