# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

test_that("Make_FigTab works", {
  file = system.file("sci_Animal.csv", package = 'ISRverse')
  AnalysisDir  = dirname(file)
  SaveDir = paste0(tempdir(check = TRUE),'/temp')
  dir.create(SaveDir)
  out <-Make_SurFigTab (AnalysisDir, SaveDir,
                        Sections = "sur")
  
  expect_true(file.exists(paste( SaveDir, 'Fig_Survival_1y1m.pdf', sep = '\\')))
  expect_named(out, c('Fig1', 'Fig2', 'Fig3', 'Fig4', 'error', 'corplot', 'Tabdata', 'Tabmetrics', 'cortab', 'Tabcheck'))
}
)
