# WARNING - Generated by {fusen} from dev/flat_select.Rmd: do not edit by hand

test_that("find_gaps works", {
  x = runif(10,0,40)
  out<-find_gaps(x,maxAlive = 5, plot = FALSE)
  expect_named(out,c('iniAge', 'finAge', 'Gap'))
  expect_equal(out$finAge-out$iniAge+1, out$Gap)
})
