# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

test_that("Sur_main works", {
  data(core)
  out <- Sur_main(core, BirthType = "Captive", 
                  models = "LO", shape = "bathtub",
                  niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
  expect_named(out, c("summary",  "bastaRes", "DICmods", "relex", 'Sur1', 'Sur5'))

})
