# WARNING - Generated by {fusen} from dev/flat_select.Rmd: do not edit by hand

test_that("select_Longthreshold works", {
  TempDir <- paste0(tempdir(check = TRUE),'\\temp')
  dir.create(TempDir)
  data(core) #### CHANGE DATASET WITH ONE EXCLUDING ABOVE95 99 99.9
  out <- select_Longthreshold (data.core = core,  sexCats = "All", 
                               PlotDir = TempDir, maintitle = 'Gorilla_gorilla')
  expect_true(file.exists(paste(TempDir, 'Gorilla_gorilla_LongThres.pdf', sep = '\\')))
  #remove temporary folder
  unlink(TempDir, recursive = TRUE)
  expect_named(out, c("summar",  "data"))
  expect_true("above95" %in% names(out$data))
  expect_named(out$summar, c("Sex", "Nglobal", "Nlifespan", "GapThresh", "NThres"))
  expect_true(out$summar$Sex == "All" )
  expect_equal(out$summar$Nglobal, nrow(core))
unlink(TempDir, recursive = TRUE)
})
