# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

test_that("Sur_main works", {
  data(core)
  data(deathinformation)
  out <- Sur_main(core, DeathInformation = deathinformation, Birth_Type = "Captive", 
                  models = "LO", shape = "bathtub",
                  niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
  expect_named(out, c("from0"))
  expect_named(out$from0, c("summary",  "bastaRes", "DICmods", "relex", 'Sur1', 'Sur5', 'L90', 'L50'))
  expect_named(out$from0$summary, c("NSelect", 'NUncertdeath', "NBasta", "Ndead", "maxAge", "maxAlive", "lxMin", "outLev", "analyzed", "Nerr", "error", "Gof_KM_coeff1", "Gof_KM_coeff2"))
  expect_named(out$from0$DICmods, c("models", "DIC"))
})
