# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand

data(weights)
data(core)

test_that("Gro_cleanmeasures works", {
  d=Gro_cleanmeasures(weights, core)
  expect_named(
    d$data,
    c("binSpecies", "SexType", "AnimalAnonID", "RecordingInstitution", "MeasurementType", "UnitOfMeasure", "MeasurementDate", "Age", "MeasurementValue"))
  expect_named(
    d$summar,
    c("NInd_raw", "NWeight_raw", "NWeight_val", "NInd_val", "error", "Nerr"))
  expect_true(unique(d$data$UnitOfMeasure) == "kg")
})
