# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

test_that("Load_Zimsdata works", {
  
  file = system.file("sci_Animal.csv", package = 'ISRverse')
  ZIMSdirtest = dirname(file)
  Split_Zimsdata	(ZIMSdir = ZIMSdirtest)
  
  data <- Load_Zimsdata	(taxa = "Reptilia", 
                         ZIMSdir = ZIMSdirtest, 
                         species = list(Reptilia = "All"),
                         Animal = TRUE,
                         tables = 'Weight') 
  
  expect_named(data$Reptilia, c("Animal",  "Weight"))
  expect_true(is.data.frame(data$Reptilia$Animal))
  expect_true(is.data.frame(data$Reptilia$Weight))
  expect_named(data$Reptilia$Weight, c("AnimalAnonID", "RecordingInstitution", "MeasurementType", "RecordType", "MeasurementValue", "EstimatedMeasurement", "ExcludededFromNorms", "MeasurementDate", "MeasurementDateEstimateType", "MeasurementDateEstimateStart", "MeasurementDateEstimateEnd", "CollectionScopeType",  "AnimalAgeMonths", "AnimalAgeDays", "Age", "UnitOfMeasure")) 
  
}
)
