# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

KM_tab = data.frame( Ages = 1:10,
                     ple = sort(runif(10, 0, 1), decreasing = TRUE))

test_that("KM_out works", {
  out <- KM_age(KM_tab, Lx = c(0.5,0.1))
  expect_named(out, c("Lx", "Age"))
  expect_true(is.numeric(out$Lx))
  expect_true(is.numeric(out$Age))
})
