# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand


test_that("run_txprofile works", {
  file = system.file("sci_Animal.csv", package = 'ISRverse')
  ZIMSdir = dirname(file)
  AnalysisDir = paste0(tempdir(check = TRUE),'\\temp')
  PlotDir = paste0(tempdir(check = TRUE),'\\temp\\plot')
  dir.create(AnalysisDir)
  dir.create(PlotDir)
  
  #This code run the survival analysis
  run_txprofile(taxa = "Reptilia", Species_list = "All",
                ZIMSdir = ZIMSdir, AnalysisDir = AnalysisDir,
                PlotDir = PlotDir,
                extractDate = "",
                minDate = "1980-01-01",
                Sections = "sur",
                sexCats = c('Male', 'Female'),
                niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3
  )
  
  expect_true(file.exists(paste(AnalysisDir, "Testudo_hermanni.Rdata", sep = '\\')))
  unlink(AnalysisDir, recursive = TRUE)
  unlink(PlotDir, recursive = TRUE)
  
})

