# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand

test_that("Rep_main works", {
  data(core)
  data(collection)
  data(parent)
  data(moves)
  out <- Rep_main (coresubset = core, collection, parent, moves,  
                   RepSect = c('agemat', 'litter'),
                   MinNRepro = 1, MinNPaRepro = 1,
                   BirthType_parent = "Captive", BirthType_offspring = "Captive", 
  ) 
  
  expect_named(out, c("summary", "agemat", "litter"))
  expect_named(out$summary, c("Nbirths", "Nadults", "NOffsp", "NParent", 
                              "NOffsp_age", "NParent_age", "analyzed",
                              "Nerr", "err", 'amat_analyzed', "litt_analyzed"))
  expect_true(is.numeric(as.numeric(out$summary[1:6])))
  expect_true(out$summary$analyzed)
  expect_false(out$summary$litt_analyzed)
  expect_true(out$summary$amat_analyzed)
})
