# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

test_that("run_txprofile works", {
  file = system.file("sci_Animal.csv", package = 'ISRverse')
  ZIMSDir = dirname(file)
  PlotDir = paste0(tempdir(check = TRUE),'/tem')
  PlotDir2 = paste0(PlotDir,'/Rdata')
  dir.create(PlotDir)
  dir.create(PlotDir2)
  
  #This code run the survival analysis
  run_txprofile(Taxa = "Reptilia", SpeciesList = "All",
                ZIMSDir = ZIMSDir, AnalysisDir = PlotDir,
                PlotDir = PlotDir, MeasureType="Live weight",
                ExtractDate = "",MinLx=0.4,
                MinDate = "1980-01-01",
                Sections = c("sur", "rep", "gro"),
                SexCats = c('Male', 'Female'),
                niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3
  )
  
  expect_true(file.exists(paste(PlotDir2, "Reptilia_Testudo_hermanni.Rdata", sep = '/')))
  unlink(PlotDir, recursive = TRUE)
})
