# WARNING - Generated by {fusen} from dev/flat_select.Rmd: do not edit by hand

test_that("select_Longthreshold works", {
  TempDir <- paste0(tempdir(check = TRUE),'\\temp')
  dir.create(TempDir)
  data(core) #### CHANGE DATASET WITH ONE EXCLUDING ABOVE95 99 99.9
  out <- select_Longthreshold (Data = core,  SexCats = "All", 
                               PlotDir = TempDir, PlotName = "Testudo_hermanni")
  expect_true(file.exists(paste(TempDir, 'Testudo_hermanni_LongThres.pdf', sep = '\\')))
  #reMove temporary folder
  unlink(TempDir, recursive = TRUE)
  expect_named(out, c("summar",  "data"))
  expect_true("above95" %in% names(out$data))
  expect_named(out$summar, c("Sex", 'Nselect', "Nlifespan", "GapThresh", "NThres"))
  expect_true(out$summar$Sex == "All" )
  expect_equal(out$summar$Nselect, nrow(core))
  unlink(TempDir, recursive = TRUE)
})
