# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

test_that("Split_Zimsdata works", {
  
  file = system.file("sci_Animal.csv", package = 'ISRverse')
  ZIMSDirtest = dirname(file)
  Split_Zimsdata	(ZIMSDir = ZIMSDirtest)
  expect_true(file.exists(glue::glue("{ZIMSDirtest}/Split_Reptilia/Reptilia_Animal.csv")))
  expect_true(file.exists(glue::glue("{ZIMSDirtest}/Split_Reptilia/Reptilia_AnimalParent.csv")))
  
})
