# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

test_that("surv_Bastab works", {
  data(core)
  data(deathinformation)
  out<- surv_Bastab(core, DeathInformation = deathinformation, earliestDate = '1990-01-01', latestDate = '2020-12-31', 
                    otherCovars = NA, excludeStillbirth = TRUE)
  expect_named(out, c("AnimalAnonID", "binSpecies", "Class", "Order", "Family", "CommonName", "Birth.Date", "Min.Birth.Date", "Max.Birth.Date", "Entry.Date", "Depart.Date", "Entry.Type", "Depart.Type", "RelevantDeathInformationType" ))
  expect_true(min(out$Entry.Date)>= lubridate::as_date('1990-01-01'))
  expect_true(max(out$Depart.Date)<=lubridate::as_date('2020-12-31'))
})
