# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand

test_that("Rep_prepdata works", {
  data(core)
  data(collection)
  data(parent)
  data(moves)
  
  Data <- Rep_prepdata (coresubset = core, collection, parent, moves,
                        BirthType_parent = "Captive", BirthType_offspring = "Captive"
  )
  expect_named(Data, c("Adults", "Reprodata", "summary"))
  expect_named(Data$summary, c("Nbirths", "Nadults", "NOffsp", "NParent", "NOffsp_age", "NParent_age"))
  expect_true(is.numeric(Data$summary%>%as.numeric()))
  expect_named(Data$Adults, c(names(core), "ageAds", "Age", "Date_age", "ScopeType"))
  expect_named(Data$Reprodata, c("AnonID", "ParentOriginType", 
                                 "ParentAnonID", "ParentType", "OffspringCollectionScopeType", 
                                 "ParentCollectionScopeType", "Parent_BirthDate", 
                                 "Parent_birthType", "Offspring_BirthDate", "Sex",
                                 "ageBirth", "currentInst", "Offspring_Inst", 
                                 "Probability"))
})
