# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand

z1 = c(rnorm(95,4,1), runif(5,100,1000))

test_that("Gro_Rout_quan error", {
  expect_error(Gro_Rout_quan("text"))
  expect_error(Gro_Rout_quan(z1, minq = 1) , regexp = "minq must be a proportion between 0 and 1")
})

test_that("Gro_Rout_quan works", {
  expect_true(sum(Gro_Rout_quan(z1, minq = 0.05)) == 95)
})
