# WARNING - Generated by {fusen} from dev/flat_select.Rmd: do not edit by hand

test_that("tx_report works", {
  file = system.file("sci_Animal.csv", package = 'ISRverse')
  ZIMSdirtest = dirname(file)
  data <- Load_Zimsdata	(taxa = "Reptilia",
                         species = list(Reptilia = "All"), ZIMSdir = ZIMSdirtest,
                         Animal = TRUE, tables = c("Collection","DeathInformation", "Weight"))
  Animal<- Prep_Animal(data[["Reptilia"]]$Animal, extractDate= "2024/08/29" )
  PlotDir = paste0(tempdir(check = TRUE),'\\temp')
  dir.create(PlotDir)
  
  out <- tx_report(species = "Testudo hermanni", taxa = "Reptilia",
                   Animal, data$Reptilia$Collection, MinBirthKnown = 0,minlx =0.5,minNIgro=40,
                   Birth_Type = "All", uncert_birth = 3500,uncert_death = 3500, 
                   DeathInformation =data$Reptilia$DeathInformation, weights =data$Reptilia$Weight,
                   niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3,
                   PlotDir = PlotDir, Sections = c('sur','gro'),
                   sexCats = c("Male", "Female"),
                   models_sur = "GO", shape = "simple",
                   models_gro = "vonBertalanffy"
  )
  expect_named(out, c('general', "summary", 'surv', 'weig'))
  expect_named(out$general, c('Nraw', 'Ndate', 'Nglobal', 'Nbirthtype', 'Nuncertbirth', 'Nalive', 'firstDate', 'maxAgeraw', 'extractdate'))
  expect_named(out$sur, c('Male', "Female"))
  expect_named(out$sur$Male, c("from0"))
  expect_named(out$sur$Male$from0, c("summary", "bastaRes", "DICmods", "relex", "Sur1", "Sur5", 'L90', 'L50'))
  expect_named(out$weig, c('Male', "Female"))
  expect_named(out$weig$Male$All, c('wSummar', "weightQ"))
  expect_named(out$weig$Female$All, c('wSummar', "weightQ"))
  expect_true(file.exists(paste(PlotDir, "Long_dist\\Reptilia_Testudo_hermanni_Male_LongThres.pdf", sep = '\\')))
  expect_true(file.exists(paste(PlotDir, "Survival\\10_Reptilia_Testudo_hermanni_Male_0_surcheck.pdf", sep = '\\')))
  expect_true(file.exists(paste(PlotDir, "Survival\\10_Reptilia_Testudo_hermanni_Male_0_surplot.pdf", sep = '\\')))
  expect_true(file.exists(paste(PlotDir, "Growth\\Reptilia_Testudo_hermanni_Male_All_outliers.png", sep = '\\')))
  expect_true(file.exists(paste(PlotDir, "Growth\\Reptilia_Testudo_hermanni_Male_All_growth.png", sep = '\\')))
  unlink(PlotDir, recursive = TRUE)
})
