# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand

#' my_fun Title
#'
#' @return 1
#' @export
#'
#' @examples
# Rep_fert <- function() {
#   fertSumm <- list(NOffsp_age = 0,  NParent_age = 0,
#                    NOffsp_bd = 0,NParent_bd = 0,
#                    NOffsp_glob = 0,NParent_glob = 0,
#                    NOffsp = 0, NParent = 0, 
#                    NAdult = 0, NAdult_rep = 0, 
#                    analyzed = FALSE, 
#                    Nerr= 0, error = "",
#                    Prepmean = NULL , Fertmean = NULL) 
#   
#   
#   
#   
#   
#   
#   # Store summary:
#   fertSumm$analyzed = TRUE
#   
#   # Reproduction matrix:
#   ageFert <- matrix(0, length(ageVec), 15, 
#                     dimnames = list(NULL, c("Age", "NReprAdult", "NtotParent", 
#                                             "Prep", "SEprep","Plower","Pupper",
#                                             "Fert", "SEfert","Fertlower","Fertupper",
#                                             "SexRatio", "SEsexratio","SRlower","SRupper")))
#   ageFert[, "Age"] <- ageVec
#   Nadstot= Npartot = 0
#   for (ix in 1:length(ageVec)) {
#     xx <- ageVec[ix]
#     Nads <- nrow(ADULTS%>%
#                    filter(Age == xx,
#                           contra == FALSE))
#     
#     subage<- subparfert%>% filter(ageBirthDisc == xx)
#     Npar = length(unique(subage$ParentAnonID))
#     Npartot = Npartot+Npar
#     if (Nads > 0 & Npar >0) {
#       tot <- subage %>% group_by(ParentAnonID)%>% 
#         summarize (rep = max(Probability)/100)
#       prepr <- sum(tot$rep) / Nads
#       Nadstot= Nadstot+Nads
#       fertRate <- sum(subage$Probability)/100 / Npar
#       temp = subage%>% group_by(ParentAnonID)%>%summarize(A = sum(Probability)/100, N = n()^2)
#       Vfert = sum(temp$A*temp$N) / Npar - fertRate^2
#       sr <- length(which(subage$SexType == "Female"))/ length(which(subage$SexType  %in% c("Female", "Male")))
#       if (fertRate > 1) {
#         if(Vfert>0){
#           fertSE <-sqrt(Vfert / Npar)
#         }else{ fertSE <- 0}
#       } else {
#         fertSE <- sqrt(fertRate * (1 - fertRate) / 
#                          Npar)
#       }
#       pSE <-  sqrt(prepr * (1 - prepr) / 
#                      Nads)
#       if(prepr> 1 | prepr<0){stop(glue("p(repro) = {pSE} for age {xx} and sex {sx}.As a probability, it should be include between 0 and 1"))}
#       srSE <-  sqrt( sr * (1 -  sr) / 
#                        length(which(subage$SexType  %in% c("Female", "Male"))))
#       
#       
#     } else {
#       fertRate <- prepr <- sr <- 0
#       pSE <- fertSE <- srSE <- 0
#     }
#     fertlower = fertRate - 1.96*fertSE
#     fertupper = fertRate + 1.96*fertSE
#     plower = prepr -1.96 *  pSE
#     pupper = prepr +1.96 *  pSE
#     srlower = sr -1.96 *  srSE
#     srupper = sr +1.96 *  srSE
#     
#     srlower = ifelse(srlower<0,0,srlower)
#     plower = ifelse(plower<0,0,plower)
#     fertlower = ifelse(fertlower<0,0,fertlower)
#     srupper = ifelse(srupper>1,1,srupper)
#     pupper = ifelse(pupper>1,1,pupper)
#     ageFert[ix, -1] <- c(Nads, Npar, 
#                          prepr, pSE,plower,pupper,
#                          fertRate, fertSE,fertlower,fertupper, 
#                          sr, srSE,srlower,srupper)
#   }
#   tot <- subparfert %>% group_by(ParentAnonID,ageBirthDisc)%>% 
#     summarize ( rep = max(Probability)/100)
#   fertSumm$Prepmean =sum(tot$rep) / Nadstot
#   fertSumm$Fertmean = sum(subpar$Probability)/ Npartot /100
#   
#   
#   
# }
