# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand

#' Prepare weight and length Dataset
#'
#'Select clean measures, unify the unity used and add individual age at each measure
#'
#' @param data \code{data.frame} including the following columns *MeasurementValue*, *MeasurementDate*, *CollectionScopeType*, *UnitOfMeasure*, *ExcludedFromNorms*, *EstimatedMeasurement*, *RecordType*, *MeasurementType*, *anonID* and *AnonInstitutionID*.
#' @param coresubse \code{data.frame} including at least the following columns *binSpecies*, *Sex*, *anonID* and *Birthdate* (\code{date})
#' @param CaptiveBirths \code{logical} Should captive born individuals be included, only? Default =  TRUE
#' @param InclUnkSex \code{logical} Should undetermined sexes be included Default =  FALSE
#' @param mindate \code{character 'YYYY-MM-DD'} Earlier date to include data
#' @param MeasureType \code{vector of characters} Name of the type of measurements that should be included. Default = NULL, all measurement type are included.
#' @param type \code{character} Either 'weight' or 'length'. Default =  'weight
#' @param corevariable \code{vector character} Name of the core columns that must be added to data
#' @param variablekeep \code{vector character} Name of the data columns that must also be returned
#' 
#' @return The data frame including selected measures, plus individual birth date and individual age at each measure
#' 
#' @import dplyr assertthat
#' 
#' @export
#'
#' @examples
#' data(raw_weights)
#' data(core)
#'
#' data_weights= Gro_cleanmeasures(raw_weights, core,
#'                                 CaptiveBirths = TRUE,
#'                                 MeasureType = 'Live weight',
#'                                 InclUnkSex = FALSE, 
#'                                 mindate = "1980-01-01")
Gro_cleanmeasures <- function(data, coresubse,
                              CaptiveBirths = TRUE, type = "weight", MeasureType = NULL,
                              InclUnkSex = FALSE, mindate = "1980-01-01",
                              corevariable = '', variablekeep ='') 
{
  mindate = lubridate::as_date(mindate)
  assert_that(is.data.frame(data))
  assert_that(is.data.frame(coresubse))
  assert_that(data %has_name% c("MeasurementValue", "MeasurementValue", "MeasurementDate", "CollectionScopeType", "UnitOfMeasure", "ExcludedFromNorms", "EstimatedMeasurement", "RecordType", "MeasurementType", "anonID", "AnonInstitutionID"))
  assert_that(coresubse %has_name% c("BirthDate", "binSpecies", "Sex", "anonID"))
  assert_that(is.logical(CaptiveBirths))
  assert_that(is.logical(InclUnkSex))
  assert_that(is.date(mindate))
  assert_that(is.character(corevariable))
  assert_that(is.character(variablekeep))
  if(corevariable != '') {assert_that(coresubse %has_name% corevariable)}
  if(variablekeep != '') {assert_that(data %has_name% variablekeep)}
  
  if(!is.null(MeasureType)){
    if(!all(MeasureType %in% unique(data$MeasurementType))){
      MeasureType_not = which(!(MeasureType %in% unique(data$MeasurementType)))
      warnings(paste0(MeasureType[MeasureType_not]," are not included in the data, check if they are spelled correctly"))
    }
  }
  assertthat::assert_that(type %in% c("weight",'length'))
  
  if(type =="weight"){
    Units <- data.frame(unit = c("kilogram", "gram", 
                                 "micrograms", "milligram", "ounce", 
                                 "pound", "stone", "tonne"), 
                        toKg = c(1,1/1000, 
                                 10^{
                                   -9
                                 }, 10^{
                                   -6
                                 }, 0.0283495, 0.453592, 6.35029, 1000),
                        stringsAsFactors = FALSE)
    
  }
  if(type =="length"){
    Units <- data.frame(unit = c("meter","m", "dm", "cm", "mm", 
                                 "foot", "inch", 
                                 "metre", "centimetre", "millimetre",  "kilometre"), 
                        toKg = c(1,1, 10^{-1}, 10^{-2},10^{-3},
                                 0.3048, 0.0254,
                                 1, 10^{-2},10^{-3},10^{3}),
                        stringsAsFactors = FALSE)
    
  }
  Corevariable = c("binSpecies", "BirthDate", "Sex", "anonID") 
  Variablekeep = c(Corevariable,"AnonInstitutionID","MeasurementType", 
                        "MeasurementDate", "age", "Measure", "Unit")
  if(corevariable != '') Corevariable = c(Corevariable, corevariable)
  if(variablekeep != '')  Variablekeep = c(Variablekeep, variablekeep)
 
    
  coresubse<- coresubse%>%
    rowwise()%>%
    mutate(cond_captivebirth = ifelse(CaptiveBirths,stringr::str_detect(birthType, pattern = "Captive"),1 ),
           cond_sex = ifelse(InclUnkSex, 1, stringr::str_detect(Sex, pattern = "Undet", negate = T) ))%>%
    filter(cond_captivebirth == 1,
           cond_sex == 1)%>%
    dplyr::select(-c(cond_captivebirth, cond_sex))
  
  data <- data%>%
    filter(anonID %in% coresubse$anonID)%>%
    mutate(MeasurementDate = lubridate::as_date(MeasurementDate))%>%
    left_join(coresubse%>%dplyr::select(all_of(Corevariable)), by = "anonID")
  
  if(!is.null(MeasureType)){
    data<- data%>%
      filter(MeasurementType %in% MeasureType)}
  
  if(nrow(data)>0){
    
    datasub<- data%>%
      filter(Sex %in% unique(coresubse$Sex),
             MeasurementDate>= mindate,
             CollectionScopeType == "Global",
             !is.na(MeasurementValue),
             as.character(UnitOfMeasure) %in% Units$unit,
             ExcludedFromNorms == 0 , 
             EstimatedMeasurement == 0 , 
             MeasurementValue > 0,
             RecordType == "Husbandry"
      )
    
    
    
    if (nrow(datasub) > 0) {
      datasub <- datasub%>%
        mutate(age = as.numeric((MeasurementDate - BirthDate)/365.25))%>%
        filter(age >= 0)%>%
        left_join(Units, by =c("UnitOfMeasure"= "unit"))%>%
        mutate(Measure = MeasurementValue * toKg,
               Unit = Units$unit[1])%>%
        dplyr::select(all_of(Variablekeep))
      output <-datasub
    }else{output <- "There is no data selected"}
    
  }else{output <- "There is no data selected"}
  return(output)
}
