# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand


#' Flag outliers in individual trajectories
#' 
#' This function flag 
#' 
#' @param data_weight \code{data.frame} including at least the following columns : *MeasurementValue* (\code{numeric}), *Age*  (\code{numeric})
#' @param variable_id \code{character} name of the variable including individual ids. Defaut = "AnonID". It must also be a column of data_weight
#' @param perc_weight_min  \code{numeric} Minimum percentage of weight that an individual can naturally lose or gain during a year. Default =  0.2 (20%)
#' @param perc_weight_max  \code{numeric} Maximum percentage of weight that an individual can naturally lose or gain during a year. Default =  2.5 (250%). This value is used only after 1 year old 
#' @param IQR \code{numeric} influences the sensitivity of the function to remove outliers. It should be above 1 Default =  1.5. A higher number makes the function less sensitive to find outliers.
#' @param remove_ext \code{logical} Do you want to keep the two first and two last observations of individual trajectories? These points may often be highlighted as false outliers. Default =  TRUE
#' @param traj_ind \code{logical} Do you want to build linear model at the level of the individual trajectory  Default =  TRUE. If yes, each individual trajectory must have at least 5 measures. 
#' 
#' @details
#' The function uses a log-linear model of the measurement value in relation to a quadratic effect of age for each individual trajectories. It flags as outliers all measures for which the residuals from the linear model are above  IQR * the inter quantile interval (quantile(0.9) - quantile(0.1)) of the residuals. \code{perc_weight_min} and \code{perc_weight_max} limit the values that must be considered as outliers.
#'The \code{remove_ext} argument prevents the function from removing the 2 last and 2 first value observations in relation to age as these values may often be farther from the prediction line.
#' 
#' @import dplyr assertthat
#' @importFrom stats quantile
#'
#' @return data frame; the data set including an additional column *Keep2* of 0 (potential outliers) and 1
#' 
#' @export
#' @examples
#' data(weights)
#'
#' #We use only trajectories for which the number of individual datapoints is > 6
#' weights <- weights%>%
#'   dplyr::group_by(AnonID)%>%
#'   dplyr::mutate(nb= dplyr::n())%>%
#'   dplyr::ungroup()%>%
#'   dplyr::filter(nb >6)
#'
#' weights <- weights%>%Gro_lin_ind(traj_ind = TRUE)
#' as.numeric(weights$Keep2)
#'
#' weights_pop <- weights%>%Gro_lin_ind(traj_ind = FALSE)
Gro_lin_ind <- function(data_weight, 
                        variable_id = "AnonID",
                        perc_weight_min = 0.2,
                        perc_weight_max = 2.5,
                        IQR = 1.5,
                        remove_ext = T,
                        traj_ind = T
) {
  
  assert_that(is.numeric(perc_weight_min ))
  assert_that(perc_weight_min  >0 )
  assert_that(perc_weight_min  <1)
  assert_that(is.numeric(perc_weight_max ))
  assert_that(perc_weight_max  >1 )
  assert_that(is.numeric(IQR))
  assert_that(IQR  > 1, msg = 'IQR should be higher than 1 to avoid removing real data')
  assert_that(is.logical(remove_ext))
  assert_that(is.logical(traj_ind))
  assert_that(data_weight %has_name% c("MeasurementValue","Age"))
  
  
  data_weight<-data_weight%>%
    dplyr::mutate(pop = 1)%>%
    dplyr::group_by(pop)
  
  assert_that(nrow(data_weight)  > 4, msg = 'There should be at least 5 measures')
  assert_that(min(length(unique(data_weight$Age)))  >= 4, msg = 'Measures must have been taken at 4 different unique ages, at least')
  
  
  #only for individual trajectory 
  if(traj_ind==T){
    assert_that(is.character(variable_id))
    assert_that(data_weight %has_name% c(variable_id))
    
    data_weight<-data_weight%>%
      mutate(anonid = {{variable_id}})%>%
      group_by(anonid)
    
    da_weight<-data_weight%>%
      summarize(nb= n(),
                la = length(unique(Age)))
    assert_that(min(da_weight$nb)  > 4, msg = 'Each individual trajectory must have at least 5 measures')
    assert_that(min(da_weight$la)  >= 4, msg = 'Each individual trajectory must have measures at 4 different unique ages, at least')
  }
  data_weight$pred2 = perc_weight_max
  data_weight$pred2[data_weight$Age<1] = 1000
  data_weight<-data_weight%>%
    mutate(pred = stats::predict(mgcv::gam(MeasurementValue ~ s(Age, bs = "cr", k=3), data = cur_group())),
           res = abs(MeasurementValue - pred),
           pred1 = abs(perc_weight_min*pred),
           pred2 = abs(pred*pred2),
           lwr = abs(IQR*(quantile(res,0.90)-quantile(res,0.10))),
           ager = rank(Age),
           #Prevent from removing 2 first and 2lasts obs as they will tend to be removed
           age0 = ager < min(ager)+2,
           agem = ager > max(ager)-2)%>%
    dplyr::ungroup()%>% 
    rowwise%>%
    mutate(
      Keep2 = res < min(max(lwr,pred1),pred2))
  if( !(remove_ext))   data_weight$Keep2[data_weight$age0 | data_weight$agem]=1
  data_weight<-data_weight%>%
    dplyr::select(- pred1, -lwr, -res, -age0, -agem, -pred, -ager,
                  -pop, -pred2)
  
  if(traj_ind==T){
    data_weight<-data_weight%>%dplyr::select(-anonid)
  } 
  return(data_weight)
}
