# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand


#' Remove outliers from weigth or length data
#'
#'Takes a data frame including weight measures and Age and look for possible outliers
#'
#' @param data_weight \code{data.frame} including at least the following columns : *MeasurementValue* (\code{numeric}), *Age*  (\code{numeric})
#' @param taxa  \code{character} the name of the taxa studied
#' @param ageMat \code{numeric} the age at sexual maturity to differentiate juveniles (still growing) from adults
#' @param maxweight \code{numeric} the maximum weight allowed for the dataset
#' @param variableid \code{character} name of the variable including individual ids. Defaut = "anonID". It must also be a column of data_weight.Default = 6. It must be at least 5
#' @param min_Nmeasures \code{integer} Minimum number of measures for an individual to check outliers along its growth trajectory. Default = 7. It must be at least 5
#' @param minq \code{numeric} Sensitivity of the function to remove outliers using percentiles, between 0 and 1. Default =  0.025
#' @param IQR \code{numeric} influences the sensitivity of the function to remove outliers using log-linear model of growth. It should be above 1 Default =  2.75. A higher number makes the function less sensitive to find outliers.
#' @param perc_weight_min  \code{numeric} Minimum percentage of weight that an individual can naturally lose or gain during a year . Default =  0.2 (20%)
#' @param perc_weight_max  \code{numeric} Maximum percentage of weight that an individual can naturally lose or gain during a year . Default =  2.5 (250%)
#' @param Ninterval_juv \code{integer} Number of intervals used for the sliding windows for juveniles. Default = 10
#' 
#' @return The data frame including the additional column `KEEP` a numeric vector of 1 and 0 indicating the measures to keep. The 0 signal outliers. Other additional columns keep1, keep2, keep3 indicates the individuals highlighted as outliers (0) in steps 1 to 3 and the column juv indicates which individuals have been classified as juveniles.
#' 
#' @details
#'This function follow 4 different steps to highlight outliers:
#'1/ It removes the measures higher than \code{maxweight} (Instead of using the OrdMag Fernando that was removing only very extreme values, a maximum value was set for each taxa).
#'2/ Independently on adults and juveniles, it uses the function Gro_Rout_quan() to removes outliers based on percentiles on adults and juveniles. It uses sliding windows of age for juveniles.
#'3/  Independently on adults and juveniles, it uses the function Gro_lin_ind() to build generalized additive models for each individual trajectories with at least 7 measures and remove outliers based on the residuals of the models.
#'4/  It uses the function Gro_lin_ind() to build a common generalized additive model for all growth trajectories and remove outliers based on the residuals of the models.
#' 
#' @import dplyr assertthat
#' @importFrom stats lm predict.lm
#' 
#' @export
#'
#' @examples
#' data(weights)
#' weights = Gro_remoutliers(weights, taxa = "Mammalia", ageMat = 10)
Gro_remoutliers <- function(data_weight, taxa, ageMat = NULL, maxweight = NULL, 
                            variableid = "anonID", min_Nmeasures = 7,
                            perc_weight_min=0.2, perc_weight_max=2.5,
                            IQR=2.75, minq=0.025, Ninterval_juv = 10) {
  
  assert_that(is.data.frame(data_weight))
  assert_that(data_weight %has_name% c("MeasurementValue", "Age"))
  assert_that(taxa %in% c("Mammalia", "Aves", "Reptilia", "Amphibia", 
                          "Chondrichthyes", "Actinopterygii"),
              msg = "taxa must one of 'Mammalia', 'Aves', 'Reptilia', 'Amphibia', 
                          'Chondrichthyes', or 'Actinopterygii'")
  if(is.null(maxweight)){
    if(taxa == "Mammalia")       maxweight = 7000
    if(taxa == "Aves")           maxweight = 200
    if(taxa == "Reptilia")       maxweight = 1500
    if(taxa == "Amphibia")       maxweight = 100
    if(taxa == "Chondrichthyes") maxweight = 1000
    if(taxa == "Actinopterygii") maxweight = 500
  }
  assert_that(is.numeric(maxweight))
  assert_that(min_Nmeasures%%1==0, msg = "min_Nmeasures should be an integer")
  assert_that(min_Nmeasures>=5)
  assert_that(Ninterval_juv%%1==0, msg = "Ninterval_juv should be an integer")
  assert_that(all(data_weight$MeasurementValue>0))
  assert_that(all(data_weight$Age>=0))
  
  if(variableid != "anonID"){
    data_weight <- data_weight%>%
      rename(anonID = !!sym(variableid))
  }
  
  if(is.null(ageMat)){ageMat=1.5}
  assert_that(is.numeric(ageMat))
  
  #1) Removes very large weights using maxweight ----
  data_weight <- data_weight%>%
    mutate(keep1 = ifelse(MeasurementValue< maxweight, 1, 0))
  
  #2) Separate Juveniles and adults 
  ### JUVENILES ----
  juv <- data_weight%>%
    mutate(juv = 1)%>%
    filter(Age >= 0, Age < ageMat*1.2)
  if (nrow(juv) > 0) {
    
    ##a/Uses sliding windows to check outliers based on percentile of the distribution 
    #Make Ninterval_juv for sliding windows
    nInts = Ninterval_juv
    windInts <- seq(0, ageMat, length = nInts+1)
    numInt <- table(findInterval(juv$Age[juv$keep1==1], windInts))
    nWindInts <- 0
    ii <- 1
    while (ii < nInts) {
      cumInt <- cumsum(numInt[ii:nInts])
      idnum <- which(cumInt > 30) + ii
      if (length(idnum) > 0) {
        nWindInts <- c(nWindInts, windInts[idnum[1]])
        ii <- idnum[1]
      } else {
        nWindInts <- c(nWindInts, windInts[nInts+1])
        ii <- nInts
      }
    }
    if (!ageMat %in% nWindInts)  nWindInts <- c(nWindInts, ageMat)
    nInts <- length(nWindInts) - 1
    juv$keep2 = juv$keep1
    for (iints in 1:nInts) {
      idwind <- which(juv$Age >= nWindInts[iints] & 
                        juv$Age <= nWindInts[iints + 1] & 
                        juv$keep1 == 1)
      juv$keep2[idwind] = Gro_Rout_quan(z = juv$MeasurementValue[idwind], x =  juv$Age[idwind],
                                        minq = minq, type = "both")
    }
    
    
    ##b/Uses individual trajectories to find outliers for juveniles with at least 7 measures
    juv <-juv %>%
      group_by(anonID,keep2)%>%
      mutate(nb =  sum(keep2),
             la = length(unique(Age)))%>%
      dplyr::ungroup()
    juv$keep3 = juv$keep2
    if(any(juv$nb >= min_Nmeasures & juv$la>=4)){
      juv_temp  <- Gro_lin_ind(juv%>%filter(keep2 == 1, nb >= min_Nmeasures, la >= 4), 
                               perc_weight_min = perc_weight_min,
                               perc_weight_max = perc_weight_max,
                               IQR = IQR,
                               remove_ext = F, traj_ind = T
      )
      
      juv$keep3[juv$keep2==1 & juv$nb >= min_Nmeasures & juv$la >=4] = juv_temp$Keep2 
    }
  }
  
  ### ADULTS ----
  ad <- data_weight%>%
    mutate(juv = 0)%>%
    filter(Age >=  ageMat*1.2)
  if (nrow(ad) > 0) {
    
    ##a/Check outliers based on percentile of the distribution 
    ad$keep2=ad$keep1
    ad$keep2[ad$keep1 == 1] = Gro_Rout_quan(z = ad$MeasurementValue[ad$keep1 == 1], x =  ad$Age[ad$keep1 == 1],  
                                            minq = minq, type = "both")
    
    ##b/Uses individual trajectories to find outliers for adults with at least 7 measures
    ad <-ad %>%
      group_by(anonID,keep2)%>%
      mutate(nb =  sum(keep2),
             la = length(unique(Age)))%>%
      dplyr::ungroup()
    ad$keep3 = ad$keep2
    if(any(ad$nb >= min_Nmeasures & ad$la>=4)){
      
      ad_temp <- Gro_lin_ind(ad%>%filter(keep2==1, nb >= min_Nmeasures, la >= 4), 
                             perc_weight_min = perc_weight_min,
                             perc_weight_max = perc_weight_max,
                             IQR = IQR,
                             remove_ext = F, traj_ind = T
      )
      ad$keep3[ad$keep2==1 & ad$nb >= min_Nmeasures & ad$la >=4] = ad_temp$Keep2 
    }
  }
  
  data_weight1 =rbind(juv,ad)%>%dplyr::select(-nb,-la)
  #3) Uses global GAM model to detect remaining outliers ----
  data_weight1$KEEP= data_weight1$keep3
  if(sum(data_weight1$KEEP)>4){
    if(length(unique(data_weight1$Age[data_weight1$KEEP==1]))>=4){
      data_weight1_temp <- Gro_lin_ind(data_weight1%>%filter(keep3==1), 
                                       perc_weight_min = perc_weight_min,
                                       perc_weight_max = perc_weight_max,
                                       IQR = IQR,
                                       remove_ext = F, traj_ind = F
      )
      data_weight1$KEEP [data_weight1$keep3 == 1] = data_weight1_temp$Keep2
    }
  }
  return(data_weight1)
  
}
