# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand

#' Prepare weight and length Dataset
#'
#'Select clean measures, unify the unity used and add individual age at each measure
#'
#' @param data \code{data.frame} including the following columns *MeasurementValue*, *MeasurementDate*, *MeasurementDateStart*, *MeasurementDateEnd*, *UnitOfMeasure*, *EstimatedMeasurement*, *RecordType*, *MeasurementType*, *AnimalAnonID*, *RecordingInstitution*, and *Age*.
#' @param coresubse \code{data.frame} including at least the following columns *binSpecies*, *SexType*, *AnimalAnonID* and *BirthType*
#' @param Birth_Type \code{character} Captive, Wild, or All Default =  TRUE
#' @param mindate \code{character 'YYYY-MM-DD'} Earlier date to include data
#' @param uncert_date \code{numeric}: Maximum uncertainty accepted for measurement dates, in days
#' @param MeasureType \code{vector of characters} Name of the type of measurements that should be included. Default = NULL, all measurement type are included.
#' @param type \code{character} Either 'weight' or 'length'. Default =  'weight
#' @param corevariable \code{vector character} Name of the core columns that must be added to data
#' @param variablekeep \code{vector character} Name of the data columns that must also be returned
#' 
#' @return A list including
#' * The data frame including selected measures, plus individual birth date and individual age at each measure
#' * A summary with the number of individuals and weight:
#'         - NInd_raw  and, NWeight_raw indicate the number of unique individuals and the number of weights once the sex, the birth type, the measurment type from global collection have been selected
#'           - NWeight_val and NInd_val indicate the number of unique individuals and the number of weights once valid measurment from Husbandry have been selected
#'          -  If no data are selected, an error and its number (Nerr) are returned: The possibility for this functions are: 1/No raw data and 2/No valid weight measure.
#' 
#' @import dplyr assertthat
#' 
#' @export
#'
#' @examples
#' data(weights)
#' data(core)
#' data_weights= Gro_cleanmeasures(weights, core,
#'                                 Birth_Type = "All",
#'                                 MeasureType = 'Live weight',
#'                                 mindate = "1980-01-01")
Gro_cleanmeasures <- function(data, coresubse,
                              Birth_Type = "All", type = "weight", MeasureType = NULL,
                               mindate = "1980-01-01", uncert_date = 365,
                              corevariable = NULL, variablekeep =NULL) 
{
  mindate = lubridate::as_date(mindate)
  assert_that(is.data.frame(data))
  assert_that(is.data.frame(coresubse))
  assert_that(data %has_name% c("MeasurementValue", "MeasurementDate","MeasurementDateEstimateStart","MeasurementDateEstimateEnd", "UnitOfMeasure", "EstimatedMeasurement", "RecordType", "MeasurementType", "AnimalAnonID", "RecordingInstitution", "Age"))
  assert_that(coresubse %has_name% c("binSpecies", "SexType", "AnimalAnonID", "BirthType"))
   assert_that(is.character(Birth_Type))
  assert_that(Birth_Type %in% c("Captive", "Wild", "All"))
  assert_that(is.date(mindate))
  assert_that(is.numeric(uncert_date))
  
  
  if(!is.null(corevariable)) {
    assert_that(is.character(corevariable))
    assert_that(coresubse %has_name% corevariable)}
  if(!is.null(variablekeep)) {
    assert_that(is.character(variablekeep))
    assert_that(data %has_name% variablekeep)}
  
  if(!is.null(MeasureType)){
    if(!all(MeasureType %in% unique(data$MeasurementType))){
      MeasureType_not = which(!(MeasureType %in% unique(data$MeasurementType)))
      warnings(paste0(MeasureType[MeasureType_not]," are not included in the data, check if they are spelled correctly"))
    }
  }
  assertthat::assert_that(type %in% c("weight",'length'))
  summar <- list(NInd_raw = 0, NWeight_raw = 0, 
                 NWeight_val = 0, NInd_val =0, 
                 error = "", Nerr = 0)
  

  Corevariable = c("binSpecies", "SexType", "AnimalAnonID", corevariable) 
  Variablekeep = c(Corevariable,"RecordingInstitution","MeasurementType", "UnitOfMeasure",
                   "MeasurementDate", "Age", "MeasurementValue",  variablekeep)
  
  
  
  if (Birth_Type != "All"){
    coresubse<- coresubse%>%
      filter(stringr::str_detect(BirthType, pattern = Birth_Type))
  }

  
  data <- data%>%
    filter(AnimalAnonID %in% coresubse$AnimalAnonID)%>%
    mutate(MeasurementDate = lubridate::as_date(MeasurementDate),
           MeasurementDateEstimateStart = lubridate::as_date(MeasurementDateEstimateStart),
           MeasurementDateEstimateEnd = lubridate::as_date(MeasurementDateEstimateEnd),
           Date_Uncert = MeasurementDateEstimateEnd - MeasurementDateEstimateStart)%>%
    filter((Date_Uncert <= uncert_date)%>% replace_na(TRUE))%>%
    left_join(coresubse%>%dplyr::select(all_of(Corevariable)), by = "AnimalAnonID")
  
  
  if(nrow(data)>0){
    if(!is.null(MeasureType)){
      data<- data%>%
        filter(MeasurementType %in% MeasureType)
      }
    summar$NInd_raw = length(unique(data$AnimalAnonID))
    summar$NWeight_raw = nrow(data)
  }else{
    warnings('no common ID between measured data and core data')
  }
  
  if(nrow(data)>0){
    data<- data%>%
      filter(MeasurementDate>= mindate,
             !is.na(MeasurementValue),
             !is.na(Age),
             EstimatedMeasurement == 0 , 
             MeasurementValue > 0,
             RecordType == "",
             Age >= 0
      )%>%
      dplyr::select(all_of(Variablekeep))
    summar$NInd_val = length(unique(data$AnimalAnonID))
    summar$NWeight_val = nrow(data)
  }else{
    summar$error = "No valid weight measure"
    summar$Nerr = 1
    data <- data.frame()}

  return(list(data = data, summar = summar))
}
