# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand


#' Flag outliers in individual trajectories
#' 
#' This function flag 
#' 
#' @param data_weight \code{data.frame} including at least the following columns : *MeasurementValue* (\code{numeric}), *Age*  (\code{numeric})
#' @param variable_id \code{character} name of the variable including individual ids. Defaut = "anonID". It must also be a column of data_weight

#' 
#' @details
#' 
#' @import dplyr assertthat
#' @importFrom stats quantile
#'
#' @return data frame; the data set including an additional column *Keep2* of 0 (potential outliers) and 1
#' 
#' @export
#' @examples
#' data(weights)
#'
Gro_analysis <- function(data_weight, 
                         variable_id = "anonID"
                         
) {
  
  assert_that(is.numeric(perc_weight_min ))
  assert_that(perc_weight_min  >0 )
  assert_that(perc_weight_min  <1)
  assert_that(is.numeric(perc_weight_max ))
  assert_that(perc_weight_max  >1 )
  assert_that(is.numeric(IQR))
  assert_that(IQR  > 1, msg = 'IQR should be higher than 1 to avoid removing real data')
  assert_that(is.logical(remove_ext))
  assert_that(is.logical(traj_ind))
  assert_that(data_weight %has_name% c("MeasurementValue","Age"))
  
  
  return(data_weight)
}


