# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand


#' Fit growth model
#' 
#' Fit a growth model to data, return its fit and AIC
#' 
#' @param num \code{numeric} index of the model to run 
#' @param data \code{data.frame} including at least the numeric columns *logx* and *logz* 
#' @param all_mods \code{vector of character} indicating growth models.The following models are supported : logistic, gompertz, chapmanRichards, vonBertalanffy, polynomial
#' 
#' @import dplyr assertthat
#' @importFrom bbmle mle2 logLik
#'
#' @return The fit and AIC of the model
#' 
#' @export
#' @examples
#' logx <- rnorm(100, 0, 1)
#' logz <- 0.2+ 15 * (1 - exp(-(1) * logx)) +rnorm(100, 0, 0.01)
#' dat = data.frame(logx = logx, logz = logz)
#' Gro_fitlog(num = 1, data = dat, all_mods = "vonBertalanffy")
Gro_fitlog <- function(num = 1, data, all_mods = "vonBertalanffy") {
  assert_that(all(all_mods %in% c("logistic", "gompertz", "chapmanRichards", "vonBertalanffy", "polynomial")), msg = "The growth models supported are: logistic, gompertz, chapmanRichards, vonBertalanffy , and polynomial")
  assert_that(is.data.frame(data))
  assert_that(data %has_name% c('logx', 'logz'))
  assert_that(is.numeric(data$logx))
  assert_that(is.numeric(data$logz))
  assert_that(is.numeric(num))
  assert_that(num <= length(all_mods))
  
  model = all_mods[num]
  modSett <- Gro_ModSettings(data, model)
  out = list()
  suppressWarnings(out$fit <- bbmle::mle2(modSett$growthMod, 
                                          data = data, 
                                          parnames = modSett$namesCoef, 
                                          fixed = list(LL = T),
                                          start = modSett$gamstart
                                          # lower = modSett$low
  ))
  out$tab = list(index = num,
                 model = all_mods[num],
                 k =modSett$np, 
                 AIC= bbmle::AIC(out$fit)) #voir le nombre de decimal
  out$growthMod = modSett$growthMod
  return(out)
}
