# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Load Zims data
#' 
#' Check if selected data are already in the global environment. If not, it load them.
#'
#' @param taxa  \code{character} the name of the taxa studied
#' @param ZIMSdir \code{character} directory where to find data
#' @param species  \code{list of character} names of the species studied. A list per taxa name should be used, or Default = "All"
#' @param Animal \code{logical} Whether the core animal data should be loaded Default = TRUE
#' @param tables \code{vector character} the type of data to load. 
#' @param silent \code{logical} Whether information of advancement should be printed
#' 
#' @details
#' \code{type} can take the following values : "Contraception", "HealthStatus", "DeathInformation","Institution","InstitutionAssociation", "Move","Parent", "Weight", "Length","DeathInformation", "Collection"
#'
#' @return A list of the data frames
#' @importFrom glue glue
#' @importFrom utils read.csv
#' @importFrom checkmate assert_directory_exists
#' @export
#'
#' @examples
#' file = system.file("sci_Animal.csv", package = 'ISRverse')
#' ZIMSdirtest = dirname(file)
#' Split_Zimsdata	(ZIMSdir = ZIMSdirtest)
#'
#' data <- Load_Zimsdata	(taxa = "Reptilia", 
#'                        ZIMSdir = ZIMSdirtest, 
#'                        species = list(Reptilia = "All"),
#'                        Animal = TRUE,
#'                        tables = 'Weight') 
#' data$Reptilia$Animal
#' unlink(glue::glue("{ZIMSdirtest}/Split_Reptilia"), recursive = FALSE)
Load_Zimsdata	<- function (taxa, ZIMSdir,
                           species ,
                           Animal = FALSE,
                           tables = c(),
                           silent = FALSE) 
{ 
  out <- list()
  checkmate::assert_directory_exists(ZIMSdir)
  assert_that(is.character(taxa))
  
   idtaxa <- list.files(glue::glue("{ZIMSdir}/"), "Split")%>%
     stringr::str_remove("Split_")
  assert_that(taxa %in% c(idtaxa, "All"),
              msg = glue::glue("taxa must one of {stringr::str_flatten_comma(idtaxa)}, or 'All'"))
  if (taxa == "All") taxa = c("Mammalia", "Aves", "Reptilia", "Amphibia", 
                              "Chondrichthyes", "Actinopterygii")
  assert_that(is.logical( silent))
    assert_that(is.list(species))
    assert_that (all(taxa %in% names(species)), 
                 msg = "species must be a list with the different taxa as names")
    if(length(tables)>0){  
    assert_that(is.character(tables))
    assert_that(all(tables %in%  c("Contraception", "HealthStatus", 
                                   "Institution","InstitutionAssociation", 
                                   "Move","Parent", "Weight", "Length",
                                   'DeathInformation', 'Collection')), msg = "The table names must be 'Contraception', 'HealthStatus', 'Institution','InstitutionAssociation', 'Move','Parent', 'Weight', 'Length', 'DeathInformation', and/or 'Collection'")
  }
  
  for (ta in taxa){
    if (!silent) {
      cat(glue::glue("{ta}"))
    }
    if(any(species[[ta]] != "All")){Species = species[[ta]]}
    #Load Animal File
    idfiles <- list.files(glue::glue("{ZIMSdir}/Split_{ta}/"), "Animal.csv")
    
    assert_that(length(idfiles )> 0,
                msg =glue::glue("Animal file for {ta} not found.")
    )
    assert_that(length(idfiles) < 2,
                msg = glue::glue("More than one Animal file for {ta}.")
    )
    
    Ani <- read.csv(glue::glue("{ZIMSdir}/Split_{ta}/{idfiles}"), sep = "@",  header = T, skipNul = TRUE)
    
    
    if(any(species[[ta]] != "All")){
      Ani <- Ani%>%
        filter(binSpecies %in% Species)
    }
    if(nrow(Ani) == 0) warnings("There are no data for selected species of {ta}")
    
    if(Animal){out[[ta]][["Animal"]]<- Ani}
    
    if(length(tables)>0){  
      for (ty in tables){
        
        idfiles <- list.files(glue::glue("{ZIMSdir}/Split_{ta}/"), glue::glue("{ty}.csv"))
        
        if(length(idfiles)== 0) error(glue::glue("{ty} file of {ta} not found."))
        
        if(length(idfiles) >= 2) error(glue::glue("More than one {ty} file for {ta}."))
        
        if (!silent) {
          cat(glue::glue("Loading {ty} of {ta}.\n"))
        }
        
        b <- read.csv(glue::glue("{ZIMSdir}/Split_{ta}/{idfiles}"), sep = "@",  header = T, skipNul = TRUE)
        
        if("AnimalAnonID" %in% colnames(b)){
          b <- b%>%
            filter(AnimalAnonID %in% Ani$AnimalAnonID)
        }
        out[[taxa]][[ty]]<- b
      }
    }
    if (!silent) {
      cat(glue::glue("{taxa} Done.\n"))
    }
  }
  return(out)
}
