# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Load Zims data
#' 
#' Load ZIMS data frames of given taxa
#'
#' @param Taxa  \code{character} Names of the taxa.
#' @param ZIMSDir \code{character} Directory where to find data.
#' @param Species  \code{list of character} names of the species studied. A list per taxa should be used, or "All".
#' @param Animal \code{logical} Whether the core animal data should be loaded.
#' @param tables \code{vector character} the type of data to load. 
#' @param silent \code{logical} Whether information of advancement should be printed.
#' 
#' @details
#' \code{tables} can take the following values : "Contraception", "HealthStatus", "DeathInformation","Institution","InstitutionAssociation", "Move","Parent", "Weight", "Length","DeathInformation", "Collection"
#'
#' @return A list of the data frames
#' @importFrom glue glue
#' @importFrom utils read.csv
#' @importFrom checkmate assert_directory_exists
#' @export
#'
#' @examples
#' file = system.file("sci_Animal.csv", package = 'ISRverse')
#' ZIMSDirtest = dirname(file)
#' data <- Load_Zimsdata	(Taxa = "Reptilia", 
#'                        ZIMSDir = ZIMSDirtest, 
#'                        Species = list(Reptilia = "All"),
#'                        Animal = TRUE,
#'                        tables = 'Weight') 
#' data$Reptilia$Animal
#' unlink(glue::glue("{ZIMSDirtest}/Split_Reptilia"), recursive = FALSE)
Load_Zimsdata	<- function (Taxa, ZIMSDir,
                           Species,
                           Animal = FALSE,
                           tables = c(),
                           silent = FALSE) 
{ 
  out <- list()
 # Check correct format for inputs ---------------------------------------------
 checkmate::assert_directory_exists(ZIMSDir)
  assert_that(is.character(Taxa))
  assert_that(is.logical(silent))
  assert_that(is.list(Species))
  assert_that (all(Taxa %in% names(Species)), 
               msg = "Species must be a list with the different Taxa as names")
  if(length(tables)>0){  
    assert_that(is.character(tables))
    assert_that(all(tables %in%  c("Contraception", "HealthStatus", 
                                   "Institution","InstitutionAssociation", 
                                   "Move","Parent", "Weight", "Length",
                                   'DeathInformation', 'Collection')), 
                msg = "The table names must be 'Contraception', 'HealthStatus',
                'Institution','InstitutionAssociation', 'Move','Parent', 'Weight', 
                'Length', 'DeathInformation', and/or 'Collection'")
  }
  idTaxa <- list.files(glue::glue("{ZIMSDir}/"), "Split")%>%
    stringr::str_remove("Split_")
  assert_that(Taxa %in% c(idTaxa, "All"),
              msg = glue::glue("Taxa must one of {stringr::str_flatten_comma(idTaxa)}, or 'All'"))
  if (Taxa == "All") Taxa = c("Mammalia", "Aves", "Reptilia", "Amphibia",    #nocov
                              "Chondrichthyes", "Osteichthyes")   #nocov
  
  # Loop over taxa ---------------------------------------------------------------
  for (ta in Taxa){
    if (!silent) {
      cat(glue::glue("{ta}"))
    }
    if(any(Species[[ta]] != "All")){Species1 = Species[[ta]]}
    #Load Animal File ----------------------------------------------------------
    idfiles <- list.files(glue::glue("{ZIMSDir}/Split_{ta}/"), "Animal.csv")
    assert_that(length(idfiles )> 0,
                msg =glue::glue("Animal file for {ta} not found."))
    assert_that(length(idfiles) < 2,
                msg = glue::glue("More than one Animal file for {ta}."))
     Ani <- read.csv(glue::glue("{ZIMSDir}/Split_{ta}/{idfiles}"), sep = "@",  header = T, skipNul = TRUE)
    
    #Filter Species List
    if(any(Species[[ta]] != "All")){
      Ani <- Ani%>%
        filter(binSpecies %in% Species1)
    }
    if(nrow(Ani) == 0) {warnings("There are no data for selected species of {ta}")}
    if(Animal){out[[ta]][["Animal"]]<- Ani}
    
     #Load other tables --------------------------------------------------------
    if(length(tables)>0){  
      for (ty in tables){
         idfiles <- list.files(glue::glue("{ZIMSDir}/Split_{ta}/"), glue::glue("{ty}.csv"))
        if(length(idfiles)== 0) error(glue::glue("{ty} file of {ta} not found.")) #nocov
        if(length(idfiles) >= 2) error(glue::glue("More than one {ty} file for {ta}."))  #nocov
          if (!silent) {cat(glue::glue("Loading {ty} of {ta}.\n"))}
         b <- read.csv(glue::glue("{ZIMSDir}/Split_{ta}/{idfiles}"), sep = "@",  header = T, skipNul = TRUE)
        
        if("AnimalAnonID" %in% colnames(b)){
          b <- b%>%
            filter(AnimalAnonID %in% Ani$AnimalAnonID)
        }
        out[[Taxa]][[ty]]<- b
      }
    }
    if (!silent) {cat(glue::glue("{Taxa} Done.\n"))}
  }
  return(out)
}
