# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Summarize taxon profiles analyses
#' 
#' Produce summary tables and plots of the demographic analyses made for all species
#'
#' @param AnalysisDir  \code{character} directory where to find the .Rdata files
#' @param SaveDir  \code{character} directory where to save summary plots and tables
#' @param namefile \code{character} Suffix to add to the name of files produced if needed. Default = ""
#' @param taxaList \code{vector of character} names of the taxa studied. Default= "Mammalia"
#' @param BySex \code{list} of the taxa names indicating the sexes analyzed. Default=list(Mammalia = c("Male", "Female"))
#' @param Sections \code{vector of character} names of the sections to update in the taxon profile results: "sur", "rep" and/or "gro". Default = c("sur", "rep", "gro")
#'
#' @return It saves summary tables and plots for each Sections and a general summary table. It returns the main summary table
#' @export
#' 
#' @importFrom ggplot2 ggplot scale_fill_brewer facet_wrap geom_bar labs position_dodge coord_flip
#' @importFrom ggpubr ggarrange
#' 
#' @examples
#' file = system.file("Testudo_hermanni.RData", package = 'ISRverse')
#' AnalysisDir  = dirname(file)
#' SaveDir = paste0(tempdir(check = TRUE),'\\temp')
#' dir.create(SaveDir)
#'
#' SummTab <- make_summary(AnalysisDir, SaveDir,
#'                taxaList = "Reptilia",
#'                BySex = list(Reptilia = c("Male", "Female")) ,
#'                Sections = c("sur", 'gro')
#' )
#' list.files(SaveDir)
#'
#'
#' unlink(SaveDir, recursive = TRUE)
make_summary <- function (AnalysisDir, SaveDir, namefile = "",
                          taxaList = "Mammalia", 
                          BySex = list(Mammalia = c("Male", "Female")) , 
                          Sections = c("sur", 'rep', 'gro')
){
  nullToNA <- function(x) {
     x[sapply(x, is.null)] <- NA
     return(x)
 }
  assert_that(is.character(taxaList))
  assert_that(taxaList %in% c("Mammalia", "Aves", "Reptilia", "Amphibia", 
                              "Chondrichthyes", "Actinopterygii"),
              msg = "taxa must one of 'Mammalia', 'Aves', 'Reptilia', 'Amphibia', 
                          'Chondrichthyes', or 'Actinopterygii'")
  assert_that(is.character(Sections))
  assert_that(all(Sections %in% c("sur", "gro", "rep")))
  checkmate::assert_directory_exists(AnalysisDir)
  checkmate::assert_directory_exists(SaveDir)
  assert_that(is.character(namefile))
  assert_that(is.list(BySex))
  assert_that(taxaList %in% names(BySex), msg = "BySex should be a list with names identical to taxaList")
  
  # List of available SRGs:
  SRGlist <- list.files(AnalysisDir, pattern = ".RData")
  assert_that(length(SRGlist) > 0, 
              msg = glue::glue("There are no result file in {AnalysisDir}"))
  SRGsps <- gsub(".RData", "", SRGlist)
   SRGspecies <- SRGsps%>%
    stringr::str_replace("_", " ")
  
  # Start counter:
  icount <- 0
  for (taxa in taxaList) {
    sexCats <- BySex [[taxa]]
    
    icount <- icount + 1
    
    table<-tibble(Class = rep(taxa, length(SRGlist)*length(sexCats)),
                  Species = rep(SRGspecies, each = length(sexCats)),
                  Sex = rep(sexCats, length(SRGlist)),
                  Nraw = numeric(1),
                  Ndate = numeric(1),
                  Nglobal = numeric(1),
                  Nalive = numeric(1),
                  firstDate = as.Date(x = integer(1), origin = "1980-01-01"),
                  maxAgeraw = numeric(1),
                  extractdate =  as.Date(x = integer(1), origin = "1980-01-01"),
                  Nlifespan = numeric(1),
                  GapThresh = numeric(1),
                  NThres = numeric(1)
    )
    
    # Taxa data table:
    if ("sur" %in% Sections){
      tempsur <- table%>%
        mutate(NGlobal = numeric(1), 
               NBasta = numeric(1), 
               Ndead = 0, 
               lxMin = numeric(1),
               maxAlive = numeric(1),
               outLev = numeric(1),
               analyzed = logical(1), 
               Nerr = numeric(1), 
               error = character(1))
    }else{tempsur = tibble()}
    
    if ("gro" %in% Sections){
      tempgro <- table%>%
        mutate(NWeight_raw = numeric(1), NInd_raw = numeric(1), 
               NWeight_val = numeric(1), NInd_val = numeric(1), 
               NWeight_age = numeric(1), NInd_age = numeric(1), 
               agemat = numeric(1), 
               NJuv = numeric(1),NJuv_keep = numeric(1),
               NAd = numeric(1), NAd_keep = numeric(1),
               NWeight = numeric(1), NInd = numeric(1), 
               analyzed = logical(1), 
               Nerr = numeric(1), error = character(1))
    }else{tempgro = tibble()}
    if ("rep" %in% Sections){
      temprep <- table%>%
        mutate()
    }else{temprep = tibble()}
    
    # Loop over species
    for (isp in SRGsps) {
      # SRG file:
      load(glue::glue("{AnalysisDir}/{isp}.RData"))
      
      table = table%>%
        rows_update(repout$general%>%as_tibble %>% 
                      mutate(Species = isp, Sex = "All"), 
                    by = c("Species", "Sex"), unmatched = "ignore")
      
      # Fill up data list:
      for (sx in sexCats) {
        
        table = table%>%
          rows_update(repout$summar[[sx]]%>%as_tibble() %>% 
                        mutate(Species = isp, Sex = sx), 
                      by = c("Sex", "Species"), unmatched = "ignore")
        
        if("sur" %in% Sections){
          
          tempsur <- tempsur%>%
            rows_update(repout$surv[[sx]]$summary%>%nullToNA%>%
                          as_tibble() %>% dplyr::select(-maxAge)%>%
                          mutate(Species = isp, Sex = sx), 
                        by = c("Sex", "Species"), unmatched = "ignore")
        }
        
        if("gro" %in% Sections){
          tempgro <- tempgro%>%
            rows_update(repout$weig[[sx]]$summary%>%as_tibble() %>% 
                          mutate(Species = isp, Sex = sx), 
                        by = c("Sex", "Species"), unmatched = "ignore")
        }
        
        if("rep" %in% Sections){
          temprep <- temprep%>%
            rows_update(repout$rep[[sx]]$summary%>%as_tibble() %>% 
                          mutate(Species = isp, Sex = sx), 
                        by = c("Sex", "Species"), unmatched = "ignore")
        }
      }
    }
    
    if("sur" %in% Sections){
      tempsur <- tempsur%>%
        rows_update(table, 
                    by = c("Sex", "Species"), unmatched = "ignore")
    }
    
    if("gro" %in% Sections){
      tempgro <- tempgro%>%
        rows_update(table, 
                    by = c("Sex", "Species"), unmatched = "ignore")
    }
    
    if("rep" %in% Sections){
      temprep <- temprep%>%
        rows_update(table, 
                    by = c("Sex", "Species"), unmatched = "ignore")
    }
    
    if (icount == 1) {
      SummTab <-table
      SurTab <- tempsur
      RepTab <- temprep
      GroTab <- tempgro
    } else {
      SummTab <- rbind(SummTab, table)
      SurTab <- rbind(SurTab, tempsur)
      RepTab <- rbind(RepTab, temprep)
      GroTab <- rbind(GroTab, tempgro)
    }
    
  }
  
  if("sur" %in% Sections){  
    SummTab <-SummTab%>%
      left_join(SurTab%>%
                  select(c(Species, Sex, NBasta, analyzed, error))%>%
                  rename(Surv_Ana = analyzed, Surv_error = error), 
                by = c("Species", "Sex"))
    
    utils::write.csv(SurTab, file = glue::glue("{SaveDir}/SRGs_Survival{namefile}.csv"),
                     row.names = FALSE)
    
    Surtabsum <- SurTab %>% 
      mutate(error =ifelse(error =="", "Analyzed",error),
             error = factor(error, levels = c('Analyzed','NThres == 0', 
                                              "Nglobal = 0", "%known births < 0.3",
                                              "Data from 1 Institution",
                                              "Nbasta < minNsur", "lxMin > minlx",
                                              "no DIC from Basta", "lx[MLE]<0.1",
                                              "Min(Life_exp)>2"), 
                            ordered = T)) %>% 
      group_by(Class, Sex, error)%>% summarize(N = n())
    p<- ggplot(data = Surtabsum, aes(x = error, y = N, fill = Sex)) +
      geom_bar(stat = "identity", position = position_dodge()) +
      scale_fill_brewer(palette = "Spectral")+
      labs(x = "") + facet_wrap(~ Class, scales = "free")+
      coord_flip()
    ggsave( glue::glue("{SaveDir}/Survival_error{namefile}.pdf"), p, width = 20, height = 6)
    
  }
  
  # if("rep" %in% Sections){ 
  #   SummTab <-SummTab%>%
  #     left_join(RepTab%>%
  #                 select(Species, Sex, NOffsp_raw, NParent_raw, NOffsp,NParent, 
  #                        NAdult_rep, Fert_Analyzed,Fert_error,
  #                        NOffsp_prob,NParent_prob, NReprEvent,Litt_Analyzed,Litt_error,
  #                        SeasNorth_Analyzed, SeasNorth_error, SeasNorth_Nbirth,
  #                        SeasSouth_Analyzed, SeasSouth_error, SeasSouth_Nbirth)%>%
  #                 rename(Fert_Ana = Fert_Analyzed,
  #                        Litt_Ana = Litt_Analyzed,
  #                        SeasNorth_Ana = SeasNorth_Analyzed,
  #                        SeasSouth_Ana = SeasSouth_Analyzed), 
  #               by = c("Species", "Sex"))
  #   
  #   
  #   utils::write.csv(RepTab, file =  glue::glue("{SaveDir}/SRGs_Reproduction{namefile}.csv", globDir),
  #                    row.names = FALSE)
  #   
  #   Ferttabsum <- RepTab  %>% tidyr::drop_na(Fert_error)%>% 
  #     mutate(Fert_error = ifelse(Fert_error =="", "Analyzed",Fert_error),
  #            Fert_error = factor(Fert_error, levels =c('Analyzed','NThres == 0', 
  #                                                      "NAdult == 0", "NOffspr_age == 0",
  #                                                      "NParent_bd == 0", 
  #                                                      "Data from 1 Institution",
  #                                                      "NOffsp < minNrepro",
  #                                                      "NParent < minNparepro"), 
  #                                ordered = T)) %>% 
  #     group_by(Class, Sex, Fert_error)%>% summarize(N = n())
  #   fert<- ggplot(data=Ferttabsum, aes(x=Fert_error, y=N, fill=Sex)) +
  #     geom_bar(stat="identity", position=position_dodge()) +
  #     scale_fill_brewer(palette="Spectral")+
  #     labs(x = "Fertility")+
  #     facet_wrap(~Class, nrow = 1, scales = "free")+
  #     coord_flip()
  #   Litttabsum <- RepTab  %>% tidyr::drop_na(Litt_error) %>% 
  #     filter(Sex!="Male")%>%
  #     mutate(Litt_error =ifelse(Litt_error =="", "Analyzed",Litt_error),
  #            Litt_error =ifelse(Litt_error =="NOffsp  < minNrepro",
  #                               "NOffsp < minNrepro",Litt_error),
  #            Litt_error = factor(Litt_error, levels = c('Analyzed','NThres == 0', 
  #                                                       "NParent_bd == 0", 
  #                                                       "NAdult == 0", "NOffspr_age == 0",
  #                                                       "NOffsp < minNrepro", 
  #                                                       "NParent < minNparepro",
  #                                                       "Data from 1 Institution",
  #                                                       "NOffsp_prob < minNrepro"), 
  #                                ordered = T))%>% 
  #     group_by(Class, Sex, Litt_error)%>% summarize(N = n())
  #   lit<- ggplot(data=Litttabsum, aes(x=Litt_error, y=N, fill=Sex)) +
  #     geom_bar(stat="identity", position=position_dodge()) +
  #     scale_fill_brewer(palette="Spectral")+
  #     labs(x = "Litter Size")+
  #     facet_wrap(~Class, nrow = 1, scales = "free")+
  #     coord_flip()
  #   SeaNtabsum <- RepTab  %>% tidyr::drop_na(SeasNorth_error)%>%
  #     filter(Sex=="Female" | Class == "Actinopterygii")%>%
  #     mutate(SeasNorth_error =ifelse(SeasNorth_error =="", "Analyzed",SeasNorth_error),
  #            SeasNorth_error = factor(SeasNorth_error, levels = c('Analyzed',"NThres == 0", 
  #                                                                 "No exact birth month",
  #                                                                 "Data from 1 Institution",
  #                                                                 "Nbirth <= minNseas"), 
  #                                     ordered = T)) %>% 
  #     group_by(Class, SeasNorth_error)%>% summarize(N = n())
  #   seaN<- ggplot(data=SeaNtabsum, aes(x=SeasNorth_error, y=N)) +
  #     geom_bar(stat="identity", position=position_dodge()) +
  #     labs(x = "Seasonality North")+
  #     facet_wrap(~Class, nrow = 1, scales = "free")+
  #     coord_flip()
  #   SeaStabsum <- RepTab  %>% tidyr::drop_na(SeasSouth_error)%>% 
  #     filter(Sex=="Female" | Class == "Actinopterygii")%>%
  #     mutate(SeasSouth_error =ifelse(SeasSouth_error =="", "Analyzed",SeasSouth_error),
  #            SeasSouth_error = factor(SeasSouth_error, levels = c('Analyzed',"NThres == 0", 
  #                                                                 "No exact birth month", 
  #                                                                 "Data from 1 Institution",
  #                                                                 "Nbirth <= minNseas"), 
  #                                     ordered = T)) %>% 
  #     group_by(Class, SeasSouth_error)%>% summarize(N = n())
  #   seaS<- ggplot(data=SeaStabsum, aes(x=SeasSouth_error, y=N)) +
  #     geom_bar(stat="identity", position=position_dodge()) +
  #     labs(x = "Seasonality South")+
  #     facet_wrap(~Class, nrow = 1, scales = "free")+
  #     coord_flip()
  #   figure <- ggarrange(fert, lit, seaN,seaS,
  #                       # labels = c("A", "B", "C"),
  #                       ncol = 1, nrow = 4)
  #   ggsave( glue::glue("{SaveDir}/Reproduction_error{namefile}.pdf"), figure, width = 25, height = 15)
  #   
  # }          
  # 
  if("gro" %in% Sections){            
    SummTab <-SummTab%>%
      left_join(GroTab%>%
                  select(Species, Sex, NWeight_raw , NWeight, analyzed,error)%>%
                  rename(Gro_Ana = analyzed, Gro_error = error), 
                by = c("Species", "Sex"))
    
    
    utils::write.csv(GroTab, file = glue::glue("{SaveDir}/SRGs_Growth{namefile}.csv"),
                     row.names = FALSE)
    
    Grotabsum <- GroTab  %>% tidyr::drop_na(error)%>% 
      mutate(error =ifelse(error =="", "Analyzed",error),
             error = factor(error, levels = c('Analyzed',"No known Sex", 
                                              "No weight for this sex category",
                                              "No valid weight measure", "Data from 1 Institution",
                                              "NWeight < minNgro", "NInds < minNIgro", "Model did not fit"), 
                            ordered = T)) %>%
      group_by(Class, Sex, error)%>% summarize(N = n())
    p<- ggplot(data=Grotabsum, aes(x=error, y=N, fill=Sex)) +
      geom_bar(stat="identity", position=position_dodge()) +
      scale_fill_brewer(palette="Spectral")+
      labs(x = "Growth")+facet_wrap(~Class, nrow = 2, scales = "free")+
      coord_flip()
    ggsave( glue::glue("{SaveDir}/Growth_error{namefile}.pdf"), p, width = 20, height = 6)
    
  }
  
  
  SummTab <-SummTab%>%
    rowwise%>%
    mutate( Any_Ana = any(across(ends_with("analyzed"))),
            All_Ana = all(across(ends_with("analyzed"))))
  
  
  utils::write.csv(SummTab, file =  glue::glue("{SaveDir}/SRGs_Analyses{namefile}.csv"),
                   row.names = FALSE)
  return(SummTab)
  
}
