# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Data Papers: Make figures & Tables
#' 
#'
#' @param AnalysisDir  \code{character} directory where to find the analyses results: .Rdata files
#' @param SaveDir  \code{character} directory where to save summary plots and tables
#' @param namefile \code{character} Suffix to add to the name of files produced if needed.
#' @param Sections \code{vector of character} names of the sections: "sur", "rep" and/or "gro".
#' @return It saves the plots and tables used in the data papers.
#' @export
#' 
#' @importFrom ggplot2 ggplot scale_fill_brewer facet_wrap geom_bar labs position_dodge coord_flip ylab xlab geom_boxplot scale_fill_manual theme_bw geom_violin stat_summary theme element_text
#' @importFrom ggpubr ggarrange
#' @importFrom grDevices grey
#' @importFrom stats cor
#' 
#' @examples
#' file = system.file("sci_Animal.csv", package = 'ISRverse')
#' AnalysisDir  = dirname(file)
#' SaveDir = paste0(tempdir(check = TRUE),'/temp')
#' dir.create(SaveDir)
#' out <-Make_SurFigTab (AnalysisDir, SaveDir,
#'                       Sections = "sur")
#' unlink(SaveDir, recursive = TRUE)
Make_SurFigTab <- function (AnalysisDir, SaveDir = NA, namefile = "",
                            Sections = c("sur", 'rep', 'gro')
){ 
  # Check correct format for inputs -----------------------------------------------
  assert_that(is.character(Sections))
  assert_that(all(Sections %in% c("sur", "gro", "rep")))
  checkmate::assert_directory_exists(AnalysisDir)
  checkmate::assert_directory_exists(SaveDir)
  assert_that(is.character(namefile))
  
  #Load main tables --------------------------------------------------------------
  Tab = readr::read_csv2(glue::glue("{AnalysisDir}/DP_Survival{namefile}.csv"), show_col_types = FALSE)
  AnyAna = readr::read_csv2(glue::glue("{AnalysisDir}/DP_Any_Ana{namefile}.csv"), show_col_types = FALSE)
  
  # Create the table for CHECKS---------------------------------------------------
  Tabcheck = Tab%>%
    filter(stat %in% c("mean", "value"),
           param %in% c("Gof_KM_coeff1", "Gof_KM_coeff2", "Gof_martingale", 
                        "LxatMLE", "LEmaxOage", "KMMinLx", "L50","L90", 
                        "S1month", "S1year"))%>%
    select(Class, Species, Sex, param, value,Data)%>% 
    tidyr::pivot_wider(names_from=c(param, Data), values_from = value)%>%
    mutate(`CH_GofKM0.6` = Gof_KM_coeff1_Raw >0.6,
           `tCH_GofKM0.8` = Gof_KM_coeff1_Raw >0.8,
           CH_SurKM = S1month_KM >  S1year_KM,
           CH_SurMod = S1month_Model >  S1year_Model,
           CH_LKM = L50_KM <  L90_KM,
           CH_LMod = L50_Model <  L90_Model,
           CH_MinLxatMLE = LxatMLE_Raw > 0.1,
           CH_LEmaxage = LEmaxOage_Raw<=2,
           CH_KMMinLx = KMMinLx_Raw<= 0.1,
           CH_CIL50_Model = L50_Model <  L90_Model,
    )
  Tabcheck2 = Tab%>%
    filter(stat %in% c("mean", "upper", "lower"),
           Data %in% c("KM", "Model"),
           !(param %in% c("b_Gomp", "Epx", "H", "CV", "G")))%>%
    group_by(Class, Species, Sex, param, Data)%>%
    summarize(IC = (max(value)-min(value))/value[stat=="mean"]<1)%>%
    tidyr::pivot_wider(names_from=c(param,Data), names_prefix = "CH_IC_",values_from = IC)
  
  Tabcheck =Tabcheck %>%
    left_join(Tabcheck2, by = c("Class", "Species","Sex"))%>%
    rowwise()%>%
    mutate(ALLcheck = all(across(starts_with("CH_")), na.rm = TRUE))
  
  # Create the Figures -------------------------------------------------------
  # Remove species for which checks are not ok
  Tabselect = Tab%>%
    left_join(Tabcheck%>%select(Species, Sex, ALLcheck), by = c('Species', 'Sex'))%>%
    filter(ALLcheck)
  if(nrow(Tabselect)==0){Tabselect = Tab%>%mutate(ALLcheck = FALSE)
  warning("No analyses passed all checks, so all analyses are present in plots and tables (instead of none)")}
  
  # Figure Data Summary
  A1 =  Tabselect%>%select(Class, Species)%>%distinct%>%
    ggplot(aes(x = Class))+ ylab("Number of species")+
    geom_bar()+theme_bw()+xlab ('')+
  theme(text = element_text(size = 20),axis.text.x=element_text(size=20))
  mycol = c("grey", "lightsalmon2", "aquamarine3")
  names(mycol) = c("All", 'Female', 'Male')
  
  A2 =  AnyAna%>%
    filter(Surv_Ana)%>%select(Class, Species, Sex, Nselect)%>%
    ggplot(aes(x = Class, fill = Sex, y=Nselect))+ ylab("Number of individuals")+
    geom_boxplot( linewidth = 0.75)+theme_bw()+
    scale_fill_manual(values=mycol)+xlab ('')+
  theme(text = element_text(size = 20),axis.text.x=element_text(size=20))
  
  A3 =  Tabselect%>%filter(param %in% c("Nrc", "Ndead"))%>%
    tidyr::pivot_wider(names_from=param, values_from = value)%>%
    mutate(Pmort = Ndead/(Ndead +Nrc))%>%
    ggplot(aes(x = Class, y=Pmort))+ ylab("% of dead individuals")+
    geom_boxplot(linewidth = 0.75)+theme_bw()+xlab ('')+
  theme(text = element_text(size = 20),axis.text.x=element_text(size=20))
  
  A4 =  Tabselect%>%filter(param %in% c("N8090", "N9000", "N0010", "N1020","N2030"))%>%
    mutate(param = factor(param, ordered = T, levels = c("N8090", "N9000", "N0010", "N1020","N2030")) )%>%
    group_by(Class, param)%>%
    mutate(Pval =sum(value))%>%
    ungroup()%>%
    group_by(Class)%>%
    mutate(Pval =Pval/sum(Pval))%>%
    # pivot_wider(names_from=param, values_from = Pval)%>%
    ggplot(aes(x = Class, y=Pval, fill =param))+ ylab("Percentage of births")+
    geom_bar(stat="identity")+theme_bw()+ scale_fill_brewer(palette="Paired") +
    xlab ('') +
  theme(text = element_text(size = 20),axis.text.x=element_text(size=20))
  Fig1 =cowplot::plot_grid(A1,A2,A3,A4, ncol = 2, rel_widths =c(7,9), rel_heights = 8)
  
  
  # Figure comparison stat
  colval = matrix(c("darkorange2","brown4","deepskyblue1"),
                  nrow = 1, byrow = T)
  figviol <-function(RES, PARAM, YLAB,colval){
    
    RES%>%
      filter(param%in% PARAM,
             stat %in% c("value", "mean"))%>%
      ggplot(aes(y=value, x=Data, fill =Data)) +
      geom_violin(trim = T, show.legend = FALSE)+
      scale_fill_manual(values=colval)+
      stat_summary(fun=median, geom="point", size=1, color=grey(0.9), show.legend = FALSE)+
      #geom_hline(yintercept = 0, color = "black", linetype = "dashed",linewidth=0.5, show.legend = FALSE) +
      ylab(YLAB) + xlab(" ") +
      facet_wrap(~Class, scales = "free",nrow = 1) +
      theme_bw()+
  theme(text = element_text(size = 20),axis.text.x=element_text(size=20))
  }
  Fig2 = cowplot::plot_grid(plotlist = list(figviol(Tabselect, PARAM = c("L50"), YLAB = "Median LE", colval = colval),
                                            figviol(Tabselect, PARAM = c("MLE"), YLAB = "Mean LE", colval = colval),
                                            figviol(Tabselect, PARAM = c("Ex"),  YLAB = "Ex", colval = colval),
                                            figviol(Tabselect, PARAM = c("L90"), YLAB = "Longevity", colval = colval)),  
                            labels = c("","","",""), # label_x = 0.2, label_y = 1.2,
                            nrow = 4, ncol = 1, hjust = -1, vjust = 62
                            )
  
  Fig3 = cowplot::plot_grid(plotlist = list(figviol(Tabselect, PARAM = c("G"),   YLAB = "Gini", colval = colval),
                                            figviol(Tabselect, PARAM = c("CV"),  YLAB = "CV", colval = colval),
                                            figviol(Tabselect, PARAM = c("Epx"), YLAB = "-log(H)", colval = colval)),
                            nrow = 3, ncol = 1, hjust = -1, vjust = 62
                            )
  
  Fig4 = cowplot::plot_grid(plotlist = list(figviol(Tabselect, PARAM = c("S1month"), YLAB = "First month survival",colval = colval),
                                            figviol(Tabselect, PARAM = c("S1year"), YLAB = "First year survival",colval = colval)),
                            nrow = 2, ncol = 1,
                            hjust = -1, vjust = 62
                            )

   
  #Figure errors
  Surtabsum <- AnyAna %>% 
    mutate(error = ifelse(is.na(Surv_error), "Analyzed",Surv_error),
           error = factor(error, levels = c('Analyzed','Nselect < MinN','Nuncertdeath < MinNSur', 
                                                 "lxmin > MinLx",
                                                 "NBasta = 0", "%known births < MinBirthKnown",
                                                 "Data from 1 Institution","Nbasta > MaxNSur",
                                                 "Nbasta < MinNSur",
                                                 "lxMin > MinLx",
                                                 "no DIC from Basta", 
                                                 "Kaplan-Meier does not fit",
                                                 "lx_MLE < MinMLE",
                                                 "Min(Life_exp) >= MaxLE",
                                                 "Kaplan-Meier does not fit:2"), 
                                                  ordered = T)) %>% 
    group_by(Class, Sex, error)%>% summarize(N = n())
  p<- ggplot(data = Surtabsum, aes(x = error, y = N, fill = Sex)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    scale_fill_brewer(palette = "Spectral")+
    labs(x = "") + facet_wrap(~ Class, scales = "free")+
    coord_flip()
  
  
  # Correlation-----------------------------------------------------------
   Tabcor = Tabselect%>%
                 filter(stat %in% c("mean", "value"))%>%
                 tidyr::drop_na()%>%
                 select(-c( "models", "firstage", "stat","ALLcheck" ))%>%
                 tidyr::pivot_wider(names_from=c(param,Data), values_from = value)
  Tabcor1 = Tabselect%>%
                  filter(Data != "Raw",
                         stat %in% c("mean", "value"))%>%
                 tidyr::drop_na()%>%
                 select(-c( "models", "firstage", "stat","ALLcheck" ))%>%
                 tidyr::pivot_wider(names_from=c(param,Data), values_from = value)
  
   cortab = cor(Tabcor1%>%
                   select(-c("Class", "Species", "Sex")))
  corplot = corrplot::corrplot(cortab, method = 'number')
  if(nrow(Tabcor)>25){
    a=Tabcor%>%
      select(Class, L50_KM,L50_Raw, L50_Model, MLE_Model, remex0_Model, Ex_KM, MLE_KM , MLE_Raw )%>%
      mutate(Class = as.factor(Class))%>%
     GGally::ggpairs(columns =2:7,                 # Data frame
        aes(color = Class,  # Color by group (cat. variable)
            alpha = 0.5))
    ggsave(a, filename =glue::glue("{SaveDir}/Survival_corplot50{namefile}.pdf"), width = 20, height = 20)
    
   a=Tabcor%>%
      select(Class, L90_KM, L90_Model, L90_Raw, S1month_KM, S1year_KM, S1month_Model, S1year_Model)%>%
      mutate(Class = as.factor(Class))%>%
     GGally::ggpairs(columns =2:8,                 # Data frame
        aes(color = Class,  # Color by group (cat. variable)
            alpha = 0.5))
    ggsave(a, filename =glue::glue("{SaveDir}/Survival_corplot90{namefile}.pdf"), width = 20, height = 20)
    
     a=Tabcor%>%
      select(Class, Epx_KM, G_KM, CV_KM,  Epx_Model, G_Model, CV_Model)%>%
      mutate(Class = as.factor(Class))%>%
     GGally::ggpairs(columns =2:7,                 # Data frame
        aes(color = Class,  # Color by group (cat. variable)
            alpha = 0.5))
    ggsave(a, filename =glue::glue("{SaveDir}/Survival_corplotCV{namefile}.pdf"), width = 20, height = 20)
}
 
    
     # Create survival TABLES-----------------------------------------------------------
   Tabdata = Tabselect%>%
    select(Class, Species, Sex, param, value)%>%
    filter(param %in% c("NBasta", "Ndead", "BDincert", 
                        "QBD10", "QBD50", "QBD90",
                        "N8090","N9000","N0010","N1020","N2030"))%>%
    tidyr::pivot_wider(names_from=param, values_from = value)%>%
    mutate(`%Birth>2000` = (N0010+N1020+N2030)/ (N8090+N9000+N0010+N1020+N2030))%>%
    select(-c("N8090","N9000","N0010","N1020","N2030"))
  
  Tabmetrics = Tabselect%>%
    filter(param %in% c("L50", "MLE", "remex0", "Ex",
                        "L90",
                        "S1month", "S1year",
                        "H", "Epx", "G", "CV", "Hx", 
                        "b_Gomp"))%>%
    tidyr::pivot_wider(names_from=c(param, Data, firstage, stat), values_from = value)
  
  
  # SAVE everything ------------------------------------------------------------
  if(!is.na(SaveDir)){
    
    ggsave(plot = Fig1, filename = glue::glue("{SaveDir}/Fig_Survival_summary{namefile}.pdf"), width = 20, height = 20)
    ggsave(Fig2, filename =glue::glue("{SaveDir}/Fig_Survival_MLE{namefile}.pdf"), width = 20, height = 20)
    ggsave(Fig3, filename =glue::glue("{SaveDir}/Fig_Survival_H{namefile}.pdf"),  width = 20, height = 20)
    ggsave(Fig4, filename =glue::glue("{SaveDir}/Fig_Survival_1y1m{namefile}.pdf"),  width = 20, height = 20)
    ggsave(p, filename =glue::glue("{SaveDir}/Survival_error{namefile}.pdf"), width = 20, height = 20)
    pdf(glue::glue("{SaveDir}/Survival_corplot{namefile}.pdf"), width = 20, height = 20)
    corrplot::corrplot(cortab, method = 'number')
    dev.off()
    
    readr::write_excel_csv2(Tabdata, file =  glue::glue("{SaveDir}/Survival_Data{namefile}.csv"))
    readr::write_excel_csv2(Tabmetrics, file =  glue::glue("{SaveDir}/Survival__metrics{namefile}.csv"))
    readr::write_excel_csv2(Tabcheck, file =  glue::glue("{SaveDir}/Survival__check{namefile}.csv"))
    # readr::write_excel_csv2(cortab, file =  glue::glue("{SaveDir}/Survival__cortab{namefile}.csv"))
  }
  
  return(out = list(Fig1 = Fig1, Fig2 = Fig2, Fig3 = Fig3, Fig4 = Fig4,error =p,
                    corplot = corplot,
                    Tabdata = Tabdata, Tabmetrics = Tabmetrics,cortab = cortab,
                    Tabcheck =Tabcheck ))
}
