# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand

#' Main Reproduction analysis for taxon profiles
#' 
#' Run the age at sexual maturity analysis, the litter size analysis
#' 
#' @param coresubset \code{data frame} cleaned core data including only the selected individuals. It must includes at least the following columns: *AnimalAnonID*, 'BirthType', *MaxBirthDate*, *MinBirthDate*, *DepartDate*, *BirthDate*,*SexType*, and *FirstHoldingInstitution*
#' @param collection \code{data frame} Collection data including at least the following columns: *AnimalAnonID*, *ScopeType*, *ChangeDate*
#' @param parent \code{data frame} Parent data including at least the following columns: *ParentAnonID*, *ParentCollectionScopeType*, *OffspringCollectionScopeType*, *AnimalAnonID*, *ParentOriginType*, *Probability*
#' @param move \code{data frame} Moves data including at least the following columns: *AnimalAnonID*, *To*, *Date*
#' @param Repsect \code{character} names of the reproductive analyses to run: "agemat", "litter" and/or ...
#' @param BirthType_parent \code{character} Captive, Wild, or All. Default =  "Captive"
#' @param BirthType_offspring \code{character} Captive, Wild, or All. Default =  "Captive"
#' @param Nday \code{numeric} Number of consecutive days over which the birth dates of a litter/clutch can be spread. Default = 7
#' @param Global \code{logical} Whether only individuals belonging to global collections should be used. Default = #'
#' @param minNrepro \code{numeric} Minimum number of birth records needed to run reproductive analyses. Default = 50
#' @param minNparepro \code{numeric} Minimum number of unique parent records needed to run reproductive analyses. Default = 30
#' @param parentProb \code{numeric} Minimum percentage of parentage probability to include. Default = 80
#' @param minNlitter \code{numeric} Minimum number of litters to run the analysis. The data frame for litter size will be produced in all cases. Default = 30
#' @param minNrepro \code{numeric} Minimum number of birth records needed to run reproductive analyses. Default = 50
#' @param minNparepro \code{numeric} Minimum number of unique parent records needed to run reproductive analyses. Default = 30
#' @param minNseas \code{numeric} XXXXXXXXXXX
#' @param minInstitution \code{numeric} Minimum number of institutions that should hold records to run the survival analysis. Default = 2
#'
#' @return  The output of a list including:
#' * a summary of the data used:
#' * A summary including:
#'  - Nbirths: the raw number of births
#'  - Nadults: the raw number of potential reproductive adults
#'  - NOffsp: the number of offspring with known birth date and with parents with known age
#'  - NParent: the number of unique parents with known age and with offspring with known birth date
#'  - NOffsp_age: the number of offspring with known birth date and with parents with a known age > 0
#'  - NParent_age: the number of unique parents with known and positive age and with offspring with known birth date
#'  - a logical indicated if any reproductive analysis can be performed
#'  -  If no analyses can be performed, an error and its number (Nerr) are returned: The possibility for  this functions are: 1/Nbirths < minNrep, 2/Nparents < minNparep, and 3/Data from N Institution
#'  - a logical indicated if the age at maturity analysis can be performed
#'  - a logical indicated if the litter size analysis can be performed
#'* The output of each analysis. See the function Rep_agemat, Rep_littersize, Rep_fertility, and and Rep_seasonality for more details.
#'  
#'  
#'  
#' @export
Rep_main <- function( coresubset, collection, parent, move,  Repsect = c('agemat', 'litter'),
                      BirthType_parent = "Captive", BirthType_offspring = "Captive", 
                      Global = TRUE, minInstitution = 2, 
                      minNrepro = 100,minNparepro = 30,
                      parentProb = 80, minNlitter = 20, Nday = 7,
                       minNseas = 50) {
  
  assert_that(is.data.frame(coresubset))
  assert_that(is.data.frame(collection))
  assert_that(is.data.frame(parent))
  assert_that(is.data.frame(moves))
  assert_that(is.double(minInstitution))
  assert_that(is.numeric(Nday))
  
  assert_that(coresubset %has_name% c("AnimalAnonID", 'BirthType', "MaxBirthDate", 
                                      "MinBirthDate", "DepartDate", "BirthDate",
                                      "SexType", "FirstHoldingInstitution"))
  assert_that(collection %has_name% c("AnimalAnonID", "ScopeType", "ChangeDate"))
  assert_that(parent %has_name% c("ParentAnonID", "ParentCollectionScopeType", 
                                  "OffspringCollectionScopeType", "AnimalAnonID",
                                  "ParentOriginType", "Probability"))
  assert_that(moves %has_name% c("AnimalAnonID", "To", "Date"))
  
  assert_that(is.character(BirthType_parent))
  assert_that(BirthType_parent %in% c("Captive", "Wild", "All"))
  assert_that(is.character( BirthType_offspring))
  assert_that( BirthType_offspring %in% c("Captive", "Wild", "All"))
  assert_that(is.logical(Global))
  assert_that(all(Repsect %in% c("agemat", "litter")))
  
  assert_that(is.numeric(parentProb))
  assert_that(parentProb > 0)
  assert_that(is.numeric(minNrepro))
  assert_that(minNrepro > 0)
  assert_that(is.numeric(minNparepro))
  assert_that(minNparepro > 0)
  assert_that(is.numeric(minNlitter))
  assert_that(minNlitter > 0)
  assert_that(is.numeric( minNseas))
  assert_that( minNseas > 0)
  assert_that(is.numeric( Nday))
  assert_that( Nday >= 0)
  out <- list()
  
  #prepare Reproduction data
  Datarep <- Rep_prepdata(coresubset = coresubset, 
                          collection, parent,move,
                          BirthType_parent = BirthType_parent, 
                          BirthType_offspring = BirthType_offspring,
                          minNrep=minNrepro, minNparep =minNparepro, 
                          Global = Global)
  out[["summary"]] <- Datarep$summary
  out$summary$litt_analyzed =  out$summary$amat_analyzed = FALSE
  if(nrow(Datarep$Reprodata)>0){
  if(length(unique(Datarep$Reprodata$currentInst))>=minInstitution){
    #remove curretn inst to avoid duplicated lines
    subfert <- Datarep$Reprodata%>%
      select(-currentInst)%>%
      distinct() 
    
    
    if("agemat" %in% Repsect){
      #Calculate reproductive age statistics
      out[["agemat"]] <- Rep_agemat(subfert)
         out$summary$amat_analyzed = out$agemat$summary$analyzed
  }
    if("litter" %in% Repsect){
      #Calculate reproductive age statistics
      out[["litter"]] <- Rep_littersize(subfert, perAge = TRUE,
                                        Nday = Nday, parentProb = parentProb,  
                                        minNlitter =minNlitter)
       out$summary$litt_analyzed = out$litter$summary$analyzed
    }
  }else{
          outsummary$error = glue::glue("Data from {length(unique(Datarep$Reprodata$currentInst)} Institution(s)")
          outsummary$Nerr = 3
          outsummary$analyzed = FALSE
  }
  }
  return(out)
}
