# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand

#' Litter Size
#' 
#' Make a data frame of litter size per parent and birth date and produce summary tables of litter size. it selects only offspring/mother couples
#'
#' @param Reprodata \code{data frame} including at least the columns *AnimalAnonID*, *ParentAnonID*, *ParentType*, *Probability*, *Offspring_BirthDate*, *Offspring_Inst* and *Parent_Age*
#' @param Nday \code{numeric} Number of consecutive days over which the birth dates of a litter/clutch can be spread. Default = 7
#' @param parentProb_Dam \code{numeric} Minimum percentage of parentage probability to include for Dam. Default = 80
#' @param parentProb_Sire \code{numeric} Minimum percentage of parentage probability to include for Sire. Default = 80
#' @param minNlitter \code{numeric} Minimum number of litters to run the analysis. The data frame for litter size will be produced in all cases. Default = 30
#'
#' @return A list including:
#' * A data frame with the litter size per mother and birth date
#' * A table including the number and proportion of each size of litter
#' * Summary statistics including:
#' - NOffsp_prob: Number of offspring
#' - NParent_prob: Number of parents
#' - NReprEvent: Number of litters
#' - MeanLittSize: Mean litter size 
#' - MedLittSize: Median litter size 
#' - SdLittSize: Standard deviation of litter size 
#' - analyzed = FALSE,
#' - error: if the litter size where not analysze, the associated error is printed here. It can be :"No births with parentage probability higher than {parentProb} or  N litter < {minNlitter}
#' - Nerr: The number id of the error
#' * a table including the mean and standard deviation of litter size per maternal age
#' 
#' @export
#'
#' @examples
#' data(core)
#' data(collection)
#' data(parent)
#' data(moves)
#' #prepare Data
#' Data <- Rep_prepdata (coresubset = core, collection, parent, moves, minNrep = 1, minNparep = 1,
#'                       BirthType_parent = "All", BirthType_offspring = "All" )
#'
#' #Estimate litter size
#' out <- Rep_littersize(Data$Reprodata, 
#'                       Nday = 7)
#'
#' out
Rep_littersize <- function(Reprodata,
                           Nday = 7, 
                           parentProb_Dam = 80,parentProb_Sire = 80,  minNlitter =30
) {
  
  assert_that(is.data.frame(Reprodata))
  
  assert_that(Reprodata %has_name% c("AnimalAnonID", "ParentAnonID", "Probability", 
                                     "ParentType", "Offspring_BirthDate",
                                     "Offspring_Inst", "Parent_Age"))
  

  assert_that(is.numeric(Nday))
  assert_that(is.numeric(parentProb_Dam))
 assert_that(is.numeric(parentProb_Sire))
  assert_that(is.numeric(minNlitter))
  
  
  
  littSumm <- list(NOffsp_prob = NULL, NParent_prob = NULL, NReprEvent = NULL,
                   analyzed = FALSE,error = "", Nerr= 0,
                   MeanLittSize = NULL, MedLittSize = NULL, SdLittSize = NULL)
  littSizeDf <- tibble()
  littSizeTab <- NULL
  littSizeperAge <- NULL
    subpar_sire <- Reprodata %>%
    filter(ParentType == "Parentage_Sire",
           Probability >= parentProb_Sire)%>%
    select("ParentAnonID", "AnimalAnonID", "Parent_Age", "ParentAnonID", "Parent_Age")%>%
      mutate(Father_Age =round(Parent_Age,2))%>%
      select(-'Parent_Age')%>%
    rename(FatherAnonID = ParentAnonID)
  
  subpar <- Reprodata %>%
    filter(ParentType == "Parentage_Dam",
           Probability >= parentProb_Dam)%>%
    left_join(subpar_sire, by = "AnimalAnonID",relationship = "many-to-many" )



  
  littSumm$NOffsp_prob <- length(unique(subpar$AnimalAnonID))
  littSumm$NParent_prob <- length(unique(subpar$ParentAnonID))
  
  col = c("ParentAnonID", "AnimalAnonID", "Offspring_BirthDate", "Offspring_Inst", "FatherAnonID", "Father_Age", "Parent_Age")
  
  
  if(nrow(subpar) >0){
    #remove duplicated lines
    subpar <- subpar%>%
      dplyr::select(all_of(col))%>%
      distinct()
    
    
    
    for (id in unique(subpar$ParentAnonID)) {
      parid <- subpar%>%filter(ParentAnonID == id)
      
      parid <- parid %>%
        arrange(Offspring_BirthDate)
      diff=  c((Nday+1), as.numeric(diff(parid$Offspring_BirthDate)))
      parid$litter=  cumsum(ifelse(diff > Nday, 1, 0))

      parid <- parid%>%
        mutate(Mother_Age = round(Parent_Age,2)
               )%>%
        group_by (ParentAnonID, Offspring_Inst, litter, Mother_Age)%>%
        summarize(litterSize = length(unique(AnimalAnonID)),
                  MeanBirthDate = median(Offspring_BirthDate),
                  FatherAnonID = list(FatherAnonID),
                  Father_Age = list(Father_Age),
                  .groups = 'drop')%>%
        # ungroup()%>%
        dplyr::select(-litter)%>%
        rename(MotherAnonID = ParentAnonID,
               InstitutionAnonID = Offspring_Inst)
      
      littSizeDf <- rbind(littSizeDf, parid)
    }

   littSizeDf<- littSizeDf%>%tidyr::unnest(c(FatherAnonID,Father_Age))%>%distinct()%>%
        group_by (MotherAnonID, InstitutionAnonID, litterSize, MeanBirthDate, Mother_Age)%>%
        summarize(FatherAnonID = list(FatherAnonID),
                  Father_Age = list(Father_Age),
                  .groups = 'drop')
    
    if (nrow(littSizeDf)>= minNlitter)  {
      littSizeTab <- littSizeDf%>%
        group_by(litterSize)%>%
        summarise( N = n(),
                   prop = n()/nrow(littSizeDf),
                  .groups = 'drop')
      
    
        littSizeperAge <- littSizeDf%>%
          group_by(Mother_Age)%>%
          summarise(MeanlittSize = mean(litterSize),
                    SDlittSize = sd(litterSize),
                    Nlitter = n(),
                  .groups = 'drop')%>%
          ungroup()

      # Summary
      littSumm$MeanLittSize =  mean(littSizeDf$litterSize)
      littSumm$MedLittSize = median(littSizeDf$litterSize)
      littSumm$SdLittSize = median(littSizeDf$litterSize)
      littSumm$analyzed = TRUE 
      littSumm$NReprEvent= sum(littSizeTab$N)
    }else{
      littSumm$error = glue::glue("N litter < {minNlitter}")
      littSumm$Nerr = 5
    }
  }else{
    littSumm$error = glue::glue("No births with Parentage probability higher than {parentProb}")
    littSumm$Nerr = 4
    
  }
  return(list(summary = littSumm, littSizeDf = littSizeDf,  
              littSizeTab =  littSizeTab, littSizeperAge = littSizeperAge))
}
