# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand

#' Age of reproduction
#' 
#' Returns summary statistcs for age of reproduction
#'
#' @param Reprodata \code{data frame} including at least the columns *ParentAnonID* and *Parent_Age*
#'
#' @return A data frame including:
#' * N_moth_agemat: Number of mothers used
#' * N_birth_agemat : Number of births used
#' * ageMat: age at first reproduction (i.e. when 2.5% of females have reproduced for the first time)
#' * ageYouRep: Minimum age at first reproduction
#' * ageOld1Rep: Maximum age at first reproduction
#' * ageMean1Rep: Mean age at first reproduction
#' * ageSd1Rep: Standard deviation of age at first reproduction
#' * ageOldRep: Maximum age of reproduction
#' * ageMeanRep: Mean age of reproduction 
#' * ageSdRep: Standard deviation of age of reproduction 
#' * ageMedRep: Median age of reproduction 
#' * ageMeanRepIC: 95% confident interval of mean age of reproduction 
#' * ageMean1RepIC: 95% confident interval of mean age at first reproduction 
#' 
#' @export
#' @importFrom stats dist median var sd
#'
#' @examples
#' data(core)
#' data(collection)
#' data(parent)
#' data(moves)
#' #prepare Data
#' Data <- Rep_prepdata (coresubset = core, collection, parent, moves, 
#'                       minNrep = 1, minNparep = 1)
#' #Calculate summary for reproductive ages
#' out <- Rep_agemat(Data$Reprodata)
#' out
#'
Rep_agemat <- function(Reprodata) {
  
  assert_that(is.data.frame(Reprodata))
  
  assert_that(Reprodata %has_name% c("ParentAnonID", "Parent_Age"))
  
  
  fertSumm <- tibble(N_moth_agemat = 0,N_birth_agemat = 0, 
                     ageMat = NA,   
                     ageYouRep = NA, ageOldRep = NA, 
                     ageMean1Rep = NA,ageSd1Rep = NA, ageOld1Rep = NA,
                     ageMeanRep = NA, ageSdRep= NA, ageMedRep = NA,
                     ageMeanRepIC = NA, ageMean1RepIC = NA) 
  
  # Age at first reproduction:
  TageMat <-  Reprodata%>%select(ParentAnonID, Parent_Age)%>%
    group_by(ParentAnonID)%>%
    summarize(ageMat = min(Parent_Age),
              ageold = max(Parent_Age))%>%
    ungroup()
  
  fertSumm$N_moth_agemat  = nrow(TageMat)
  fertSumm$N_birth_agemat  = nrow( Reprodata)
  fertSumm$ageMat<- as.numeric(quantile(TageMat$ageMat, 0.025, 
                                        na.rm = TRUE))
  
  fertSumm$ageYouRep= as.numeric(min(TageMat$ageMat, na.rm = TRUE))
  fertSumm$ageOldRep= as.numeric(max( TageMat$ageold, na.rm = TRUE))
  fertSumm$ageOld1Rep = as.numeric(max(TageMat$ageMat, na.rm = TRUE))
  
  fertSumm$ageMean1Rep = mean(as.numeric(TageMat$ageMat), na.rm = TRUE)
  fertSumm$ageSd1Rep = sd(as.numeric(TageMat$ageMat), na.rm = TRUE)
  fertSumm$ageMean1RepIC = list(fertSumm$ageMean1Rep +c(-1.96, 1.96)*sqrt(var(as.numeric(TageMat$ageMat), na.rm = TRUE)/nrow(TageMat)))
  fertSumm$ageMeanRep = mean(as.numeric(Reprodata$Parent_Age), na.rm = TRUE)
  fertSumm$ageSdRep = sd(as.numeric(Reprodata$Parent_Age), na.rm = TRUE)
  fertSumm$ageMeanRepIC = list(fertSumm$ageMeanRep +c(-1.96, 1.96)*sqrt(var(as.numeric( Reprodata$Parent_Age), na.rm = TRUE)/nrow(Reprodata)))
  
  fertSumm$ageMedRep =  median(as.numeric(Reprodata$Parent_Age), na.rm = TRUE)
  
  return(fertSumm)
}
