# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand

#' my_fun Title
#'
#' @return 1
#' @export
#'
#' @examples
# Rep_main <- function() {
#   # Find institutions and their hemisphere:
#   Inst <- newcore$firstInst
#   idinst <- which(as.character(.institution$AnonInstitutionID) %in% Inst)
#   subinst <- .institution[idinst, ]
#   rownames(subinst) <- as.character(subinst$AnonInstitutionID)
#   subinst <- subinst[Inst, ]  
#   
#   # Find which are from the northern and southern hemisphere:
#   idnorth <- which(subinst$Latitude > 0)
#   idsouth <- which(subinst$Latitude < 0)
#   Hemisph <- rep(NA, nrow(subinst))
#   Hemisph[idnorth] <- "North"
#   Hemisph[idsouth] <- "South"
#   instHemisph <- data.frame(AnonInstID = subinst$AnonInstitutionID, 
#                             Continent = subinst$Continent, 
#                             Country = subinst$Country, 
#                             Hemisph = Hemisph)
#   
#   
#   # Extract contraception method:
#   idIncont <- which(as.character(.contraception$` AnonID`) %in% 
#                       as.character(newcore$anonID))
#   subContra <- .contraception[idIncont, ]
#   nContra <- length(idIncont)
#   method <- rep("NA", nContra)
#   genMethod <- c("hormonal", "surgical", "immunological", "Management", 
#                  "Indeterminate", "Undetermined")
#   methodTransl <- c("Hormonal", "Surgical", "Immunological", "Management", 
#                     "Undetermined", "Undetermined")
#   nMeth <- length(genMethod)
#   for (ii in 1:nMeth) {
#     idm <- grep(genMethod[ii], subContra$Method)
#     method[idm] <- methodTransl[ii]
#   }
#   genStatus <- c("Inactive", "Active", "Undetermined", "Indeterminate")
#   statusTransl <- c("Inactive", "Active", "Undetermined", "Undetermined")
#   status <- rep(NA, nContra)
#   for (ii in 1:nMeth) {
#     idm <- grep(genStatus[ii], subContra$Status)
#     status[idm] <- statusTransl[ii]
#   }
#   
#   
#   # Final contraception table:
#   newContra <- data.frame(anonID = as.character(.contraception$` AnonID`)[idIncont],
#                           date = as.Date(.contraception$Date)[idIncont], 
#                           method = method, status = status)
#   
#   if(length(unique(subpar$currentInst))>1){
#     if (fertSumm$NOffsp >= minNrepro) {
#       if (fertSumm$NParent >= minNparepro) {
#         
#         #remove curretn inst to avoid duplicated lines
#         subparfert <- subpar%>%
#           select(-currentInst)%>%
#           distinct()
#         
#         
#         REp_agemat
#         
#         
#       }}}
#   
#   METTRE LES CONDITIONS SUR AU MOINS 2 INSTITUTIION
#   
# }
