# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Run Taxon Profiles
#' 
#' Load data needed and run or update demographic analyses for the list of species selected
#'
#' @param taxa  \code{character} the name of the taxa studied
#' @param Species_list \code{vector of character} Species selected
#' @param ZIMSdir \code{character} directory where to find data
#' @param AnalysisDir \code{character} directory where to save results
#' @param PlotDir \code{character} Directory to save the plots. Default = NULL, no plot is saved
#' @param extractDate \code{character 'YYYY-MM-DD'} Date of data extraction
#' @param minBirthDate  \code{character}: Earlier possible date: date used when minimum birth or death date unknown
#' @param Birth_Type \code{character} Captive, Wild, or All. Default =  "Captive"
#' @param minDate \code{character 'YYYY-MM-DD'} Earlier date to include data
#' @param Sections \code{vector of character} names of the sections to update in the taxon profile results: "sur", "rep" and/or "gro". Default = c("sur", "rep", "gro")
#' @param erase_previous \code{logical} whether the current result file should be deleted (before being replaced). Default = FALSE
#' @param sexCats \code{character} Male, Female or All Default =  "All"
#' @param Global \code{logical} Whether only individuals belonging to global collections should be used.
#' @param inparallel \code{logical} Whether this function is run in parallel on different computer. In other words: should the species list be divided? Default = FALSE
#' @param ipara \code{numeric} Id number of the computer used to select the species to run
#' @param npara \code{numeric} number of computers used in parallel
#' @param minN \code{numeric} Minimum number of individuals. Default = 50
#' @param maxOutl \code{numeric} Maximum threshold for the longevity distribution. Default = NULL
#' @param spOutLev \code{vector of character} List of species for which the Maximum threshold for the longevity distribution.XXXXXXXXXXXXXXXXXXXXXXXXX
#' @param minInstitution \code{numeric} Minimum number of institutions that should hold records to run the analyses. Default = 2
#' @param uncert_birth \code{numeric}: Maximum uncertainty accepted for birth dates, in days
#' @param uncert_death \code{numeric}: Maximum uncertainty accepted for death dates, in days. Default = 365
#' @param uncert_date \code{numeric}: Maximum uncertainty accepted for measurement dates: weight, in days. Default = 365
#' @param minNsur \code{numeric} Minimum number of individuals to run the survival analysis. Default = 50
#' @param maxNsur \code{numeric} Maximum number of individual records to run the survival analysis. Default = NULL
#' @param minlx  \code{numeric} between 0 and 1. Minimum reached survivorship from the raw Kaplan Meier analysis needed to run the survival analysis. Default = 0.1
#' @param MinBirthKnown  \code{numeric} between 0 and 1. Minimum proportion of individuals with a known birth month in the data. Default = 0.3
#' @param XMAX \code{numeric} Maximum possible age. Default = 120
#' @param Min_MLE \code{numeric} Goodness of fit: Minimum survivorship at Mean life expectancy
#' @param MaxLE \code{numeric} Goodness of fit: Maximum remaining life expectancy at max age
#' @param minAge \code{numeric} Ages at which the analyses should start.  see ?basta for more information. Default = 0
#' @param firstyear \code{logical} Whether to do the analysis only on first year. Default = FALSE
#' @param models_sur \code{vector of characters} names of the survival basta models to run: "G0", "EX", "LO" and/or "WE". see ?basta for more information. Default = "GO"
#' @param shape \code{character} shape of the survival basta model to run: "simple", "Makeham", "bathtub".  see ?basta for more information. Default = "simple"
#' @param lastdead  \code{logical} Whether the longest lived individuals should be considered dead. Default = FALSE
#' @param niter  \code{numeric}. number of MCMC iterations to run the survival model. see ?basta for more information. Default = 25000
#' @param burnin  \code{numeric} Number of iterations removed so that the survival model has time to converge. see ?basta for more information. Default = 5001
#' @param thinning  \code{numeric} Number of iteration to run the survival model before saving a set of parameters. see ?basta for more information. Default = 20
#' @param nchain  \code{numeric} Number of chains to run the survival model. Default = 5001
#' @param ncpus  \code{numeric} Number of computer core to use. Default = 2
#' @param Repsect \code{character} names of the reproductive analyses to run: "agemat", "litter" and/or ...
#' @param Nday \code{numeric} Number of consecutive days over which the birth dates of a litter/clutch can be spread. Default = 7
#' @param parentProb_Dam \code{numeric} Minimum percentage of parentage probability to include for Dam. Default = 80
#' @param parentProb_Sire \code{numeric} Minimum percentage of parentage probability to include for Sire. Default = 80
#' @param minNlitter \code{numeric} Minimum number of litters to run the analysis. The data frame for litter size will be produced in all cases. Default = 30
#' @param minNrepro \code{numeric} Minimum number of birth records needed to run reproductive analyses. Default = 50
#' @param minNparepro \code{numeric} Minimum number of unique parent records needed to run reproductive analyses. Default = 30
#' @param minNseas \code{numeric} XXXXXXXXXXX
#' @param minNgro \code{numeric} Minimum number of weight needed to fit the growth models
#' @param minNIgro \code{numeric} Minimum number of unique individuals needed to fit the growth models
#' @param MeasureType \code{vector of characters} Name of the type of measurements that should be included.  Default = NULL, all measurement type are included.
#' @param models_gro \code{vector of characters} indicating the growth models that need to be fit.The following models are supported : logistic, gompertz, chapmanRichards, vonBertalanffy, polynomial. default = "vonBertalanffy"
#'
#' @return Save and replace the result file for each specie sin the list. The file is saved in {analysisDir}\\{taxa}\\{species}.Rdata
#' @export
#'
#' @examples
#' # Here is an example but use directly your own ZIMSdir (directory to find data) 
#' # and analysisDir (directory to save analysis)
#' file = system.file("sci_Animal.csv", package = 'ISRverse')
#' ZIMSdir = dirname(file)
#' AnalysisDir = paste0(tempdir(check = TRUE),'\\temp')
#' PlotDir = paste0(tempdir(check = TRUE),'\\temp\\plot')
#' dir.create(AnalysisDir)
#' dir.create(paste0(tempdir(check = TRUE),'\\temp\\Rdata'))
#' dir.create(PlotDir)
#'
#' #This code run the survival analysis
#' run_txprofile(taxa = "Reptilia", Species_list = "All",
#'               ZIMSdir = ZIMSdir, AnalysisDir = AnalysisDir,
#'               PlotDir = PlotDir,
#'               extractDate = "",
#'               minDate = "1980-01-01",
#'               Sections = c("sur"),
#'               sexCats = c('Male', 'Female'),
#'               niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3
#' )
#'
#' list.files(PlotDir)
#' list.files(paste0(AnalysisDir,'\\temp\\Rdata'))
#'
#' unlink(AnalysisDir, recursive = TRUE)
#' unlink(PlotDir, recursive = TRUE)
#'
run_txprofile <- function(taxa, Species_list, ZIMSdir, 
                          AnalysisDir, PlotDir,
                          extractDate, minDate = "1980-01-01",
                          Sections, erase_previous = FALSE,
                          sexCats = c('Male', 'Female'), minBirthDate = "1900-01-01",
                          inparallel = FALSE, ipara = 1, npara = 1, 
                          minN= 50,  maxOutl =99,  spOutLev = NULL, Global = TRUE,
                          uncert_birth = 365,  uncert_death = 365,  uncert_date = 365, 
                          minNsur = 50, maxNsur = NULL, minInstitution = 2,
                          minlx = 0.1, MinBirthKnown = 0.3, XMAX =120,
                          Min_MLE = 0.1, MaxLE = 2, minAge = 0,firstyear =FALSE,
                          models_sur = "GO", shape = "bathtub",
                          niter = 25000, burnin = 5001, thinning = 20, 
                          nchain = 3, ncpus = 2,
                          Repsect = c('agemat', 'litter'),
                          Birth_Type = "Captive", lastdead = FALSE,
                          parentProb_Sire = 80, parentProb_Dam = 80, minNlitter = 20,Nday = 7,
                          minNrepro = 100, minNparepro = 30, minNseas = 50, 
                          minNgro =100,minNIgro = 50, MeasureType = "Live weight",
                          models_gro = "vonBertalanffy"
                          
){
  
  assert_that(is.character(taxa))
  assert_that(is.character(Sections))
  assert_that(all(Sections %in% c("sur", "gro", "rep")))
  assert_that(is.character(Species_list))
  assert_that(is.logical(Global))
  minDate = lubridate::as_date(minDate)
  extractDate = lubridate::as_date(extractDate)
  assert_that(Birth_Type %in% c("Captive", "Wild", "All"))
  assert_that(is.logical( erase_previous))
  assert_that(is.logical(inparallel))
  assert_that(is.numeric( ipara))
  assert_that(is.numeric( npara))
  assert_that(ipara <= npara)
  assert_that(is.numeric( maxOutl))
  assert_that(is.numeric(minAge))
  assert_that(minAge>=0)
  assert_that(is.logical(firstyear))
  assert_that( maxOutl <= 100)
  assert_that(is.numeric(uncert_birth))
  assert_that(is.numeric(uncert_death))
  assert_that(is.numeric(uncert_date))
  assert_that(is.double(minInstitution))
  assert_that(is.numeric(Min_MLE))
  assert_that(is.numeric(MaxLE))
  assert_that(is.numeric(minNsur))
  assert_that(minNsur > 0)
  if(!is.null(maxNsur)) assert_that(is.numeric(maxNsur))
  assert_that(is.numeric(minlx))
  assert_that(minlx > 0)
  assert_that(minlx < 1)
  assert_that(is.numeric(MinBirthKnown))
  assert_that(MinBirthKnown >= 0)
  assert_that(MinBirthKnown <1)
  assert_that(is.numeric(niter))
  assert_that(niter > 0)
  assert_that(is.numeric(burnin))
  assert_that(burnin > 0)
  assert_that(burnin < niter)
  assert_that(is.numeric(thinning))
  assert_that(thinning > 0)
  assert_that(thinning < niter)
  assert_that(is.numeric(nchain))
  assert_that(nchain > 0)
  assert_that(is.numeric(ncpus))
  assert_that(ncpus > 0)
  assert_that(is.character(models_sur))
  assert_that(all(models_sur %in% c("GO", "EX", "LO", "WE")))
  assert_that(is.character(shape))
  assert_that(all(shape %in% c("simple", "bathtub", "Makeham")))
  assert_directory_exists(ZIMSdir)
  assert_directory_exists(AnalysisDir)
  assert_directory_exists(PlotDir)
  
  assert_that(all(Repsect %in% c("agemat", "litter")))
  assert_that(is.numeric(parentProb_Dam))
  assert_that(parentProb_Dam > 0)
  assert_that(is.numeric(parentProb_Sire))
  assert_that(parentProb_Sire > 0)
  assert_that(is.numeric(minNrepro))
  assert_that(minNrepro > 0)
  assert_that(is.numeric(minNparepro))
  assert_that(minNparepro > 0)
  assert_that(is.numeric(minNlitter))
  assert_that(minNlitter > 0)
  assert_that(is.numeric( minNseas))
  assert_that( minNseas > 0)
  assert_that(is.numeric( Nday))
  assert_that( Nday >= 0)
  
  assert_that(is.numeric( minNIgro))
  assert_that( minNIgro > 0)
  assert_that(is.numeric(minNgro))
  assert_that(minNgro > 0)
  assert_that(is.character(MeasureType))
  assert_that(is.character(models_gro ))
  assert_that(all(models_gro %in% c("logistic", "gompertz", "chapmanRichards", "vonBertalanffy", "polynomial", "gam")), msg = "The growth models supported are: logistic, gompertz, chapmanRichards, vonBertalanffy, and polynomial, in addition to GAM.")
  
  assert_that(is.character( sexCats))
  assert_that(all(sexCats %in% c("Male", "Female", "All")))
  
  
  
  # ======================#
  # ==== Load data ========
  # ======================#
  cat("Loading Data\n")
  tables = c("Collection")
  if("sur" %in% Sections){
    tables = c(tables, "DeathInformation")
  }
  if("gro" %in% Sections){
    tables = c(tables, "Weight")
  }
  if("rep" %in% Sections){
    tables = c(tables, "Parent", "Contraception", "Move")
  }
  species_list = list()
  species_list [[taxa]] = Species_list
  data <- Load_Zimsdata	(taxa = taxa, ZIMSdir = ZIMSdir, 
                         species = species_list,
                         Animal = TRUE,
                         tables = tables,
                         silent = TRUE) 
  
  # ======================#
  # ==== Species List =====
  # ======================#
  if(all(Species_list == "All")){
    spAll <- unique(data[[taxa]]$Animal$binSpecies)%>%
      stringr::str_subset(pattern = ' sp.', negate = TRUE)
  }else{
    spAll <-Species_list
  }
  if (inparallel){
    # IDs of species to run per version:
    idsprun <- seq(ipara, length(spAll), by = npara)
  }else{
    idsprun <- c(1:length(spAll))}
  
  # ======================#
  # ==== RUN ANALYSES: ====
  # ======================#
  core <- Prep_Animal(data[[taxa]]$Animal, extractDate= extractDate,minBirthDate =minBirthDate )
  # #subset Tables
  if("sur" %in% Sections){
    DeathInformation <- data[[taxa]]$DeathInformation
  }else{DeathInformation <- NULL}
  if("gro" %in% Sections){
    weights = data[[taxa]]$Weight
  }else{
    weights <-NULL
  }
  if("rep" %in% Sections){
    parents = data[[taxa]]$Parent
    move = data[[taxa]]$Move
    contraceptions = data[[taxa]]$Contraception
  }else{
    parents =contraceptions = move = NULL
  }
  
  # Start counter:
  icount <- 0
  
  # Loop over species
  for (isp in idsprun) {
    # Extract species:
    species <- spAll[isp]
    
    # # progress count:
    icount <- icount + 1
    
    
    # Report progress:
    cat("\n====================\nClass:   ", taxa, "\nSpecies: ", species, 
        "\nProgress:", round(icount / length(idsprun) * 100, 0), 
        "%\n=====================\n")
    cat("Species running...\n ")
    
    speciesname = stringr::str_replace(species, " ", "_")
    
    #Load previous taxon profile to update it
    if(erase_previous){
      repout = list()
    }else{
      if(length(list.files(glue::glue("{AnalysisDir}Rdata/"), glue::glue("{taxa}_{speciesname}.RData")))>0){
        load(glue::glue("{AnalysisDir}Rdata/{taxa}_{speciesname}.RData"))
      }else{repout = list()}
    }
    if (species %in% spOutLev) {maxOutl1 <- 99.9
    }else{maxOutl1 <- maxOutl}
    
    
    # Create report:
    repout <- tx_report(species, taxa, 
                        Animal =  core, collection = data[[taxa]]$Collection, 
                        DeathInformation = DeathInformation,
                        PlotDir = PlotDir, extractDate= extractDate, minBirthDate = minBirthDate,
                        weights = weights, parents = parents, contraceptions = contraceptions, move = move,
                        repout = repout, Sections = Sections, Birth_Type = Birth_Type,
                        sexCats = sexCats, minN= minN, minDate= minDate, Global = Global,
                        uncert_birth = uncert_birth, uncert_death= uncert_death,
                        uncert_date = uncert_date,minAge =minAge,firstyear = firstyear,
                        maxOutl = maxOutl1, minlx = minlx, minInstitution = minInstitution,
                        minNsur = minNsur, maxNsur = maxNsur, MinBirthKnown = MinBirthKnown,
                        Min_MLE = Min_MLE, MaxLE =  MaxLE,XMAX = XMAX,
                        models_sur = models_sur, shape = shape,lastdead = lastdead,
                        niter = niter, burnin =  burnin, thinning = thinning,
                        nchain = nchain,  ncpus = ncpus,
                        Repsect = Repsect, parentProb_Dam = parentProb_Dam,
                        parentProb_Sire = parentProb_Sire, minNrepro = minNrepro,
                        minNlitter = minNlitter, Nday = Nday,
                        minNparepro = minNparepro, minNseas = minNseas, 
                        minNgro =minNgro,minNIgro = minNIgro, 
                        MeasureType = MeasureType, models_gro = models_gro
    )
    
    # ----------------------- #
    # ---- Save results: ----
    # ----------------------- #
    # Save species list:
    save("repout", file = glue::glue("{AnalysisDir}/Rdata/{taxa}_{speciesname}.RData"))
    cat(" done.\n")
  }
}

