# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Run Taxon Profiles
#' 
#' Load data needed and run or update demographic analyses for the list of species selected
#'
#' @param taxa  \code{character} the name of the taxa studied
#' @param Species_list \code{vector of character} Species selected
#' @param ZIMSdir \code{character} directory where to find data
#' @param AnalysisDir \code{character} directory where to save results
#' @param PlotDir \code{character} Directory to save the plots. Default = NULL, no plot is saved
#' @param extractDate \code{character 'YYYY-MM-DD'} Date of data extraction
#' @param minDate \code{character 'YYYY-MM-DD'} Earlier date to include data
#' @param Sections \code{vector of character} names of the sections to update in the taxon profile results: "sur", "rep" and/or "gro". Default = c("sur", "rep", "gro")
#' @param erase_previous \code{logical} whether the current result file should be deleted (before being replaced). Default = FALSE
#' @param sexCats \code{character} Male, Female or All Default =  "All"
#' @param inparallel \code{logical} Whether this function is run in parallel on different computer. In other words: should the species list be divided? Default = FALSE
#' @param ipara \code{numeric} Id number of the computer used to select the species to run
#' @param npara \code{numeric} number of computers used in parallel
#' @param minN \code{numeric} Minimum number of individuals. Default = 50
#' @param maxOutl \code{numeric} Maximum threshold for the longevity distribution. Default = NULL
#' @param spOutLev \code{vector of character} List of species for which the Maximum threshold for the longevity distribution.XXXXXXXXXXXXXXXXXXXXXXXXX
#' @param minNsur \code{numeric} Minimum number of individuals to run the survival analysis. Default = 50
#' @param minlx  \code{numeric} between 0 and 1. Minimum reached survivorship from the raw Kaplan Meier analysis needed to run the survival analysis. Default = 0.1
#' @param MinBirthKnown  \code{numeric} between 0 and 1. Minimum proportion of individuals with a known birth month in the data. Default = 0.3
#' @param models_sur \code{vector of characters} names of the survival basta models to run: "G0", "EX", "LO" and/or "WE". see ?basta for more information. Default = "GO"
#' @param shape \code{character} shape of the survival basta model to run: "simple", "Makeham", "bathtub".  see ?basta for more information. Default = "simple"
#' @param niter  \code{numeric}. number of MCMC iterations to run the survival model. see ?basta for more information. Default = 25000
#' @param burnin  \code{numeric} Number of iterations removed so that the survival model has time to converge. see ?basta for more information. Default = 5001
#' @param thinning  \code{numeric} Number of iteration to run the survival model before saving a set of parameters. see ?basta for more information. Default = 20
#' @param nchain  \code{numeric} Number of chains to run the survival model. Default = 5001
#' @param ncpus  \code{numeric} Number of computer core to use. Default = 2
#' @param parentProb \code{numeric} XXXXXXXXXXX
#' @param minNrepro  \code{numeric} XXXXXXXXXXX
#' @param minNparepro  \code{numeric} XXXXXXXXXXX
#' @param minNseas \code{numeric} XXXXXXXXXXX
#' @param minNgro \code{numeric} Minimum number of weight needed to fit the growth models
#' @param minNIgro \code{numeric} Minimum number of unique individuals needed to fit the growth models
#' @param MeasureType \code{vector of characters} Name of the type of measurements that should be included.  Default = NULL, all measurement type are included.
#' @param models_gro \code{vector of characters} indicating the growth models that need to be fit.The following models are supported : logistic, gompertz, chapmanRichards, vonBertalanffy, polynomial. default = "vonBertalanffy"
#'
#' @return Save and replace the result file for each specie sin the list. The file is saved in {analysisDir}\\{taxa}\\{species}.Rdata
#' @export
#'
#' @examples
#' # # Here is an example but use directly your own ZIMSdir(directory to find data) and analysisDir(directory to save analysis)
#' # file = system.file("coretest.csv", package = 'ISRverse')
#' # ZIMSdir = dirname(file)
#' # AnalysisDir = paste0(tempdir(check = TRUE),'\\temp')
#' # PlotDir = paste0(tempdir(check = TRUE),'\\temp\\plot')
#' # dir.create(AnalysisDir)
#' # dir.create(PlotDir)
#' # 
#' # #This code run the survival analysis for gorilla
#' # out <- run_txprofile(taxa = "Mammalia", Species_list = c('Gorilla gorilla'), 
#' #                           ZIMSdir = RastDir, AnalysisDir = AnalysisDir,
#' #                           PlotDir = PlotDir,
#' #                           extractDate = "", 
#' #                           minDate = "1980-01-01",
#' #                           Sections = "sur", 
#' #                           sexCats = c('Male', 'Female'),
#' #                          niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3
#' # )
#' # 
#' # list.files(PlotDir)
#' # list.files(AnalysisDir)
#' # 
#' # unlink(AnalysisDir, recursive = TRUE)
#'
#'
#' \dontrun{
#' # Here is an example but use directly your own ZIMSdir(directory to find data) and analysisDir(directory #' to save analysis)
#' file = system.file("coretest.csv", package = 'ISRverse')
#' ZIMSdir = dirname(file)
#' analysisDir = paste0(tempdir(check = TRUE),'\\temp')
#' PlotDir = paste0(tempdir(check = TRUE),'\\temp\\plot')
#' dir.create(analysisDir)
#' dir.create(PlotDir)
#' 
#' #Here I want to split my analysis on two computers
#' #Run on computer 1:
#' out <- run_txprofile(taxa = "Mammalia", Species_list = c('Gorilla gorilla', "Capreolus capreolus"), 
#'                           ZIMSdir = RastDir, analysisDir = analysisDir,
#'                          PlotDir = PlotDir,
#'                        extractDate = "", 
#'                           minDate = "1980-01-01",
#'                           Sections = "sur", 
#'                           sexCats = c('Male', 'Female'), 
#'                           inparallel = TRUE, 
#'                           ipara = 1, npara = 2
#' )
#' 
#' 
#' #Run on computer 2:
#' out <- run_txprofile(taxa = "Mammalia", Species_list = c('Gorilla gorilla', "Capreolus capreolus"), 
#'                           ZIMSdir = RastDir, analysisDir = analysisDir,
#'                           PlotDir = PlotDir,
#'                       extractDate = "", 
#'                           minDate = "1980-01-01",
#'                           Sections = "sur", 
#'                           sexCats = c('Male', 'Female'), 
#'                           inparallel = TRUE,
#'                            ipara = 2, npara = 2
#' )
#' list.files(PlotDir)
#' list.files(AnalysisDir)
#'
#' unlink(analysisDir, recursive = TRUE)
#' }
run_txprofile <- function(taxa, Species_list, ZIMSdir, 
                          AnalysisDir, PlotDir,
                          extractDate, minDate = "1980-01-01",
                          Sections, erase_previous = FALSE,
                          sexCats = c('Male', 'Female'), 
                          inparallel = FALSE, ipara = 1, npara = 1, 
                          minN= 50,  maxOutl =99,  spOutLev = NULL,
                          minNsur = 50, minlx = 0.1, MinBirthKnown = 0.3, 
                          models_sur = "GO", shape = "bathub",
                          niter = 25000, burnin = 5001, thinning = 20, 
                          nchain = 3, ncpus = 2,
                          parentProb = 80, minNrepro = 100, 
                          minNparepro = 30, minNseas = 50, 
                          minNgro =100,minNIgro = 50, MeasureType = "",
                          models_gro = "vonBertalanffy"
                          
){
  
  assert_that(is.character(taxa))
  assert_that(taxa %in% c("Mammalia", "Aves", "Reptilia", "Amphibia", 
                          "Chondrichthyes", "Actinopterygii"),
              msg = "taxa must one of 'Mammalia', 'Aves', 'Reptilia', 'Amphibia', 
                          'Chondrichthyes', or 'Actinopterygii'")
  assert_that(is.character(Sections))
  assert_that(all(Sections %in% c("sur", "gro", "rep")))
  assert_that(is.character(Species_list))
  minDate = lubridate::as_date(minDate)
  extractDate = lubridate::as_date(extractDate)
  assert_that(is.logical( erase_previous))
  assert_that(is.logical(inparallel))
  assert_that(is.numeric( iparal))
  assert_that(is.numeric( npara))
  assert_that(ipara <= npara)
  assert_that(is.numeric( maxOutl))
  assert_that( maxOutl <= 100)
  assert_that(is.numeric(minNsur))
  assert_that(minNsur > 0)
  assert_that(is.numeric(minlx))
  assert_that(minlx > 0)
  assert_that(minlx < 1)
  assert_that(is.numeric(MinBirthKnown))
  assert_that(MinBirthKnown > 0)
  assert_that(MinBirthKnown <1)
  assert_that(is.numeric(niter))
  assert_that(niter > 0)
  assert_that(is.numeric(burnin))
  assert_that(burnin > 0)
  assert_that(burnin < niter)
  assert_that(is.numeric(thinning))
  assert_that(thinning > 0)
  assert_that(thinning < niter)
  assert_that(is.numeric(nchain))
  assert_that(nchain > 0)
  assert_that(is.numeric(ncpus))
  assert_that(ncpus > 0)
  assert_that(is.character(models_sur))
  assert_that(all(models_sur %in% c("GO", "EX", "LO", "WE")))
  assert_that(is.character(shape))
  assert_that(all(shape %in% c("simple", "bathtub", "Makeham")))
  assert_directory_exists(ZIMSdir)
  assert_directory_exists(AnalysisDir)
   assert_directory_exists(PlotDir)
 
  assert_that(is.numeric(parentProb))
  assert_that(parentProb > 0)
  assert_that(is.numeric(minNrepro))
  assert_that(minNrepro > 0)
  assert_that(is.numeric(minNparepro))
  assert_that(minNparepro > 0)
  assert_that(is.numeric( minNseas))
  assert_that( minNseas > 0)
  
  assert_that(is.numeric( minNIgro))
  assert_that( minNIgro > 0)
  assert_that(is.numeric(minNgro))
  assert_that(minNgro > 0)
  assert_that(is.character(MeasureType))
  assert_that(is.character(models_gro ))
  assert_that(all(models_gro %in% c("logistic", "gompertz", "chapmanRichards", "vonBertalanffy", "polynomial", "gam")), msg = "The growth models supported are: logistic, gompertz, chapmanRichards, vonBertalanffy, and polynomial, in addition to GAM.")
  
  assert_that(is.character( sexCats))
   assert_that(all(sexCats %in% c("Male", "Female", "All")))
  
  
  
  # ======================#
  # ==== Load data ========
  # ======================#
  tables = c( "core", "collections")
  if("gro" %in% Sections){
    tables = c(tables, "weights")
  }
  if("rep" %in% Sections){
    tables = c(tables, "parents", "contraception")
  }
  Load_Zimsdata	(taxa = taxa, ZIMSdir = ZIMSdir, 
                 extractDate, 
                 type = tables,
                 silent = TRUE) 
  
  # ======================#
  # ==== Species List =====
  # ======================#
  if( Species_list == "All"){
    spAll <- unique(core$binSpecies)
  }
  if (inparallel){
    # IDs of species to run per version:
    idsprun <- seq(ipara, length(spAll), by = npara)
  }else{
    idsprun <- c(1:length(spAll))}
  
  # ======================#
  # ==== RUN ANALYSES: ====
  # ======================#
  # Start counter:
  icount <- 0
  
  # Loop over species
  for (isp in idsprun) {
    # Extract species:
    species <- spAll[isp]
    
    # # progress count:
    icount <- icount + 1
    
    #subset Tables
    if("gro" %in% Sections){
      weight_spe <- weights%>%
        filter(binSpecies == "species")
    }else{
      weight_spe <-NULL
    }
    if("rep" %in% Sections){
      contra_spe <- contraceptions%>%
        filter(binSpecies == "species")
      parent_spe <- parents()%>%
        filter(binSpecies == "species")
    }else{
      parent_spe <- contra_spe <-NULL
    }
    
    # Report progress:
    cat("\n====================\nClass:   ", taxa, "\nSpecies: ", species, 
        "\nProgress:", round(icount / length(idsprun) * 100, 0), 
        "%\n=====================\n")
    cat("Species running... ")
    
    #Load previous taxon profile to update it
    if(erase_previous){
      Repout = list()
    }else{
      if(any( stringr::str_detect(list.files("ISRdata/global/rdata/", species)))){
        load(glue::glue("ISRdata/global/rdata/{species}.RData"))
      }else{Repout = list()}
    }
    maxOutl= NULL
    if (species %in% spOutLev) maxOutl <- 99.9
    
    
    # Create report:
    repout <- tx_report(species, taxa, 
                        coresubset, collection, 
                        PlotDir = PlotDir, extractDate= extractDate,
                        weights = weight_spe, parents = parent_spe, contraceptions = contra_spe,
                        repout = repout, Sections = Sections,
                        sexCats = sexCats, minN= minN, minDate= minDate, 
                        maxOutl = maxOutl, minlx = minlx, 
                        minNsur = minNsur, MinBirthKnown = MinBirthKnown,
                        models_sur = models_sur, shape = shape,
                        niter = niter, burnin =  burnin, thinning = thinning,
                        nchain = nchain,  ncpus = ncpus,
                        parentProb = parentProb, minNrepro = minNrepro,
                        minNparepro = minNparepro, minNseas = minNseas, 
                        minNgro =minNgro,minNIgro = minNIgro, 
                        MeasureType = MeasureType, models_gro = models_gro
    )
    
    # ----------------------- #
    # ---- Save results: ----
    # ----------------------- #
    # Save species list:
    save("repout", file = glue::glue("{analysisDir}/{species}.RData"))
    cat(" done.\n")
  }
}

