# WARNING - Generated by {fusen} from dev/flat_select.Rmd: do not edit by hand

#' Extract data
#' 
#' Extract data of the specified species that fill the condition on minimum date and global collections
#'
#' @param speciesname \code{character} latin name of the species selected
#' @param coresubset  \code{data.frame} including at least the following columns *AnimalAnonID*, *binSpecies*, *BirthDate* (\code{date}), *DepartDate* (\code{date}), *EntryDate* (\code{date}), *MaxBirthDate* (\code{date}), *MinBirthDate* (\code{date}), *MaxDeathDate* (\code{date}), *MinDeathDate* (\code{date}), *EntryType*, *DepartType*,  *LastTXDate*, *DeathDate*, *FirstHoldingInstitution*, *LastHoldingInstitution*, *GlobalStatus*, *LastCollectionScopeType*, and *FirstCollectionScopeType*
#' @param collection \code{data.frame} including at least the following columns*RecordingInstitution*, *ChangeDate*, *ScopeType*, and *AnimalAnonID*.
#' @param minDate \code{character 'YYYY-MM-DD'} Earlier date to include data
#' @param uncert_birth \code{numeric}: Maximum uncertainty accepted for birth dates, in days
#' @param Birth_Type \code{character} Captive, Wild, or All. Default =  "Captive"
#' @param extractDate \code{character 'YYYY-MM-DD'} Date of data extraction
#' @param Global \code{logical} Whether only individuals belonging to global collections should be used.
#' @param na_birthdate \code{logical} Whether lines with unknown birth date should be kept.
#'
#' @return The output of a list including:
#' * a summary of the data used:
#'- Nraw : Raw number of individuals selected from global collections
#'- Ndate : Number of individuals with an entry date posterior to the minimum date
#'- Nglobal: Number of individuals selected from global collections
#'- Nbirthtype: Number of individuals selected from birth type
#'- Nuncertbirth: Number of individuals selected from uncertainty in birth
#'- Nalive: Number of individuals still alive
#'- firstDate: Date of first record
#'- maxAgeraw: Maximum observed age
#'* The subseted dataset
#' @export
#'
#' @examples
#' data(core)
#' data(collection)
#' out<- select_species(speciesname = "Testudo hermanni", coresubset = core, collection,
#'                      minDate = "1980-01-01", extractDate = "2023-01-01")
#' out$summary
#' out$data
select_species <- function(speciesname, coresubset, collection, uncert_birth = 365,                                     Birth_Type = "Captive",
                           minDate, extractDate, Global = TRUE, na_birthdate = FALSE) {
  
  minDate = lubridate::as_date(minDate)
  extractDate = lubridate::as_date(extractDate)
  assert_that(Birth_Type %in% c("Captive", "Wild", "All"))
  assert_that(is.numeric(uncert_birth))
  assert_that(is.data.frame(coresubset))
  assert_that(is.data.frame(collection))
  assert_that(coresubset  %has_name% c("AnimalAnonID", "binSpecies", "BirthDate", "DepartDate",
                                       "EntryDate", "MaxBirthDate", "MinBirthDate",
                                       "MaxDeathDate", "MinDeathDate", "EntryType", "DepartType",
                                       "LastTXDate", "DeathDate", "FirstHoldingInstitution", 
                                       "LastHoldingInstitution","GlobalStatus",
                                       "LastCollectionScopeType","FirstCollectionScopeType"))
  assert_that(collection  %has_name% c("RecordingInstitution", "ChangeDate", 
                                       "ScopeType", "AnimalAnonID"))
  assert_that(is.logical(Global))
  # Select Species
  coresubset0 <- coresubset%>%
    filter(binSpecies == speciesname)
  
  # Subset by min date
  coresubset1 <- coresubset0%>%
    filter(DepartDate >= minDate)
  
  
  summar = list(Nraw = nrow(coresubset0),
                Ndate = nrow(coresubset1),
                Nglobal = 0,
                Nbirthtype = 0,
                Nuncertbirth = 0,
                Nalive = 0,
                firstDate = NULL,
                maxAgeraw = NULL,
                extractdate = extractDate)
  
  if(summar$Ndate>0){
    if(Global){
      # Keep only Global individuals
      indglobloc = coresubset1%>%
        filter(LastCollectionScopeType == "Local",
               FirstCollectionScopeType == "Global"
        )
      if(nrow(indglobloc)>0){
        indglobloc = indglobloc%>%
          left_join(collection%>%
                      select(RecordingInstitution, ChangeDate, ScopeType, AnimalAnonID),
                    by = c("AnimalAnonID"))%>%
          group_by(AnimalAnonID, ScopeType)%>%
          mutate(maxtime = max(ChangeDate)) %>%
          ungroup()%>%
          filter(maxtime  == ChangeDate)
        #Warnings: there are sometimes 2 institutions for 1 individual for same date  ###!!! THIS SHOULD NOT HAPPEN
        indloc<-indglobloc%>%
          filter(ScopeType=="Local")%>%
          select(-RecordingInstitution)%>%
          left_join(indglobloc%>%
                      filter(ScopeType=="Global")%>%
                      select(AnimalAnonID, RecordingInstitution)%>%
                      group_by(AnimalAnonID )%>%
                      summarise(RecordingInstitution = min(RecordingInstitution)),  ###!!! TO BE CHANGED
                    by = "AnimalAnonID")%>%
          mutate(globStat ="Undetermined (Lost to follow up)",
                 lastInst = as.character(RecordingInstitution),
                 LastCollectionScopeType = "now Global",
                 DepartType = "C",
                 DepartFrom = "collections",
                 DeathDate = lubridate::as_date(NA),
                 LastTXDate = lubridate::as_date(ChangeDate),
                 DepartDate = lubridate::as_date(ChangeDate))%>%
          select(-ChangeDate, -ScopeType,-maxtime, -RecordingInstitution )%>%
          distinct()
      }else{indloc<-indglobloc}
      
      
      
      
      data_sel <- coresubset1%>%
        rows_update(indloc, by="AnimalAnonID")%>%
        mutate()%>%
        filter(FirstCollectionScopeType == "Global")
      summar$Nglobal = nrow(data_sel)
    }else { data_sel <- coresubset1}
    
    
    if (summar$Nglobal > 0) {  
       # Subset by birth type
      if (Birth_Type != "All"){
        data_sel <- data_sel  %>%
          filter(stringr::str_detect(BirthType, pattern = Birth_Type))
      }
      summar$Nbirthtype = nrow( data_sel)
      
      if(!na_birthdate){
      # Subset by uncertainty in birth
      data_sel <- data_sel %>%
        tidyr::drop_na(BirthDate)}
      
      if(nrow(data_sel)>0){
       data_sel1 <- data_sel %>%
        filter((Birth_Uncertainty <= uncert_birth)%>% replace_na(TRUE))
      summar$Nuncertbirth = nrow( data_sel1)
      
          if(nrow(data_sel1)>0){
         # Number alive by extraction date:
      summar$Nalive <- nrow(data_sel1%>%
                              filter(DepartDate == extractDate , 
                                     DepartType == "C"))
      
      # First record:
      summar$firstDate <- min(data_sel1$EntryDate)
 # Max Ages:
      data_age <- data_sel1%>%
        mutate(tempAges = as.numeric(DepartDate - BirthDate) / 365.25,
               tempAlive = as.numeric(DepartDate - EntryDate) / 365.25)
      
      
      summar$maxAgeraw <- max(c(data_age$tempAges,data_age$tempAlive))
        } 
      }else{data_sel1 = tibble()}
    }else{data_sel1 = tibble()}
    
  }else{data_sel1 = tibble()}
  
  
  sexDat <- list(summary = summar, data = data_sel1)
  
  return(sexDat)
}
