# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Split raw extracted data
#' 
#' Check Data and split tables per taxa
#'
#' @param ZIMSdir \code{character} directory where to find data
#' @param extractDate \code{character} Extraction Date
#' @param silent \code{logical} Whether information of advancement should be printed
#' 
#' @return A list of the data frames
#' 
#' @importFrom glue glue
#' @importFrom readr write_delim
#' @importFrom stringr str_remove str_detect
#' @importFrom checkmate assert_directory_exists
#' @export
#'
#' @examples
#'
#' file = system.file("sci_Animal.csv", package = "ISRverse")
#' ZIMSdirtest = dirname(file)
#'
#' Split_Zimsdata(ZIMSdir = ZIMSdirtest)
#'
#' list.files(ZIMSdirtest, recursive = TRUE)
Split_Zimsdata	<- function (ZIMSdir,
                            extractDate = NULL,
                            silent = FALSE) 
{ 
  checkmate::assert_directory_exists(ZIMSdir)
  assert_that(is.logical( silent))
  if(!is.null(extractDate)){
    extractDate = lubridate::date(extractDate)
  }else{extractDate = ""}
  
  idfiles <- list.files(ZIMSdir, "sci_")
  idfilesAni <- list.files(ZIMSdir, "Animal.csv")
  idfiles = str_subset(idfiles, pattern = "Animal.csv", negate = TRUE)
  
  
  #Load Animal File
  assert_that(length(idfilesAni)> 0,
              msg =glue::glue("Animal file not found.")
  )
  assert_that(length(idfilesAni) < 2,
              msg = glue::glue("More than one Animal file.")
  )
  if (!silent) {
    cat(glue::glue("Splitting Animal file.\n"))
  }
  Ani <- read.csv(glue::glue("{ZIMSdir}/{idfilesAni}"), sep = "@",  header = T, skipNul = TRUE)
  Ani <- Ani%>%filter(AnimalType == "Individual")
  
  temp= stringr::str_split(Ani$SpeciesName, " ", simplify = T)
  temp2 = temp[,2]
  temp[,2][temp2 == ""] = "sp."
  Ani$binSpecies = stringr::str_c(temp[,1], temp[,2], sep = " ")
  taxaList = unique(Ani$Class)
  
  #split Animal data and create sub_directory
  for (taxa in taxaList){
    dir.create(path = glue::glue("{ZIMSdir}/Split_{taxa}/"), showWarnings = FALSE)

    
    Ani_taxa = Ani%>% filter(Class == taxa)
    write_delim(Ani_taxa, file = glue::glue("{ZIMSdir}/Split_{taxa}/{taxa}{extractDate}_Animal.csv"), delim = "@")
  }
  
  
  #Split all other files
  for (file in idfiles){
    if (!silent) {
      cat(glue::glue("Splitting {file}.\n"))
    }
    name = str_remove(file, "sci_")
    fi <- read.csv(glue::glue("{ZIMSdir}/{file}"), sep = "@",  header = T, skipNul = TRUE)
    
    for (taxa in taxaList){
      fi_taxa = fi
      Ani_taxa = Ani%>% filter(Class == taxa)
      if("AnimalAnonID" %in% names(fi)){
        fi_taxa <- fi_taxa %>% filter(AnimalAnonID %in% Ani_taxa$AnimalAnonID)}
      if("InstitutionAnonID" %in% names(fi)){
        fi_taxa <- fi_taxa %>% filter(InstitutionAnonID %in% Ani_taxa$InstitutionAnonID)}
      
      if (name == "AnimalWeight.csv"){
        fi_taxa <-fi_taxa%>%
          filter(WeightValueKg>0)%>%
          rename(MeasurementValue = WeightValueKg)%>%
          mutate(Age = AnimalAgeDays/365,
                 UnitOfMeasure = "kg")
      }
      if (name == "AnimalLength.csv"){
        fi_taxa <-fi_taxa%>%
          filter(LengthValueCm>0)%>%
          rename(MeasurementValue = LengthValueCm)%>%
          mutate(Age = AnimalAgeDays/365,
                 UnitOfMeasure = "cm")
      }
      write_delim(fi_taxa,
                  file = glue::glue("{ZIMSdir}/Split_{taxa}/{taxa}{extractDate}_{name}"), 
                  delim = "@")
    }
  }
  
  if (!silent) {
    cat(" Done.\n")
  }
}
