# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

#' Estimate raw survivorship from life table
#' 
#' @param sexData \code{data.frame} including at least the following columns *deparAge*, *entryAge* (\code{date}), and *DepartType* 
#'
#' @return A data frame including 3 colummns:
#' * Ages: the different ages
#' * Surv: survivorship
#' * event = 1 if the individual was dead at this age 
#' vs. 0 is the individual was left-censored at this age
#' 
#' @export
#'
#' @examples

# Product limit estimator:
#' entryAge = sample(c(1:10), 200, replace = TRUE)
#' data <- data.frame(
#'   entryAge = entryAge,
#'   deparAge =  entryAge + sample(c(0:10), 200, replace = TRUE),
#'   DepartType = sample(c('C', 'D'), 200, replace = TRUE))
#'
#'
#' out<-Sur_ple(data)
Sur_ple <- function(sexData) {
  assert_that(is.data.frame(sexData))
  assert_that(sexData %has_name% c("deparAge", "DepartType", "entryAge"))
  # Find records with same first and last age:
  sexData <- sexData%>%
    rowwise()%>%
    mutate(idsame = entryAge == deparAge,
           deparAge = ifelse(idsame, deparAge + 1/365.25, deparAge))%>%
    arrange(deparAge)
  
  # Number of ages:
  nage <- nrow(sexData)
  
  # Cx and delta:
  Cx <- rep(0, nage)
  delx <- rep(0, nage)
  
  # Fill up Cx and delta:
  for (ii in 1:nage) {
    agev = sexData$deparAge[ii]
    idNx <-sexData %>%filter(entryAge <= agev,
                             deparAge >= agev)
    Cx[ii] <- nrow(idNx) / nage
    if (sexData$DepartType[ii] == "D") delx[ii] <- 1
  }
  
  # Calculate product limit estimator:
  ple <- cumprod((1 - 1 / (nage * Cx))^delx)
  ple[ple<0]=0
  
  # Add age 0:
  Ages <- sexData$deparAge
  if (Ages[1] > 0) {
    Ages <- c(0, Ages)
    ple <- c(1, ple)
    delx<- c(0, delx)
  }
  
  # Output:
  pleTab <- data.frame(Ages = Ages, ple = ple, event = delx)
  
  return(pleTab)
}

