# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

#' Maximum Longevity
#' 
#' Estimate Lxx: age at which xx% of the population is still alive
#' 
#' @param theMat \code{array} including the posteriors estimates of the model parameter
#' @param model \code{character} names of the basta models to run: "G0", "EX", "LO" and/or "WE". see ?basta for more information. Default = "GO"
#' @param shape \code{character} shape of the basta model: "simple", "Makeham", "bathtub".  see ?basta for more information. Default = "simple"
#' @param xx  \code{numeric} % of the population still alive
#' @param ncpus  \code{numeric} Number of core to use
#' @param ageMax \code{numeric} Maximum age in years Default = 120
#' @param dage \code{numeric} precision  for age Default = 0.01
#' @param minAge \code{numeric} Ages at which the analyses should start.  see ?basta for more information. Default = 0
#'
#' @return a data frame including age, the mean and 95% credible interval of the L90
#' 
#' @export
#' 
#' @importFrom paramDemo CalcSurv
#' @importFrom snowfall sfInit sfLibrary sfClusterApplyLB  sfStop
#' 
#' @examples
#' theMat = as.matrix(data.frame( b0 = rnorm(10, -6, 0.01),
#'                                b1= rnorm(10, 0.1, 0.01)))
#'
#'
#' out <- Sur_xx(theMat, model = 'GO', shape = 'simple', ncpus = 2,
#'               ageMax = 50, dage = 0.1, xx = 0.1)
Sur_xx <- function(theMat,  model = 'GO', shape = 'bathtub', ncpus = 1,
                   ageMax = 120, dage = 0.01, xx = 0.5, minAge =0) {
  
  assert_that(is.array(theMat))
  assert_that(is.numeric(ageMax))
  assert_that(ageMax >= 1)
  assert_that(is.numeric(dage))
  assert_that(dage > 0)
  assert_that(is.numeric(ncpus))
  assert_that(ncpus > 0)
  assert_that(is.numeric(xx))
  assert_that(xx > 0)
  assert_that(xx <1)
  assert_that(is.character(model))
  assert_that(all(model %in% c("GO", "EX", "LO", "WE")))
  assert_that(is.character(shape))
  assert_that(all(shape %in% c("simple", "bathtub", "Makeham")))
  
  iseq <- floor(seq(0, nrow(theMat), length = ncpus + 1))
  xv <- seq(0, ageMax, by = dage)
  
  # run parallel estimation:
  sfInit(parallel = TRUE, cpus = ncpus)
  # Run parallel function:
  exparal <- sfClusterApplyLB(1:ncpus, Sur_xx_0, theMat = theMat,
                              model = model, shape = shape,  
                              iseq = iseq,  xv = xv , xx=xx)
  # Stop application:
  sfStop()
  
  # Gather estimates:
  for (jj in 1:ncpus) {
    if (jj == 1) {
      exMat <- exparal[[jj]]
    } else {
      exMat <- c(exMat, exparal[[jj]])
    }
  }
  
  out <- list(L = mean(exMat+minAge), Lower = quantile(exMat+minAge,0.025), Upper =  quantile(exMat+minAge,0.975))
  
  return(out)
}


#' Age at which xx% of the population still alive
#'
#' @return Lxx
#' 
#' @importFrom paramDemo CalcSurv
#' 
#'
#' @noRd
Sur_xx_0 <- function(sim= 1, theMat ,model = 'GO', shape = 'bathtub',  
                     iseq = 1:nrow(theMat), xx =0.5,
                     xv = seq(0, 50, by = 0.01)
) {
  
  idseq <- (iseq[sim] + 1):iseq[sim + 1]
  surage <- t(sapply(idseq, function(ith) {
    theta <- theMat[ith, ]
    Sx <- paramDemo::CalcSurv(theta = theta, x = xv, model = model, shape = shape)
    Lxx <- xv[max(which(Sx>=xx))]
    return(Lxx)
  }))
  return(surage)
}
