# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

#' Remaining life expectancy
#' 
#' Estimate remaining life expectancy over age from the parameters outputs of a Basta model.
#' 
#'
#' @param theMat \code{array} including the posteriors estimates of the model parameter
#' @param model \code{character} names of the basta models to run: "G0", "EX", "LO" and/or "WE". see ?basta for more information. Default = "GO"
#' @param shape \code{character} shape of the basta model: "simple", "Makeham", "bathtub".  see ?basta for more information. Default = "simple"
#' @param ncpus  \code{numeric} Number of core to use
#' @param xMax \code{numeric} Maximum age in years Default = 120
#' @param dx \code{numeric} precision for age Default = 0.01
#' @param minAge \code{numeric} Ages at which the analyses should start.  see ?basta for more information. Default = 0
#'
#' @return a data frame including age, the mean and 95% credible interval of the remaining life expectancy
#' 
#' @export
#' 
#' @importFrom paramDemo CalcSurv
#' @importFrom snowfall sfInit sfLibrary sfClusterApplyLB  sfStop
#' 
#' @examples
#' theMat = as.matrix(data.frame( b0 = rnorm(10, -6, 0.01),
#'                                b1= rnorm(10, 0.1, 0.01)))
#'
#'
#' out <- Sur_relex(theMat, model = 'GO', shape = 'simple', ncpus = 2,
#'                  xMax = 50, dx = 0.1)
Sur_relex <- function(theMat, model = 'GO', shape = 'bathtub', ncpus = 1,
                      xMax = 120, dx = 0.01,minAge = 0) {
  
  assert_that(is.array(theMat))
  assert_that(is.numeric(xMax))
  assert_that(xMax > 1)
  assert_that(is.numeric(dx))
  assert_that(dx > 0)
  assert_that(is.numeric(ncpus))
  assert_that(ncpus > 0)
  assert_that(is.character(model))
  assert_that(all(model %in% c("GO", "EX", "LO", "WE")))
  assert_that(is.character(shape))
  assert_that(all(shape %in% c("simple", "bathtub", "Makeham")))
  
  iseq <- floor(seq(0, nrow(theMat), length = ncpus + 1))
  xv <- seq(0, xMax, by = dx)
  
  # run parallel estimation:
  sfInit(parallel = TRUE, cpus = ncpus)
  # Upload paramDemo:
  # sfLibrary(paramDemo)
  # export variables:
  # sfExport(list = c("iseq", "theMat", "model", "shape", "xMax", "dx"))
  # Run parallel function:
  exparal <- sfClusterApplyLB(1:ncpus, Sur_relex_0, theMat = theMat,
                              model = model, shape = shape,  
                              iseq = iseq, 
                              xMax = xMax, dx = dx, xv = xv )
  
  # Stop application:
  sfStop()
  
  # Gather estimates:
  for (jj in 1:ncpus) {
    if (jj == 1) {
      exMat <- exparal[[jj]]
    } else {
      exMat <- rbind(exMat, exparal[[jj]])
    }
  }
  
  exQuants <- data.frame(Age = xv[which(xv <= xMax)] + minAge, 
                         RemLExp = apply(exMat, 2,quantile, 0.5), 
                         Lower = apply(exMat, 2, quantile, 0.025),
                         Upper = apply(exMat, 2, quantile, 0.975))
  return(exQuants)
}


#' Raw remaining life expectancy
#'
#' @return a data frame including age, the mean and 95% credible interval of the remaining life expectancy
#' 
#' @importFrom paramDemo CalcSurv
#' 
#'
#' @noRd
Sur_relex_0 <- function(sim= 1, theMat ,model = 'GO', shape = 'bathtub',  
                        iseq = 1:nrow(theMat), xMax = 120, dx = 0.01 , xv = seq(0, xMax, by = dx)
) {
  
  idseq <- (iseq[sim] + 1):iseq[sim + 1]
  
  remex <- t(sapply(idseq, function(ith) {
    theta <- theMat[ith, ]
    Sx <- paramDemo::CalcSurv(theta = theta, x = xv, model = model, shape = shape)
    ex <- Sx * 0
    idn0 <- which(Sx > 0.001)
    ex[idn0] <- rev(cumsum(rev(Sx[idn0] * dx))) / Sx[idn0]
    return(ex)
  }))
  return(remex)
}
