# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

#' Main survival analysis for taxon profiles
#' 
#' Run the survival analysis per sex and per birth type
#'
#' @param data.core \code{data.frame} including at least the following columns *AnimalAnonID*, *BirthDate*, *DepartDate*, *EntryDate*, *MaxBirthDate*, *MinBirthDate*, *EntryType*, *DepartType*, *FirstHoldingInstitution*, *LastHoldingInstitution*, *SexType*, and *BirthType*
#' @param DeathInformation  \code{data.frame} including at least the following columns *AnimalAnonID* and *RelevantDeathInformationType*
#' @param Birth_Type \code{character} When separated the analysis by sex category, the birth type to be selected: Captive, Wild, or All Default =  "All"
#' @param outlLev1 \code{numeric} Start threshold used to selected for the data: 100%, 99.9, 99 or 95%
#' @param models \code{vector of characters} names of the basta models to run: "G0", "EX", "LO" and/or "WE". see ?basta for more information. Default = "GO"
#' @param shape \code{character} shape of the basta model: "simple", "Makeham", "bathtub".  see ?basta for more information. Default = "simple"
#' @param XMAX \code{numeric} Maximum possible age. Default = 120
#' @param uncert_death \code{numeric}: Maximum uncertainty accepted for death date, in days
#' @param mindate \code{character 'YYYY-MM-DD'} Earlier date to include data
#' @param minNsur \code{numeric} Minimum number of individual records needed to run the survival analysis. Default = 50
#' @param maxNsur \code{numeric} Maximum number of individual records to run the survival analysis. Default = NULL
#' @param minInstitution \code{numeric} Minimum number of institutions that should hold records to run the survival analysis. Default = 2
#' @param minAge \code{numeric} Ages at which the analyses should start.  see ?basta for more information. Default = 0
#' @param firstyear \code{logical} Whether to do the analysis only on first year. Default = FALSE
#' @param minlx  \code{numeric} between 0 and 1. Minimum reached survivorship from the raw Kaplan Meier analysis needed to run the survival analysis. Default = 0.1
#' @param MinBirthKnown  \code{numeric} between 0 and 1. Minimum proportion of individuals with a known birth month in the data. Default = 0.3
#' @param Min_MLE \code{numeric} Goodness of fit: Minimum survivorship at Mean life expectancy
#' @param MaxLE \code{numeric} Goodness of fit: Maximum remaining life expectancy at max age
#' @param niter  \code{numeric}. number of MCMC iterations to run. see ?basta for more information. Default = 25000
#' @param burnin  \code{numeric} Number of iterations removed so that the model has time to converge. see ?basta for more information. Default = 5001
#' @param thinning  \code{numeric} Number of iteration to run before saving a set of parameters. see ?basta for more information. Default = 20
#' @param nchain  \code{numeric} Number of chains to run. Default = 5001
#' @param ncpus  \code{numeric} Number of computer core to use. Default = 2
#' @param PlotDir \code{character} Directory to save the plots. Default = NULL, no plot is saved
#' @param plotname \code{character} Name used to save the plot. Default = ""
#' @param lastdead  \code{logical} Whether the longest lived individuals should be considered dead. Default = FALSE
#' 
#' @return The output of a list including per sex categories:
#' * a summary of the data used:
#'- NGlobal: Number of captive born individuals selected from global collections
#'- NBasta: Number of data (individuals) selected for the BaSTA/survival analysis
#'- Ndead:Number of individuals with known age of death used in the BaSTA/survival analysis
#'- maxAge: Maximum age of known age individuals
#'- maxAlive:Maximum number of years spent ex situ
#'- lxMin:Minimum survivorship reached with the raw Kaplan-Meier model
#'-  OutLev: threshold selected for the distribution of  time spent alive: 100%, 99.9, 99 or 95%
#'- a logical indicated if the survival analysis was performed
#'-  If the survival analysis was not performed, an error and its number (Nerr) are returned: The possibility for  this functions are: 2/Nuncertdeath < minNsur; 3/lxMin > minlx; 4/NBasta = 0; 5/ %known births < MinBirthKnown; 6/Data from 1 Institution; 7/Nbasta < minNsur; 8/Nbasta < maxNsur; 9/no DIC from Basta; 10/Kaplan-Meier does not fit; 11/Motality does not fit; 12/Min(Life_exp) >= MaxLE; 13/lx[MLE] < Min_MLE.
#'- A goodness of fit tested the trend in the residuals between the model prediction and the kaplan meier estimator
#'* the basta fit of the best model
#'* the DIC table comparing the different fit of the models
#'* the estimated remaining life expectancy per age
#'* the age at which 90% of the population died
#'* the estimated probability to live one year more
#'* the estimated probability to live five years more
#' If PlotDir is filled, 2 plots are produced: one showing the outliers removed from the data, and one showing the fit of the model on the data.
#'
#' @export

#' @examples
#' data(core)
#' data(deathinformation)
#' out <- Sur_main(core, DeathInformation = deathinformation, Birth_Type = "All",
#'                 models = "GO", shape = "simple",
#'                 niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
Sur_main <- function(data.core,   DeathInformation, Birth_Type = "All",
                     models = "GO", shape= "simple", firstyear =FALSE,
                     outlLev1 = NA,minAge =0,
                     mindate = "1980-01-01", minNsur = 50, maxNsur = NULL,
                     minInstitution = 2,uncert_death=365,
                     minlx = 0.1, MinBirthKnown = 0.3, 
                     Min_MLE = 0.1, MaxLE = 2,XMAX=120,lastdead = FALSE,
                     niter = 25000, burnin = 5001, thinning = 20, nchain = 3, 
                     ncpus = 2, PlotDir = NULL, plotname = '') {
  
  mindate = lubridate::as_date(mindate)
  assert_that(is.data.frame(data.core))
  assert_that(data.core  %has_name% c("AnimalAnonID", "BirthDate", "DepartDate",
                                      "EntryDate", "MaxBirthDate", "MinBirthDate",
                                      "EntryType", "DepartType", "FirstHoldingInstitution", 
                                      "LastHoldingInstitution", "SexType", "BirthType"))
  assert_that(is.data.frame(DeathInformation))
  assert_that(DeathInformation %has_name% c("AnimalAnonID","RelevantDeathInformationType"))
  if(!is.na(outlLev1)){
    assert_that(is.numeric(outlLev1))
    assert_that(outlLev1 <= 100)
  }else(outlLev1 = 100)
  assert_that(is.numeric(minAge))
  assert_that(is.numeric(minNsur))
  assert_that(is.numeric(uncert_death))
  if(!is.null(maxNsur)) assert_that(is.numeric(maxNsur))
  assert_that(is.double(minInstitution))
  assert_that(is.numeric(Min_MLE))
  assert_that(is.numeric(MaxLE))
  assert_that(MinBirthKnown <1)
  assert_that(is.numeric(niter))
  assert_that(niter > 0)
  assert_that(is.numeric(burnin))
  assert_that(burnin > 0)
  assert_that(burnin < niter)
  assert_that(is.numeric(thinning))
  assert_that(thinning > 0)
  assert_that(thinning < niter)
  assert_that(is.numeric(nchain))
  assert_that(nchain > 0)
  assert_that(is.numeric(ncpus))
  assert_that(ncpus > 0)
  assert_that(is.character(models))
  assert_that(is.character(plotname))
  assert_that(all(models %in% c("GO", "EX", "LO", "WE")))
  assert_that(is.character(shape))
  assert_that(all(shape %in% c("simple", "bathtub", "Makeham")))
  assert_that(is.character(Birth_Type))
  assert_that(length(Birth_Type) == 1, msg = "You can use only one birth type for each sex analysis")
  assert_that(Birth_Type %in% c("Captive", "Wild", "All"))
  if(!is.null(PlotDir)){
    checkmate::assert_directory_exists(PlotDir)
  }
  out = list()
  # Run analyses:
  if (Birth_Type != "All"){
    sexData<- data.core %>%
      filter(stringr::str_detect(BirthType, pattern = Birth_Type))
  }else{sexData<- data.core}
  # Survival Analysis
  for(j in 1:length(minAge)){
    
    out[[paste0("from",minAge[j])]]<- Sur_ana(sexData, DeathInformation = DeathInformation,
                                              outlLev1 = outlLev1, 
                                              models = models, shape = shape,
                               mindate = mindate,      uncert_death = uncert_death, 
                               lastdead = lastdead, minAge = minAge[j],
                               minNsur = minNsur, maxNsur = maxNsur,
                               minInstitution = minInstitution,
                               minlx = minlx, MinBirthKnown = MinBirthKnown, 
                               niter = niter, burnin = burnin, thinning = thinning, 
                               nchain = nchain, ncpus = ncpus) 
  out[[paste0("from",minAge[j])]] <- append( out[[paste0("from",minAge[j])]], 
                                             list(relex = NULL, Sur1 = NULL, Sur5 = NULL, L90 = NULL, L50 = NULL))
  
  
  if (out[[paste0("from",minAge[j])]]$summary$analyzed) {
    
    out[[paste0("from",minAge[j])]]  <-Sur_out(out[[paste0("from",minAge[j])]] , shape= shape, 
                                XMAX=XMAX,ncpus = ncpus, minAge = minAge[j],
                                PlotDir = PlotDir, plotname = paste0(plotname,"_",minAge[j]),
                                Min_MLE = Min_MLE, MaxLE = MaxLE
    )
  }
  }
  if(firstyear){
  
  out[["firstyear"]]<- Sur_ana1(sexData, DeathInformation = DeathInformation, 
                                models = models, shape = shape,
                                mindate = mindate,      uncert_death = uncert_death, 
                                uncert_birth = 30, 
                                minNsur = minNsur, maxNsur = maxNsur, minInstitution = minInstitution,
                                niter = niter, burnin = burnin, thinning = thinning, nchain = nchain, ncpus = ncpus) 
  out[["firstyear"]] <- append(out[["firstyear"]], list(Sur1 = NULL))
  if (out[["firstyear"]]$summary$analyzed) {
    
    out[["firstyear"]] <-Sur_out(out[["firstyear"]], shape= shape, 
                                 XMAX=XMAX,ncpus = ncpus, firstyear = TRUE,
                                 PlotDir = PlotDir, plotname = paste0(plotname,"_1yo"),
                                 Min_MLE = Min_MLE, MaxLE = MaxLE
    )
  }
  }
  return(out)
}

