# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

#' Create output and plots for the survival analysis
#' 
#' Estimate remaning life expectancy, L90, L50 and age-specific survival.
#'
#' @param out \code{numeric} The output of the survival analysis
#' @param XMAX \code{numeric} Maximum possible age. Default = 120
#' @param shape \code{character} shape of the basta model: "simple", "Makeham", "bathtub".  see ?basta for more information. Default = "simple"
#' @param Min_MLE \code{numeric} Goodness of fit: Minimum survivorship at Mean life expectancy
#' @param MaxLE \code{numeric} Goodness of fit: Maximum remaining life expectancy at max age
#' @param ncpus  \code{numeric} Number of computer core to use. Default = 2
#' @param PlotDir \code{character} Directory to save the plots. Default = NULL, no plot is saved
#' @param plotname \code{character} Name used to save the plot. Default = ""
#' @param firstyear \code{logical} Whether the analysis was done only on first year. Default = FALSE
#' @param minAge \code{numeric} Ages at which the analyses should start.  see ?basta for more information. Default = 0
#' 
#' @return The output list of the survival analysis including in addition:
#' * a summary of the data used:
##'- A goodness of fit tested the trend in the residuals between the model prediction and the kaplan meier estimator
#'* the estimated remaining life expectancy per age
#'* the age at which 90% of the population died
#'* the age at which 50% of the population died
#'* the estimated probability to live one year more
#'* the estimated probability to live five years more
#' If PlotDir is filled, 2 plots are produced: one showing the outliers removed from the data, and one showing the fit of the model on the data.
#'
#' @export
#'
#' @importFrom grDevices pdf dev.off
#' @importFrom graphics lines
#'
#' @examples
#' data(core)
#' data(deathinformation)
#' out <- Sur_ana(core,  DeathInformation = deathinformation, models = "GO", shape = "simple",
#'                niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
#'
#' out <- Sur_out(out, shape = "simple", ncpus = 3)
Sur_out <- function(out, shape= "simple", 
                    XMAX=120,ncpus = 2, minAge = 0,
                    PlotDir = NULL, plotname = '',
                    Min_MLE = 0.1, MaxLE = 2,
                    firstyear = FALSE) {
  
  assert_that(is.numeric(Min_MLE))
  assert_that(is.numeric(MaxLE))
  assert_that(is.numeric(ncpus))
  assert_that(ncpus > 0)
  assert_that(is.character(plotname))
  assert_that(is.character(shape))
  assert_that(all(shape %in% c("simple", "bathtub", "Makeham")))
  if(!is.null(PlotDir)){
    checkmate::assert_directory_exists(PlotDir)
  }
  
  # Find age at S(x) = 0.005:
  Sx <- out$bastaRes$surv$nocov[1,]
  idxMax <- out$bastaRes$x[which(Sx < 0.005)][1]
  if (is.na(idxMax)) {
    xMax <- min(max(out$bastaRes$x),XMAX)
  } else {xMax = idxMax}
    paramax = length(out$bastaRes$names)
    if("lambda" %in% out$bastaRes$names){paramax = paramax-1}
 
  if(!firstyear){
    
     
    # Remaining life expectancy:
    out$relex <- Sur_relex(theMat = out$bastaRes$params[,1:paramax], 
                           model = out$bastaRes$modelSpecs["model"], 
                           shape = shape, ncpus = ncpus, 
                           xMax = xMax, dx = 0.01, minAge = minAge)
    
    # L90 : Age at which 90% of the individuals died
    out$L90 <- Sur_xx(theMat = out$bastaRes$params[,1:paramax],  
                      model = out$bastaRes$modelSpecs["model"], 
                      shape = shape, ncpus = ncpus, xx = 0.1,
                      ageMax = xMax, dage = 0.01, minAge = minAge)
    # L50 : Age at which 50% of the individuals died
    out$L50 <- Sur_xx(theMat = out$bastaRes$params[,1:paramax],  
                      model = out$bastaRes$modelSpecs["model"], 
                      shape = shape, ncpus = ncpus, xx = 0.5,
                      ageMax = xMax, dage = 0.01, minAge = minAge)
    # Proba to live 5 year more:
    if(xMax >=5){
      out$Sur5 <- Sur_age(theMat = out$bastaRes$params[,1:paramax], 
                          model =out$bastaRes$modelSpecs["model"], 
                          shape = shape, ncpus = ncpus,  minAge = minAge,
                          ageMax = xMax,  dage = 0.01, Nyear = 5)
    }else{out$Sur5 = "Error : Age max lower than 5 years"}
   # Proba to live 1 year more:
  out$Sur1 <- Sur_age(theMat = out$bastaRes$params[,1:paramax],  
                      model = out$bastaRes$modelSpecs["model"], 
                      shape = shape, ncpus = ncpus, minAge = minAge,
                      ageMax = xMax, dage = 0.01, Nyear = 1)
  
  }else{
  # Proba to live 1 year more:
  out$Sur1m <- Sur_age(theMat = out$bastaRes$params[,1:paramax],  
                      model = out$bastaRes$modelSpecs["model"], 
                      shape = shape, ncpus = ncpus, minAge = 0,
                      ageMax = 1, dage = 1/12, Nyear = 1/12)
  }
  
  # Goodness of fit tests
    
      
  if(!firstyear){
      xmaxobs = max(out$bastaRes$lifeTable$noCov$Mean$Ages)
  ##Test if the life expectancy at max age observed is below MaxLE years old
  idxmax = ifelse(max(out$relex$Age) > xmaxobs, which(out$relex$Age==xmaxobs), length(out$relex$Age))
  if(out$relex$RemLExp[idxmax]>= MaxLE){
    out$summary$error = "Min(Life_exp) >= MaxLE"
    out$summary$Nerr=11
    # out$summary$analyzed <- FALSE 
    # out$bastaRes <- list()
  }
    ##Test if the survivorship at mean life expectancy is higher than Min_MLE
    lx <-out$bastaRes$lifeTable$noCov$Mean$lx
    #age for mle
    dif <-abs(out$bastaRes$lifeTable$noCov$Mean$Ages - out$bastaRes$PS$nocov$PS[1,1])
    
    if(lx[which(dif == min(dif))]< Min_MLE){
      # out$summary$analyzed <- FALSE
      out$summary$error = "lx[MLE] < Min_MLE"
      out$summary$Nerr = 12
      # out$bastaRes <- list()   
    }
  }  
 
     ##Test if residuals of predicted lx vs. kaplan meier estimator has a trend
  # id = which(out$bastaRes$x %in% seq(0,round(XMAX)),0.5)
  # m = min(length(id),(round(XMAX)+1), length(out$bastaRes$lifeTable$noCov$Mean$lx))
  # if(length(id)>m){ id = which(out$bastaRes$x %in% out$bastaRes$lifeTable$noCov$Mean$Ages)}
  # res = out$bastaRes$surv$nocov[1,id] - out$bastaRes$lifeTable$noCov$Mean$lx[1:m]
  # b = summary(lm(res~c(1:m)))
  # out$summary$Gof_KM = b$coefficients[2,4] > 0.01
  # out$summary$Gof_KM_coeff =b$coefficients[2,1]
  
  #test if kaplan-meier estimator is within the estimated 95CI
  Lx= tibble(Meann = out$bastaRes$surv$nocov[1,],
             Lower = out$bastaRes$surv$nocov[2,],
             Upper = out$bastaRes$surv$nocov[3,],
             Ages =out$bastaRes$x )%>%
    filter(Ages >=minAge)
  #correct estimates when minAge >0
  Lx$Meann=Lx$Meann/Lx$Meann[1]
  Lx$Lower=Lx$Lower/Lx$Lower[1]
  Lx$Upper=Lx$Upper/Lx$Upper[1]
  
  LT = out$bastaRes$lifeTable$noCov$ple%>%
    mutate(Ages = round(Ages/0.05)*0.05)%>%
    filter(Ages >=minAge)
#correct estimates when minAge >0
  LT$ple   =  LT$ple/ LT$ple[1]
    LT = LT%>%
    group_by(Ages)%>%
    summarise(ple = max(ple))%>%
    left_join(Lx)%>%
    tidyr::drop_na(Lower, Upper)%>%
    mutate(check = (ple <= Upper & ple >= Lower),
           residual = Meann - ple,
           sign = ifelse(residual <0, -1,1),
           diff = 0)
LT$diff[2:nrow(LT)] =ifelse(LT$sign[1:(nrow(LT)-1)] == LT$sign[2:nrow(LT)], 0,1)
LT$diff = cumsum(LT$diff)

v <- LT%>%
  group_by(diff)%>%
  summarise(resi = abs(sum (residual)))
  
  check = length(which(LT$check))/nrow(LT)
  out$summary$Gof_KM_coeff1 =check
  out$summary$Gof_KM_coeff2 =max(v$resi)

 if(max(v$resi)>=2 & out$summary$Nerr==0 ){
    out$summary$error = "Kaplan-Meier does not fit:2"
      out$summary$Nerr = 13
    }
  if(check < 0.8){
   out$summary$error = "Kaplan-Meier does not fit"
      out$summary$Nerr = 10
    }



 
  #Plots
  if(!is.null(PlotDir)){
       pdf(file = paste0(PlotDir,"/",out$summary$Nerr,'_', plotname, "_surcheck.pdf", sep=""), width = 6, height = 6)
   if(firstyear){
    plot(out$bastaRes, main = plotname)
    plot(out$bastaRes, plot.type = 'demorates', xlim = c(0,1))
    plot(out$bastaRes, plot.type = 'gof', xlim = c(0,1))
    dev.off()
    
     pdf(file = paste0(PlotDir,"/", out$summary$Nerr,'_', plotname, "_surplot.pdf", sep=""), width = 6, height = 6)
           out$Sur1m$Agem=round(out$Sur1m$Age*12,2)
      plot(out$Sur1m$Sur ~  out$Sur1m$Agem, 
           xlab = "Age (month)", ylab = 'Month-specific survival', type = "l")
      lines(out$Sur1m$Lower ~  out$Sur1m$Agem, lty = 2)
      lines(out$Sur1m$Upper ~  out$Sur1m$Agem, lty = 2)
         dev.off()

    }else{
       plot(out$bastaRes, main = plotname)
    plot(out$bastaRes, plot.type = 'demorates')
    plot(out$bastaRes, plot.type = 'gof')
    dev.off()
    
      pdf(file = paste0(PlotDir,"/", out$summary$Nerr,'_', plotname, "_surplot.pdf", sep=""), width = 6, height = 6)
      plot(out$relex$RemLExp~  out$relex$Age, main = plotname, xlab = "Age (year)", 
           ylab = "Remaining life expectancy", type = "l")
      lines(out$relex$Lower ~  out$relex$Age, lty = 2)
      lines(out$relex$Upper ~  out$relex$Age, lty = 2)
      
      plot(out$Sur1$Sur ~  out$Sur1$Age, 
           xlab = "Age (year)", ylab = 'Age-specific survival', type = "l")
      lines(out$Sur1$Lower ~  out$Sur1$Age, lty = 2)
      lines(out$Sur1$Upper ~  out$Sur1$Age, lty = 2)
      
      if(xMax >=5){
        plot(out$Sur5$Sur ~  out$Sur5$Age, 
             xlab = "Age (year)", ylab = 'p(survive 5 more years)', type = "l")
        lines(out$Sur5$Lower ~  out$Sur5$Age, lty = 2)
        lines(out$Sur5$Upper ~  out$Sur5$Age, lty = 2)
      }
      dev.off()
    }
    
  }
  
  
  return(out)
}

