# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand

#' Create Basta data frame
#' 
#' Check column names and succession of dates to prepare the data for BASTA.
#'
#' @param coresubset  \code{data.frame} including at least the following columns *AnimalAnonID*, *binSpecies*, *Class*, *Order*, *Family*, *CommonName*, *BirthDate*, *DepartDate*, *EntryDate*, *MaxBirthDate*, *MinBirthDate*, *EntryType*, and *DepartType*.
#' @param DeathInformation  \code{data.frame} including at least the following columns *AnimalAnonID* and *RelevantDeathInformationType*.
#' @param EarliestDate \code{character 'YYYY-MM-DD'} Earlier date to be included.
#' @param LatestDate \code{character 'YYYY-MM-DD'} Latest date to be included.
#' @param OtherCovars \code{vector of character}. Additional variables to include in the data.
#' @param ExcludeStillBirth \code{logical} Whether to exclude still births.
#' 
#' @details
#' This function removes:
#' * individuals with NA in the columns BirthDate, MinBirthDate, MaxBirthDate, EntryDate, and DepartDate.
#' * individuals for which the dates from min birth date/entry date to Depart date do not follow one another in a logical order.
#' * Still born individuals if required
#' * individuals with depart date anterior to earliest date
#' * individuals with entry date posterior to latest date
#' * Depart date posterior to latest date are changed to latest date. These individuals are considered as right-censored.
#'
#' @return the subset dataset in the basta format
#' 
#' @export
#' @importFrom tidyr replace_na
#'
#' @examples
#' data(core)
#' data(deathinformation)
#' out<- surv_Bastab(core, DeathInformation = deathinformation,
#'                   EarliestDate = '1990-01-01', LatestDate = '2020-12-31', 
#'                   OtherCovars = "SexType", ExcludeStillBirth = TRUE)
#'
#'
surv_Bastab <- function (coresubset, DeathInformation, 
                         EarliestDate = NA, LatestDate = NA, 
                         OtherCovars = NA, ExcludeStillBirth = FALSE) 
{   
  
  # Check correct format for inputs --------------------------------------------
inclcols <- c("AnimalAnonID", "binSpecies", "Class", 
                "Order", "Family", "CommonName", "BirthDate", "MinBirthDate", 
                "MaxBirthDate", "EntryDate", "DepartDate", "EntryType", 
                "DepartType")
  assert_that(coresubset %has_name% inclcols)
  assert_that(DeathInformation %has_name% c("AnimalAnonID","RelevantDeathInformationType"))
  assert_that(is.logical(ExcludeStillBirth))
  if (all(!is.na(OtherCovars))) {
    assert_that(coresubset %has_name% OtherCovars)
    inclcols <- c(inclcols, OtherCovars)
  }
  
  # Select columns and join RDI  -----------------------------------------------
  bastadat <- coresubset[, inclcols]%>%
    left_join(DeathInformation%>%select(AnimalAnonID, RelevantDeathInformationType)%>%
                filter(RelevantDeathInformationType %in% c("Stillborn","Fetal death")), by = "AnimalAnonID")
  if (all(!is.na(OtherCovars))) {
    colnames(bastadat) <- c("AnimalAnonID", "binSpecies", "Class", 
                            "Order", "Family", "CommonName", "Birth.Date", "Min.Birth.Date", 
                            "Max.Birth.Date", "Entry.Date", "Depart.Date", "Entry.Type", 
                            "Depart.Type",OtherCovars, "RelevantDeathInformationType")
  }else{
    colnames(bastadat) <- c("AnimalAnonID", "binSpecies", "Class", 
                            "Order", "Family", "CommonName", "Birth.Date", "Min.Birth.Date", 
                            "Max.Birth.Date", "Entry.Date", "Depart.Date", "Entry.Type", 
                            "Depart.Type","RelevantDeathInformationType")
    
  }
  
  # Remove individuals with too Early or too late dates, and check logical succession of dates ------------------------
  if (is.na(EarliestDate)) {
    EarliestDate <- min(bastadat$Min.Birth.Date, na.rm = TRUE)
  }else{
    EarliestDate <- lubridate::as_date(EarliestDate)
  }
  if (is.na(LatestDate)) {
    LatestDate <- lubridate::today()
  }else{
    LatestDate <- lubridate::as_date(LatestDate)
  }
  
  bastadat <- bastadat%>%
    mutate(Depart.Date = lubridate::as_date(Depart.Date),
           Entry.Date = lubridate::as_date(Entry.Date),
           Min.Birth.Date = lubridate::as_date(Min.Birth.Date),
           Max.Birth.Date = lubridate::as_date(Max.Birth.Date),
           Birth.Date = lubridate::as_date(Birth.Date)
    )%>%
    filter(Depart.Date >= EarliestDate,
           Entry.Date <= LatestDate)%>%
    tidyr::drop_na(c(Birth.Date, Min.Birth.Date, Max.Birth.Date, Entry.Date, Depart.Date))%>%
    filter((Min.Birth.Date <= Birth.Date)%>% replace_na(TRUE), 
           (Birth.Date <= Max.Birth.Date)%>% replace_na(TRUE), 
           (Birth.Date <= Entry.Date)%>% replace_na(TRUE), 
           (Entry.Date <= Depart.Date)%>% replace_na(TRUE))%>%
    mutate(Depart.Type = if_else (Depart.Date > LatestDate, "C", Depart.Type),
           Depart.Date = if_else (Depart.Date > LatestDate, LatestDate, Depart.Date),
           Entry.Type  = if_else (Entry.Date < EarliestDate, "C", Entry.Type),
           Entry.Date  = if_else (Entry.Date < EarliestDate, EarliestDate, Entry.Date)
    )
  
  # Remove Stillborn if required ------------------------------------------------
  if(ExcludeStillBirth){
    bastadat <- bastadat%>%
      filter((Depart.Date != Birth.Date)%>% replace_na(TRUE),
             stringr::str_detect(RelevantDeathInformationType, "Stillborn", negate = T)%>% replace_na(TRUE),
             stringr::str_detect(RelevantDeathInformationType, "Fetal death", negate = T)%>% replace_na(TRUE))
  }%>%
    select(-"RelevantDeathInformationType")

  return(bastadat)
}
