# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Summarize taxon profiles analyses
#' 
#' Produce summary tables and plots of the demographic analyses made for all species
#'
#' @param SpeciesTable \code{Data.frame} including 2 columns: *Class* and *Species*
#' @param AnalysisDir  \code{character} directory where to find the .Rdata files
#' @param SaveDir  \code{character} directory where to save the json files
#' @param namefile \code{character} Suffix to add to the name of files produced if needed. Default = ""
#' @param taxaList \code{vector of characters} name of the taxa studied. Default= "Mammalia"
#' @param BySex \code{List} indicating the sexes analyzed. Default= list(Mammalia= c("Male", "Female"))
#' @param Sections \code{vector of character} names of the sections to update in the taxon profile results: "sur", "rep" and/or "gro". Default = c("sur", "rep", "gro")
#'
#' @return It saves summary tables and plots for each Sections and a general summary table. It returns the main summary table
#' @export
#' 
#' @importFrom ggplot2 ggplot scale_fill_brewer facet_wrap geom_bar labs position_dodge coord_flip
#' @importFrom ggpubr ggarrange
#' 
#' @examples
#' # file = system.file("sci_Animal.csv", package = 'ISRverse')
#' # AnalysisDir  = paste0(dirname(file),'\\Rdata')
#' # SaveDir = paste0(tempdir(check = TRUE),'\\temp')
#' # dir.create(SaveDir)
#' # SpeciesTable = data.frame( Class = "Reptilia", Species = "Testudo hermanni")
#' # Tx_devout(SpeciesTable, AnalysisDir, SaveDir,
#' #                         taxaList = "Reptilia",
#' #                         BySex = list(Reptilia = c("Male", "Female")) ,
#' #                         Sections = c("sur", 'gro')
#' # )
#' # list.files(SaveDir)
#' # unlink(SaveDir, recursive = TRUE)
Tx_devout <- function (SpeciesTable, AnalysisDir, SaveDir, namefile = "",
                       taxaList = "Mammalia",
                       BySex = list(Mammalia= c("Male", "Female")) , 
                       Sections = c("sur", 'rep', 'gro')
){
  
  assert_that(is.data.frame(SpeciesTable))
  
  assert_that(SpeciesTable  %has_name% c("Class", "Species"))
  assert_that(is.character(taxaList))
  # assert_that(taxaList %in% c("Mammalia", "Aves", "Reptilia", "Amphibia", 
  #                             "Chondrichthyes", "Actinopterygii"),
  #             msg = "taxa must one of 'Mammalia', 'Aves', 'Reptilia', 'Amphibia', 
  #                         'Chondrichthyes', or 'Actinopterygii'")
  assert_that(is.character(Sections))
  assert_that(all(Sections %in% c("sur", "gro", "rep")))
  checkmate::assert_directory_exists(AnalysisDir)
  checkmate::assert_directory_exists(SaveDir)
  assert_that(is.character(namefile))
  assert_that(is.list(BySex))
  assert_that(all(taxaList %in% names(BySex)), msg = "BySex should be a list with names identical to taxaList")
  
  # List of available SRGs:
  SRGlist <- list.files(AnalysisDir, pattern = ".RData")
  assert_that(length(SRGlist) > 0, 
              msg = glue::glue("There are no result file in {AnalysisDir}"))
  
  for (taxa in taxaList) {
    
    SRGspecies = SpeciesTable%>%filter(Class==taxa)%>%pull(Species)
    SRGspeciesta = SRGspecies %>%stringr::str_replace(" ", "_")
    i = 0
    # Loop over species
    for (isp in SRGspeciesta) {
      i = i+1
      specie =isp%>%
        stringr::str_remove(pattern = paste0(taxa, '_'))%>%
        stringr::str_replace("_", " ")
      
      cat("\n", taxa," -------Species: ", SRGspecies[i], "Progress:", round(i / length(SRGspecies) * 100, 1),"%")
      
      # SRG file:
      load(file = glue::glue("{AnalysisDir}/{taxa}_{isp}.RData"))
      TPout = list()
      
      # Fill up data list:
      for (sx in  BySex[[taxa]]) {
        if("sur" %in% Sections){
          TPout$survival[[sx]]$Nbasta = repout$surv[[sx]]$from0$summary$NBasta
          TPout$survival[[sx]]$Lx = cbind(Age = repout$surv[[sx]]$from0$bastaRes$x, t(repout$surv[[sx]]$from0$bastaRes$surv$nocov))
          TPout$survival[[sx]]$relex = repout$surv[[sx]]$from0$relex
          TPout$survival[[sx]]$Sur1= repout$surv[[sx]]$from0$Sur1
          
        }
        
      }
      write(rjson::toJSON(TPout), file = glue("{SaveDir}/{namefile}{taxa}_{isp}.json"))
    }
    
    if("gro" %in% Sections){
      print("There is no growth output for now")
    }
    if("rep" %in% Sections){
      print("There is no reproduction output for now")
      
    }
  }
}
