# WARNING - Generated by {fusen} from dev/flat_select.Rmd: do not edit by hand

#' Taxon profile report
#' 
#' Run the survival, reproduction and growth analysis for the selected species
#'
#' @param taxa  \code{character} the name of the taxa studied
#' @param species \code{character} the name of the species studied
#' @param core \code{data.frame} core data
#' @param collection  \code{data.frame} collection data
#' @param PlotDir \code{character} Directory to save the plots. Default = NULL, no plot is saved
#' @param weights \code{data.frame} weights data if the growth analysis is run
#' @param parents \code{data.frame} parents data if the reproduction analysis is run
#' @param contraceptions \code{data.frame} contraception data if the reproduction analysis is run
#' @param repout \code{list} Previous result of the taxon profile for this species if it needs to be updated only
#' @param Sections \code{vector of character} names of the sections to update in the taxon profile results: "sur", "rep" and/or "gro". Default = c("sur", "rep", "gro")
#' @param sexCats \code{character} Male, Female or All Default =  "All"
#' @param minN \code{numeric} Minimum number of individuals. Default = 50
#' @param minDate \code{character 'YYYY-MM-DD'} Earlier date to include data
#' @param extractDate \code{character 'YYYY-MM-DD'} Date of data extraction
#' @param minNsur \code{numeric} Minimum number of individual records needed to run the survival analysis. Default = 50
#' @param minlx  \code{numeric} between 0 and 1. Minimum reached survivorship from the raw Kaplan Meier analysis needed to run the survival analysis. Default = 0.1
#' @param MinBirthKnown  \code{numeric} between 0 and 1. Minimum proportion of individuals with a known birth month in the data. Default = 0.3
#' @param maxOutl \code{numeric} Maximum threshold for the longevity distribution. Default = 100
#' @param models_sur \code{vector of characters} names of the survival basta models to run: "G0", "EX", "LO" and/or "WE". see ?basta for more information. Default = "GO"
#' @param shape \code{character} shape of the survival basta model to run: "simple", "Makeham", "bathtub".  see ?basta for more information. Default = "simple"
#' @param niter  \code{numeric}. number of MCMC iterations to run the survival model. see ?basta for more information. Default = 25000
#' @param burnin  \code{numeric} Number of iterations removed so that the survival model has time to converge. see ?basta for more information. Default = 5001
#' @param thinning  \code{numeric} Number of iteration to run the survival model before saving a set of parameters. see ?basta for more information. Default = 20
#' @param nchain  \code{numeric} Number of chains to run the survival model. Default = 5001
#' @param ncpus  \code{numeric} Number of computer core to use. Default = 2
#' @param parentProb \code{numeric} XXXXXXXXXXX
#' @param minNrepro  \code{numeric} XXXXXXXXXXX
#' @param minNparepro  \code{numeric} XXXXXXXXXXX
#' @param minNseas \code{numeric} XXXXXXXXXXX
#' @param minNgro \code{numeric} Minimum number of weight needed to fit the growth models
#' @param minNIgro \code{numeric} Minimum number of unique individuals needed to fit the growth models
#' @param MeasureType \code{vector of characters} Name of the type of measurements that should be included.  Default = NULL, all measurement type are included.
#' @param models_gro \code{vector of characters} indicating the growth models that need to be fit.The following models are supported : logistic, gompertz, chapmanRichards, vonBertalanffy, polynomial. default = "vonBertalanffy"

#' @return a list including the results and summary of each analysis
#' @export
#'
#' @examples
#' data(core)
#' data(collection)
#' PlotDir = paste0(tempdir(check = TRUE),'\\temp')
#' dir.create(PlotDir)
#'
#' out <- tx_report(species = "Gorilla gorilla", taxa = "Mammalia",
#'                  core, collection, 
#'                  PlotDir = PlotDir,Sections = c('sur'),
#'                  sexCats = c("Male", "Female"),
#'                  models_sur = "GO", shape = "simple",
#'                  models_gro = "vonBertalanffy",
#'                  niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3
#' )
#'
#' list.files(PlotDir)
#' unlink(PlotDir, recursive = TRUE)
#'
tx_report <- function(species, taxa,  core, collection, PlotDir = NULL,
                      weights = NULL,parents = NULL, contraceptions = NULL,
                      repout = list(), Sections = c('sur', 'rep', 'gro'),
                      sexCats = c("Male", "Female"), minN= 50, minDate= "1980-01-01",
                      extractDate = NULL, minNsur = 50, minlx = 0.1, MinBirthKnown = 0.3, maxOutl = 100,
                      models_sur = "GO", shape = "bathtub",
                      niter = 25000, burnin = 5001, thinning = 20, nchain = 3, 
                      ncpus = 2,
                      parentProb = 80, minNrepro = 100, minNparepro = 30, minNseas = 50, 
                      minNgro =100,minNIgro = 50, MeasureType = "",
                      models_gro = "vonBertalanffy"
) {
  assert_that(is.character(taxa))
  assert_that(taxa %in% c("Mammalia", "Aves", "Reptilia", "Amphibia", 
                          "Chondrichthyes", "Actinopterygii"),
              msg = "taxa must one of 'Mammalia', 'Aves', 'Reptilia', 'Amphibia', 
                          'Chondrichthyes', or 'Actinopterygii'")
  assert_that(is.character(Sections))
  assert_that(all(Sections %in% c("sur", "gro", "rep")))
  assert_that(is.character(species))
  
  if(!is.null(extractDate)){
    extractDate = lubridate::as_date(extractDate)
  } else{
    extractDate = max(lubridate::as_date(core$DepartDate), na.rm = T)
  }
  
  minDate = lubridate::as_date(minDate)
  assert_that(is.data.frame(core))
  assert_that(is.data.frame(collection))
  assert_that(core  %has_name% c("anonID", "BirthDate", "DepartDate",
                                 "EntryDate", "MaxBirthDate", "MinBirthDate",
                                 "EntryType", "DepartType", "DepartFrom", "firstInst", 
                                 "LastTXDate", "DeathDate", "lastInst","globStat",
                                 "LastCollectionScopeType","FirstCollectionScopeType"))
  assert_that(collection  %has_name% c("RecordingInstitution", "ChangeDate", 
                                       "ScopeType", "AnimalID"))
  
  if("gro" %in% Sections){
    assert_that(is.data.frame(weights))
    assert_that(weights %has_name% c("MeasurementValue", "MeasurementValue", "MeasurementDate", "CollectionScopeType", "UnitOfMeasure", "ExcludedFromNorms", "EstimatedMeasurement", "RecordType", "MeasurementType", "anonID", "AnonInstitutionID"))
  }
  if("rep" %in% Sections){
    assert_that(is.data.frame(parents))
    assert_that(is.data.frame(contraceptions))
    # assert_that(parents %has_name% c()) XXXXXXXXXXXXXXXXXXXXXX
    # assert_that(contraceptions %has_name% c()) XXXXXXXXXXXXXXXXXX
  }
  
  assert_that(is.character( sexCats))
  assert_that(all(sexCats %in% c("Male", "Female", "All")))
  assert_that(is.numeric( maxOutl))
  assert_that( maxOutl <= 100)
  assert_that(is.numeric(minNsur))
  assert_that(minNsur > 0)
  assert_that(is.numeric(minlx))
  assert_that(minlx > 0)
  assert_that(minlx < 1)
  assert_that(is.numeric(MinBirthKnown))
  assert_that(MinBirthKnown > 0)
  assert_that(MinBirthKnown <1)
  assert_that(is.numeric(niter))
  assert_that(niter > 0)
  assert_that(is.numeric(burnin))
  assert_that(burnin > 0)
  assert_that(burnin < niter)
  assert_that(is.numeric(thinning))
  assert_that(thinning > 0)
  assert_that(thinning < niter)
  assert_that(is.numeric(nchain))
  assert_that(nchain > 0)
  assert_that(is.numeric(ncpus))
  assert_that(ncpus > 0)
  assert_that(is.character(models_sur))
  assert_that(all(models_sur %in% c("GO", "EX", "LO", "WE")))
  assert_that(is.character(shape))
  assert_that(all(shape %in% c("simple", "bathtub", "Makeham")))
  checkmate::assert_directory_exists(PlotDir)
  
  assert_that(is.numeric(parentProb))
  assert_that(parentProb > 0)
  assert_that(is.numeric(minNrepro))
  assert_that(minNrepro > 0)
  assert_that(is.numeric(minNparepro))
  assert_that(minNparepro > 0)
  assert_that(is.numeric( minNseas))
  assert_that( minNseas > 0)
  
  assert_that(is.numeric( minNIgro))
  assert_that( minNIgro > 0)
  assert_that(is.numeric(minNgro))
  assert_that(minNgro > 0)
  assert_that(is.character(MeasureType))
  assert_that(is.character(models_gro ))
  assert_that(all(models_gro %in% c("logistic", "gompertz", "chapmanRichards", "vonBertalanffy", "polynomial", "gam")), msg = "The growth models supported are: logistic, gompertz, chapmanRichards, vonBertalanffy, and polynomial, in addition to GAM.")
  
  # --------------------- #
  # ---- Prep. data: ----
  # --------------------- #
  ## Extract Data
  Dat <- select_species(species, core, collection,
                        minDate = minDate , extractDate = extractDate, Global = TRUE) 
  repout$general = Dat$summary
  for (sx in sexCats){
    sexDat <- select_Longthreshold( Dat$data,  sexCats = sx, 
                                    PlotDir= PlotDir, minN = minN ,
                                    maintitle = glue::glue("{species}_{sx}") )
    repout$summary[[sx]] = sexDat$summar
    # -------------------------- #
    # ---- Survival Module: ----
    # -------------------------- #
    # Run survival analyses:
    if ("sur" %in% Sections) {
      repout$surv[[sx]] <- Sur_main(data.core = sexDat$data,
                                     BirthType = "All",
                                    xMax = 120, PlotDir = PlotDir,
                                    models = models_sur, shape= shape, 
                                    outlLev1 = sexDat$summar$GapThresh,
                                    mindate = minDate, minNsur = minNsur, 
                                    minlx = minlx , MinBirthKnown = MinBirthKnown, 
                                    niter = niter, burnin = burnin, thinning = thinning, nchain = nchain, 
                                    ncpus = ncpus, plotname = species)
    }
    
    # # ------------------------------ #
    # # ---- Reproduction module: ----
    # # ------------------------------ #
    # # Reproduction module list:
    # if ("rep" %in% Sections) {
    #   # Reproduction module list:
    #   repout$repr <- RunRepro(sexDat = sexDat, sexCats = sexCats, coresubset= coresubset,
    #                    PlotDir = PlotDir,
    #                      subinst = subinst, minNseas = minNseas, 
    #                    mindate =minDate,
    #                    newContra = newContra, parentProb = parentProb, 
    #                    minNrepro = minNrepro,minNparepro = minNparepro,  speciesID = speciesID)
    # }
    
    # ----------------------------- #
    # ---- Body weight module: ----
    # ----------------------------- #
    # Growth module list:
    if ("gro" %in% Sections) {
      repout$weig[[sx]] <- Gro_Main(data = weights, coresubse = sexDat$data,
                                    taxa = taxa, species = species,
                                    BirthType = NULL, 
                                    agemat = NA, percentiles = c(2.5,97.5),
                                    PlotDir = PlotDir, type = "weight",
                                    MeasureType = MeasureType,
                                    minNgro = minNgro, minNIgro = minNIgro, 
                                    models = models_gro,
                                    mindate = minDate) 
    }
  }
  
  return(repout)
}

