globalVariables(c("Age", "anonID", "MeasurementValue", "age0", "agem", "ager", "anonid", "keep2", "keep3",
    "lwr", "nb", "pop", "pred", "pred1", "pred2", "res", 'birthType', 'Sex','cond_captivebirth',
    'cond_sex','MeasurementDate','MeasurementType', 'CollectionScopeType','UnitOfMeasure',
    'ExcludedFromNorms','EstimatedMeasurement','RecordType','BirthDate','age','toKg',
    'la', "KEEP", "LSQ", "QAIC", "index", "k", "keep1", "percent50", "AnonInstitutionID",
    "juv", "Depart.Date", "DepartDate", "Entry.Date", "EntryDate", "Max.Birth.Date",
    "Min.Birth.Date", "deparAge", "entryAge", "idsame",
    "outBasta", "remex", "xv", "AnimalID", "Birth.Date", "ChangeDate", "Depart.Type",
    "DepartType", "Entry.Type", "FirstCollectionScopeType", "Gap",
    "LastCollectionScopeType", "MaxBirthDate", "MinBirthDate",
    "RecordingInstitution", "ScopeType", "causeDeath", "collections",
    "iniAge", "lifespans", "maxtime", "ngap", "tempBirths","Analyzed", "Class", "Fert_Analyzed",
    "Fert_error", "Litt_Analyzed", "Litt_error", "N", "NAdult_rep", "NBasta", "NOffsp",
    "NOffsp_prob", "NOffsp_raw", "NParent", "NParent_prob", "NParent_raw"," NReprEvent",
    "NWeight", "NWeight_raw", "SeasNorth_Analyzed", "SeasNorth_Nbirth",
    "SeasNorth_error", "SeasSouth_Analyzed", "SeasSouth_Nbirth", "SeasSouth_error",
    "Species", "binSpecies", "collection", "core", "coresubset",
    "error", "globDir", "iparal", "repout", "NReprEvent", "contraceptions",  "parents",
    "weights","ADULTS", "AnonID", "Date", "Date_age","OffspringCollectionScopeType",
    "Offspring_BirthDate", "Offspring_Inst", "ParentAnonID",
    "ParentCollectionScopeType", "ParentOriginType", "Parent_BirthDate",
    "Parent_birthType", "Probability", "To", "ageAds", "ageBirth", "ageBirthDisc",
    "birthYear", "contra", "currentInst", "dist", "firstInst",
    "minNrepro", "minNseas", "mintime", "sexDat", "subinst",
    "subpar", "sx", "taxa", "AnimalAgeDays", "AnimalAnonID", "AnimalType", "BirthDateEstimateEnd",
    "BirthDateEstimateStart", "BirthObserved", "BirthType", "Birth_Uncertainty",
    "Date_Uncert", "DeathDate", "DeathDateEstimateEnd", "DeathDateEstimateStart",
    "Death_Uncertainty", "ExcludededFromNorms", "FirstAcquisitionDate",
    "FirstHoldingInstitution", "GlobalStatus", "InstitutionAnonID", "LastTXDate",
    "LengthValueCm", "MaxDeathDate", "MeasurementDateEstimateEnd",
    "MeasurementDateEstimateStart", "MinDeathDate", "ParentType", "Parent_Age",
    "Parent_BirthType", "RelevantDeathInformationType", "SexType", "SpeciesName",
    "WeightValueKg", "ageVec", "litter", "litterSize", "out", "parent",
    "sexCats", "subparfert", "moves", "maxAge", 'analyzed', ":=","AnyLocalCollectionFlag",
    "Ages", "Lower", "Upper", "ple", "GAN", "Meann", "FatherAnonID", "residual",
    "Father_Age", "MeanBirthDate", "MotherAnonID", "Mother_Age", "finAge", "vbGrowthtest"), package ="ISRverse")
